### ISSUE TITLE
Is there any way to specify a port mapping ?

### ISSUE THREAD

**Issue by grillorafael** [testcontainers/testcontainers-node#104]
I wasn't able to find in the code or docs but I figured it would be best to ask here. Is there any way to specify which host post my container port should be mapped to in case I need a strict port mapping ?

**Comment by cristianrgreco** [comment]
Hi @grillorafael, it's not possible to specify the host mapping, this is to avoid port collisions

**Comment by grillorafael** [comment]
Sounds good! I managed to find a decent way around it and use the assigned ports that we get so I'm good with that! thanks!
