### ISSUE TITLE
Unable to exec psql command within jest test

### ISSUE THREAD

**Issue by nellyged** [testcontainers/testcontainers-node#117]
My code successfully spins up a new docker container and starts up the postgres instance. The first command runs fine (I tested this and then ran another command that simply grabs the date from the container and it returned the proper value)

But when I attempt to connect to psql I get this error:

{ output:
         'OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \\"docker exec -it e2d9242bd30749f91412c6d5e6c71a2ead06e98dd9dd035edecb9421d3714114 /bin/sh;\\": stat docker exec -it e2d9242bd30749f91412c6d5e6c71a2ead06e98dd9dd035edecb9421d3714114 /bin/sh;: no such file or directory": unknown\r\n',
        exitCode: 126 }

Here is the code I am using:

describe('Start Test', () => {
  it('Connect', async () => {
    const container = await new GenericContainer('postgres', 'latest')
      .withEnv('POSTGRES_PASSWORD', 'password')
      .withEnv('POSTGRES_DB', 'databaseName')
      .withEnv('POSTGRES_USER', 'username')
      .start()
    console.log(container.getId())
    const cmd = `docker exec -it ${container.getId()} /bin/sh;`
    await container.exec([cmd])
    const logs = await container.exec([`psql -d databaseName -U username -c ${"'"}CREATE TABLE test()${"'"}`])
    console.log(logs)
  })
})

**Comment by cristianrgreco** [comment]
Hi, I'm not sure if it's GitHub's formatting but ensure the command is split by word, for example like in the README:

```
const { output, exitCode } = await container.exec(["echo", "hello", "world"]);
```

**Comment by cristianrgreco** [comment]
Hi @nellyged, was my last answer able to help?

**Comment by nellyged** [comment]
> Hi @nellyged, was my last answer able to help?

Thanks for the response I was actually able to figure out making dB changes using typeorm once the docker instance is running
