### ISSUE TITLE
getContainerIpAddress() does not work as expected in Gitlab CI docker runner

### ISSUE THREAD

**Issue by KaiStapel** [testcontainers/testcontainers-node#15]
I have a similar issue like #7 

I am starting two docker containers in my tests (postgres and rabbitMQ). Then I construct the connection strings using `container.getContainerIpAddress()` and `container.getMappedPort()`. Everything works locally. However, in Gitlab CI I get the following error.
```
     Error: connect ECONNREFUSED 127.0.0.1:44937
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
```

When checking the value of `getContainerIpAddress()` it always returns `localhost` even when run in the Gitlab CI docker runner. While the Java counter part of testcontainers returns a real IP address like `172.17.0.1` in Gitlab CI.

Can you adjust your code to behave like your Java counter part?

**Comment by cristianrgreco** [comment]
Hi @KaiStapel 

Have you followed the docs here: https://www.testcontainers.org/supported_docker_environment/continuous_integration/gitlab_ci/ ?

Testcontainers will look for a `DOCKER_HOST` env variable, so as long as you are setting that it should work.

**Comment by KaiStapel** [comment]
I am not using dind service. I am directly using the docker daemon of the docker runner itself which is on default socket `unix:///var/run/docker.sock`. This works fine with Java, but fails with NodeJS as the IP is not resolved correctly (or at all).

**Comment by KaiStapel** [comment]
Looks like the Java code is doing some strange stuff if run inside a container: https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/dockerclient/DockerClientConfigUtils.java#L48

**Comment by cristianrgreco** [comment]
@KaiStapel Could you please post the value of the `DOCKER_HOST` env variable in Gitlab CI?

**Comment by KaiStapel** [comment]
In my case it is undefined. That means the default socket `unix:///var/run/docker.sock` is being used.

**Comment by cristianrgreco** [comment]
@KaiStapel if you're using the socket, wouldn't `localhost` be the correct hostname?

**Comment by KaiStapel** [comment]
No. I guess my setup is special because I am re-using the docker deamon of the gitlab CI docker runner itself. That means the docker runner first creates a container for the build. Lets call it `build`. Then, inside of `build`, the outer deamon is used to create a new container like `postgres`. Both containers are "local" to the runner. But from within the `build` container, in order to access the `postgres` container, one needs the IP address of the runner.

**Comment by cristianrgreco** [comment]
Seems a bit of a strange setup, as you have containers running on different networks but expect them to communicate with each other. Why not use `dind`?

**Comment by KaiStapel** [comment]
Our gitlab admin suggested to not use dind because of security concerns.

Java uses an IP if run inside a container: https://github.com/testcontainers/testcontainers-java/blob/1.11.4/core/src/main/java/org/testcontainers/dockerclient/DockerClientConfigUtils.java#L57

**Comment by KaiStapel** [comment]
If you do not want feature parity between java and node testcontainers that is fine. I will find a workaround in my code.

**Comment by cristianrgreco** [comment]
I had missed the logic for finding the default gateway when running in a container, I will look at implementing this soon (at work at the moment).

Just to confirm this will fix your issue, can you confirm that:
1. There exists `/.dockerenv` in your file system.
2. The output of this command: `sh -c "ip route|awk '/default/ { print $3 }'"`

**Comment by KaiStapel** [comment]
1. `/.dockerenv` exists inside the container that is running on the Gitlab CI runner.
2. The output of `docker run alpine:3.5 sh -c "ip route|awk '/default/ { print $3 }'"` is `172.17.0.1\n`

Note that in Java testcontainers the command is run inside a "tiny" container, i.e. `alpine:3.5`.

The follwoing works for me both locally and on Gitlab (which is more or less equivalent to what is done in Java testcontainers):

    const DEFAULT_DOCKER_HOST: string = "unix:///var/run/docker.sock";

    const getContainerIpAddress = async () => {
      const dockerHost = process.env.DOCKER_HOST || DEFAULT_DOCKER_HOST;

      const parsedDockerHost = url.parse(dockerHost);

      switch (parsedDockerHost.protocol) {
        case "http:":
        case "https:":
        case "tcp:":
          return parsedDockerHost.host;
        case "unix:":
        case "npipe:":
          return await getContainerIp(parsedDockerHost);
        default: return "localhost";
      }
    };

    const getContainerIp = async (dockerHost: url.Url) => {
      try {
        // https://github.com/docker/docker/blob/a9fa38b1edf30b23cae3eade0be48b3d4b1de14b/daemon/initlayer/setup_unix.go#L25
        if (fs.existsSync("/.dockerenv")) {
          const dockerode = new Dockerode({socketPath: dockerHost.path});
          const stream = new WritableStream();
          await dockerode.run("alpine:3.5", ["sh", "-c", "ip route|awk '/default/ { print $3 }'"], stream);
          const output = stream.toString();
          if (!!output) {
            return output.trim();
          }
        }
      } catch (err) {
        console.error("Could not check existence of file '/.dockerenv'. Defaulting to container host 'localhost'.", err);
      }
      return "localhost";
    };

**Comment by cristianrgreco** [comment]
Hi @KaiStapel, could you please try v2.0.0 and report back?

**Comment by KaiStapel** [comment]
Can you point me to a migration guide? v2 does not seem to be backwards compatible.

**Comment by cristianrgreco** [comment]
@KaiStapel Yes, it's a major release because there's a breaking change. If you have:

```javascript
GenericContainer.fromDockerfile()
```

Then you just have to add `.build()` at the end, as `fromDockerfile` now returns a builder.

**Comment by KaiStapel** [comment]
Looking good locally and on Gitlab:

For example:
```
PG connect string: postgres://postgres:postgres@172.17.0.1:40279
```

Can you give a short summary how you fixed this without #16 ?

**Comment by cristianrgreco** [comment]
@KaiStapel Great news.

These are the changes:

https://github.com/testcontainers/testcontainers-node/blob/d9696834d842f9b8565cb40d1c565152698338a8/src/docker-client-factory.ts#L25-L29
https://github.com/testcontainers/testcontainers-node/blob/d9696834d842f9b8565cb40d1c565152698338a8/src/docker-client-factory.ts#L68-L79

Let me know if we can close this issue.

**Comment by KaiStapel** [comment]
Ah, you used a wormhole, of course 😃

Yes, you can go ahead and close this ticket. Thanks for your support.

**Comment by cristianrgreco** [comment]
Thank you for raising the issue 🙂

**Comment by Quaiks** [comment]
Hello!

I am having a related issue. `getContainerIpAddress` always returns localhost.

https://github.com/testcontainers/testcontainers-node/blob/d9696834d842f9b8565cb40d1c565152698338a8/src/generic-container.ts#L113-L119

I don't get why is returning the client host instead of the ip of the actual container. Is a design decision? Am I mixing concepts?

Thanks in advance
