### ISSUE TITLE
Disabling Ryuk

### ISSUE THREAD

**Issue by JavoByte** [testcontainers/testcontainers-node#150]
Hello.

I am using this project to run integration tests on a node project and I want to introduce this to bitbucket pipelines.
However, bitbucket pipelines don't allow privileged mode on docker instances. This means that Ryuk container is failing to run. I saw in [documentation](https://www.testcontainers.org/features/configuration/) that I could set `TESTCONTAINERS_RYUK_DISABLED` but this doesn't seem to work. 

Is there any way to overcome this problem?

**Comment by cristianrgreco** [comment]
Hi @JavoByte, indeed this isn't currently supported, let me know if there's any reason not to merge the referenced PR 🙂

**Comment by cristianrgreco** [comment]
Released in https://github.com/testcontainers/testcontainers-node/releases/tag/v4.6.0, please close the issue if resolved
