### ISSUE TITLE
Support for regular expressions in LogWaitStrategy

### ISSUE THREAD

**Issue by sondrele** [testcontainers/testcontainers-node#152]
I have a case where it would be convenient to wait for a variable log message.

Specifially, a migrate-command with [flyway](https://github.com/flyway/flyway-docker) will output something along the line of
```
Successfully applied x migrations to schema `my-schema`  (execution time 00:01.123s)
```

where `x` is a variable number depending how many migrations were actually applied.

The strategy seams a little less prone to errors with `Wait.forLogMessage(/Successfully applied \d+ migrations/)` than the current strategy of `Wait.forLogMessage("Successfully applied")` - the intention of the code is also more clear.

I'm sure there are other strategies that would also work for my specific use case, and I could always implement my own RegExpLogWaitStrategy, but this seams like a fairly common use case.

I'd be happy to make a contribution if you think it's a good addition to the library.

**Comment by cristianrgreco** [comment]
HI @sondrele, good idea! I'm happy to take a look at this later and implement it as suggested

**Comment by cristianrgreco** [comment]
@sondrele check out the referenced PR, unless you have any issues I'll merge 🙂

**Comment by sondrele** [comment]
@cristianrgreco  Perfect! :ok_hand:

**Comment by cristianrgreco** [comment]
Released in https://github.com/testcontainers/testcontainers-node/releases/tag/v4.7.0 🙂
