### ISSUE TITLE
Can we specify a port to bind to?

### ISSUE THREAD

**Issue by helgridly** [testcontainers/testcontainers-node#156]
I can spin up a container `.withExposedPorts(1234)` but that doesn't let me specify the port that it gets bound to on the host. I know I can get call `.getMappedPort(1234)` after the container is started, but I need to define a healthcheck that curls the container (like in the example), and the mapped port isn't available then.

Can we specify a fixed port on the host to bind to, and error if it's not available?

**Comment by cristianrgreco** [comment]
Hi @helgridly, there isn't a way to specify a port to bind to. 
The health checks run within the container so if the port is 1234 you can use that directly (eg `curl http://localhost:1234`)

**Comment by helgridly** [comment]
Oh - I assumed they ran from the outside, on the host. Thanks!
