### ISSUE TITLE
Allow multiple compose files

### ISSUE THREAD

**Issue by lamuertepeluda** [testcontainers/testcontainers-node#158]
Hi there,

I would like to use [multiple compose file](https://docs.docker.com/compose/extends/#multiple-compose-files), so that I can override some parameters in my `docker-compose.test.yml` file wrt. the main `docker-compose.yml` file.

I seen now that the options for the docker compose environment, and in particolar [this line](https://github.com/testcontainers/testcontainers-node/blob/abd3d47dfd6aa9ba5e2373bb9efe2020ca06e248/src/docker-compose-environment.ts#L172) do not allow for passing multiple compose files.

The underlying [docker-compose](https://github.com/PDMLab/docker-compose#options) library, however, accepts multiple compose files as string array `string[]`.

Would it be possible to unlock this feature? Or is there any peculiar reason why this was somehow blocked?

Thanks

**Comment by lamuertepeluda** [comment]
Maybe it is just a TypeScript definition and documentation issue, after all 😅 

I just tried passing (in a `.js` file so that I don't get TS errors)

```js
    const composeFilePath = path.resolve(__dirname, '../')
    const composeFile = ['docker-compose.yml', 'docker-compose.test.yml']

    environment = await new DockerComposeEnvironment(
      composeFilePath,
      composeFile
    )
      .withStartupTimeout(120000)
      .withBuild() 
      .up()
```

And it worked pretty fine!

Thanks God nor your library nor docker-compose makes any runtime validation of the arguments! 😄

**Comment by cristianrgreco** [comment]
> Thanks God nor your library nor docker-compose makes any runtime validation of the arguments! 😄

Haha that's great! I'm happy to change the API to allow for multiple files, will there be cases where we use files in different paths? If so I think I might inline `composeFilePath` and `composeFIle`, so `composeFile` becomes the full path including file

**Comment by lamuertepeluda** [comment]
I think it could be, even though it's not that relevant for me, however the docker-compose library documentation says the files must be in the same cwd...

**Comment by cristianrgreco** [comment]
Cool, the cwd will be the same then. Check out the referenced PR, will merge unless you see any issue 🙂

**Comment by cristianrgreco** [comment]
Released in https://github.com/testcontainers/testcontainers-node/releases/tag/v5.1.0, thanks again!
