### ISSUE TITLE
Add ability to get internal container ip

### ISSUE THREAD

**Issue by Shahan** [testcontainers/testcontainers-node#159]
When I create a container with `NetworkMode`, I have no chance to find out what is IP address of the container host in this network.

Experimentally I observed that internal container hostname may be computed as `startedContainer.getId().substr(0, 12)`, however, there is still even no workaround to get IP address. 

Is it possible to add any method that will help us to obtain container's IP address inside given network?

Please let me know if you need more details.

UPDATE: small explanation example:
```
//create network
const network = await new Network()
    .start();

//start alpine container in created network
const alpineContainer = await new GenericContainer("alpine")
  .withNetworkMode(network.getName())
  .start();

// create redis container in the same network
const redisContainer = await new GenericContainer("redis")
       .withNetworkMode(network.getName())
      .start();
```

The question is: by what ip (not hostname) may `redisContainer` host be accessed from `alpineContainer` host inside created `network`?

UPDATE 2:
Well, I found workaround here: https://github.com/testcontainers/testcontainers-node/issues/36 , but it's ugly. It's exactly the same as my problem.
This is also a related issue: https://github.com/testcontainers/testcontainers-node/issues/67 . It was closed because issuer could obtain hostname of container, but exposing `inspect` would allow him to obtain also an IP address.

**Comment by cristianrgreco** [comment]
hi @Shahan, thanks for raising the issue. I just had a read of the testcontainers-java docs and it seems they've solved this by using network aliases, see advanced networking at the bottom at https://www.testcontainers.org/features/networking/. Would something like that work for you? it seems they are quite against exposing the internal IP because it would cause other issues in remote environments

**Comment by Shahan** [comment]
hi @castarco 
thank you for your attention to my problem.

I agree that the proposed solution with hostnames (from your example) is fine for normal people because hostnames are much better than IP addresses for multiple reasons. Unfortunately, it's not my case, because in my case my tests should verify that the application is capable to work with IP addresses correctly. 
I understand, that exposing internal IP addresses may cause various problems in a remote environment, so I would suggest a tradeoff: is it possible to add a getter of Network settings for `StartedContainer`? Then everyone, who will need an IP address, will be able to obtain it from the network settings.

Just look how complex is it to obtain IP address now:
```
(await (startedContainer.dockerClient.dockerode.getContainer(startedContainer.getId())).inspect()).NetworkSettings.Networks[network.getName()].IPAddress;
```
Here we have to access private fields 2 times: `dockerClient` and `dockerode`. Seems to be not good.
I would suggest adding a getter of network settings to StartedContainer to make the job more clear:
```
startedContainer.getNetworkSettings().Networks[this.network.getName()].IPAddress
```
How do you think, is it possible?

**Comment by cristianrgreco** [comment]
@Shahan What do you think about this:

```javascript
const network = await new Network()
    .start();

const container = await new GenericContainer("alpine")
  .withNetworkMode(network.getName())
  .start();

const networkIpAddress = container.getNetworkSettings(network.getName()).ipAddress;
```

**Comment by cristianrgreco** [comment]
Ideally I would like to make the breaking change of renaming `container.getContainerIpAddress()` to `container.getHost()`, and then this PR could be simplified to `container.getIpAddress(networkName: string)`.. 🤔

**Comment by Shahan** [comment]
> @Shahan What do you think about this:
> 
> ```js
> const network = await new Network()
>     .start();
> 
> const container = await new GenericContainer("alpine")
>   .withNetworkMode(network.getName())
>   .start();
> 
> const networkIpAddress = container.getNetworkSettings(network.getName()).ipAddress;
> ```

Looks even better than I could dream about 👍  Thank you!




> Ideally I would like to make the breaking change of renaming the existing `container.getContainerIpAddress()` to `container.getHost()`, and then this PR could be simplified to `container.getIpAddress(networkName: string)`.. 🤔
Even though `getContainerIpAddress` method result is confusing, but its strange behavior is fully in accordance with java version of test containers :P It would be great, if breaking change will be done in both java and node-js (nevermind, just thinking out loud)

**Comment by cristianrgreco** [comment]
> Looks even better than I could dream about 👍 Thank you!

Amazing, how rare that I can make someone's dreams come true! 😄 

> Even though getContainerIpAddress method result is confusing, but its strange behavior is fully in accordance with java version

That's what I thought, but according to this example they also use `getHost()`: https://www.testcontainers.org/quickstart/junit_5_quickstart/

**Comment by Shahan** [comment]
> That's what I thought, but according to this example they also use `getHost()`: https://www.testcontainers.org/quickstart/junit_5_quickstart/

@cristianrgreco  You are right, in java they keep 3(!) methods that return the same:
1. Deprecated `getIpAddress()` that returns `getHost()`. Code pointer: https://github.com/testcontainers/testcontainers-java/blob/b28f6efafa8f60e70f95670fecfde29eafbf4e4b/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L1257
2. `getContainerIpAddress()` that returns `getHost()`. Code pointer: https://github.com/testcontainers/testcontainers-java/blob/b28f6efafa8f60e70f95670fecfde29eafbf4e4b/core/src/main/java/org/testcontainers/containers/ContainerState.java#L48
3. `getHost()` that returns docker client host IP address. Code pointer: https://github.com/testcontainers/testcontainers-java/blob/b28f6efafa8f60e70f95670fecfde29eafbf4e4b/core/src/main/java/org/testcontainers/containers/ContainerState.java#L57

So I would suggest to follow the same way by adding one more method `getHost` rather than renaming of existing. It will help to avoid breaking changes.

**Comment by cristianrgreco** [comment]
I think they want to remove the other methods and keep just `getHost()`

<img width="484" alt="Screenshot 2020-11-06 at 09 24 47" src="https://user-images.githubusercontent.com/10348798/98349481-f14fbe00-2011-11eb-8668-f34ded2f8b05.png">

I'm happy to make it a breaking change because I think the two methods we end up with are quite clear:

```javascript
getHost();
getIpAddress(networkName: string);
```

Let me know if you're happy for me to merge https://github.com/testcontainers/testcontainers-node/pull/162

**Comment by Shahan** [comment]
Regarding breaking change I can only warn about thousands of javascript tests around the world that will fail in runtime after a major update due to the not found method 'getContainerIpAddress()`.

I'm fully happy with all changes in #162, I'm ready to use the new version right after the merge.

**Comment by cristianrgreco** [comment]
This is what major updates are for 🙂 I think in the long-term the change is beneficial so the sooner the better. This functionality is available in https://github.com/testcontainers/testcontainers-node/releases/tag/v6.0.0

**Comment by Shahan** [comment]
@cristianrgreco  Thanks a lot :)
