### ISSUE TITLE
Expose Host Ports to Container

### ISSUE THREAD

**Issue by traviscollins** [testcontainers/testcontainers-node#163]
I have the need for a container launched by testcontainers-node (the client) to communicate with a non-containerized service that I'm testing against (the server). The Java version of TestContainers supports ```Testcontainers.exposeHostPorts(localServerPort);```

https://www.testcontainers.org/features/networking/#exposing-host-ports-to-the-container

It does not appear that there is an equivalent function in testcontainers-node. Correct?

**Comment by cristianrgreco** [comment]
@traviscollins check out the referenced PR, does it suit your needs?

**Comment by traviscollins** [comment]
It does! Wow. Thanks!

**Comment by cristianrgreco** [comment]
released in https://github.com/testcontainers/testcontainers-node/releases/tag/v6.1.0 🙂
