### ISSUE TITLE
Can't use 'redirection' (<) with StartedTestContainer exec command 

### ISSUE THREAD

**Issue by mtwinux** [testcontainers/testcontainers-node#166]
Hello. 
My environment : 
- windows 10
- Node.js  [v12.18.4],NPM [ 6.14.8]
- loopback 4 [loopback@3.27.0]
- testcontainers [testcontainers@6.1.1]
- dockerode [dockerode@3.2.1]
- Docker [Docker version 19.03.13, build 4484c46d9d]

My problem :) 
I am using GenericContainer to set up a MariaDB container and it goes well but i need to run one or more sql script file to the container. So, what i did is "withBindMount" my local folder where sql are, and then i use the StartedTestContainer **exec** command to run mysql giving him the sql file every time i want to load one.
My problem is that the container runs, mysql is launch but it's like the redirect is ignored. Someone can tell me how to that ? :   

**I tried with :** 
const execResult = await mariaDB.exec([     'mysql',     '-uroot',     '-pxxxxxxxx',     '--default-character-set=utf8', 	'<', '/etc/mysql/anyfile.sql'   ]);
_and_
const execResult = await mariaDB.exec([     'mysql',     '-uroot',     '-pxxxxxxxx',     '--default-character-set=utf8', 	'< /etc/mysql/anyfile.sql'   ]);

**When debugging, i see that it all goes right to the dockerode module exec function who makes the post call to the container. Problem is how the post call is handled by the container i guess...** 

Meanwhile, i'm using **.withBindMount(mysqlFolder, '/docker-entrypoint-initdb.d')** and it works. The container use this folder to ckeck for some sql at startup . It's a workaround. I hope there is a way.

**Comment by cristianrgreco** [comment]
hi, thanks for raising the issue.

i also cannot get redirection working using the underlying `dockerode` library, i've raised an issue here: https://github.com/apocas/dockerode/issues/600.

as a temporary workaround, instead of `["echo", "hello world", ">", "/tmp/test.txt"]` you could do `["/bin/sh", "-c", "echo 'hello world' > /tmp/test.txt"]`, which seems to work as expected

**Comment by mtwinux** [comment]
thanks ! i will try this 👍

**Comment by dmitri-gb** [comment]
_Redirection_ is a feature of the _shell_. When simply executing `['mysql', '-u...', '-p...', '<', 'file']`, there's no shell involved, so naturally, no redirection can take place. `<` and whatever follows are just arguments to `mysql`.

If you really need to use redirection, you'll need to pass the command through a shell, e.g.
```
['/bin/sh', '-c', 'mysql -u... -p... < file']
```

Another solution would be to have `mysql` read the file itself:
```
['mysql', '-u...', '-p...', '-e', 'source /etc/mysql/anyfile.sql']
```

Yet another solution would be to launch `mysql` and pipe your script directly into its standard input. This is not supported by the testcontainers-node API, but can be done [using Dockerode](https://www.npmjs.com/package/dockerode#streams-goodness).

**Comment by cristianrgreco** [comment]
Thanks @dmitri-gb !
