### ISSUE TITLE
Allow passing a custom zookeeper image into the Kafka container

### ISSUE THREAD

**Issue by jackkainov** [testcontainers/testcontainers-node#167]
Hi,
the image path for zookeeper is hardcoded here https://github.com/testcontainers/testcontainers-node/blob/master/src/modules/kafka/kafka-container.ts#L66
With the recent Docker Hub limitations we started using our own private Docker registry inside the company, but unfortunately, the zookeeper image is still pulled from the Docker Hub.
Do you think it could be possible to either accept a private registry URL or a custom zookeeper image URL in the Kafka container?
Thank you.

**Comment by katerina-semikina** [comment]
+1, faced docker hub rate limiting limitations. Possibility to use docker hub proxy would be perfect.

**Comment by cristianrgreco** [comment]
hi both, thanks for raising the issue. does the referenced PR work for you? I've exposed these settings via the constructor:

```typescript
const container: StartedKafkaContainer = await new KafkaContainer(
  "confluentinc/cp-kafka", // Kafka image
  "latest", // Kafka image tag
  undefined, // Host
  "confluentinc/cp-zookeeper", // ZK image
  "latest" // ZK image tag
)
  .withExposedPorts(9093)
  .start();
```

**Comment by jackkainov** [comment]
Hi @cristianrgreco , thank you for such a swift reaction. The proposed solution would definitely do a trick and in the next major version, API could be cleaned up :) Also, Kafka is removing [this](https://www.confluent.io/blog/removing-zookeeper-dependency-in-kafka/) dependency so maybe we won't even need it in the new version.

**Comment by cristianrgreco** [comment]
Sounds good! Released in https://github.com/testcontainers/testcontainers-node/releases/tag/v6.2.0
