### ISSUE TITLE
Add support for loading registry auth information from config

### ISSUE THREAD

**Issue by crickford** [testcontainers/testcontainers-node#170]
`testcontainers-java` has great support for loading credentials for private registries from wherever they might be stored: https://github.com/testcontainers/testcontainers-java/blob/cf8c349e43ff05f7364c645cebb9061fda90aabf/core/src/main/java/org/testcontainers/utility/RegistryAuthLocator.java#L31

Registry credentials can be provided by the credential store, credential helpers, or even just the user's docker config file.

This is great in a CI environment, because it allows credentials to be managed completely separately from the application codebase. Would love to see similar functionality in `testcontainers-node`!

**Comment by cristianrgreco** [comment]
Hi @crickford, thanks for raising the issue. I've raised a PR which will find and use authentication from `$HOME/.docker/config.json`, using credential helpers if necessary, like in testcontainers-java

**Comment by cristianrgreco** [comment]
Thanks for reviewing @crickford. 
This has been released in 7.0.0 (https://github.com/testcontainers/testcontainers-node/releases/tag/v7.0.0).
