### ISSUE TITLE
Configuring containers with circular dependency

### ISSUE THREAD

**Issue by beepsoft** [testcontainers/testcontainers-node#173]
Hi,

I have two containers: a Hasura server and nodejs/express app. Both need to connect to the other, so I need to pass in an environment variable the IP:PORT of Hasura to nodejs/express and the IP:PORT of nodejs/express to Hasura. Is it possible to do this with testcontainers? 

With docker-compose it works, because the domain name is derived form the container's name. In testcontainers - setting up containers using GenericContainer -, however, this doesn't seem to be the case: I can only know what IP a container has once it has been run, but in case of the circular dependency I can only configure IP:PORT in one of the two containers.

Is there some solution to this?

**Comment by cristianrgreco** [comment]
Hi,

There's an example of creating a container with a name in the README:

```javascript
const { GenericContainer } = require("testcontainers");

const container = await new GenericContainer("alpine")
  .withName("custom-container-name")
  .start();
```

Other containers can then reference it by its name.

Does that help?

**Comment by cristianrgreco** [comment]
@beepsoft Was my previous message able to help?

**Comment by beepsoft** [comment]
@cristianrgreco oh, sorry for the delay. Yes, I gave explicit names for the containers and now it works all right. Thanks for your support!

**Comment by beepsoft** [comment]
More precisely I also needed to add a common network for the containers to see each other. So something like:

```js
...
this.network = await new Network({
    name: "test-network",
}).start();

this.postgresql = await new GenericContainer("postgres")
    .withName("test-postgresql")
    .withEnv("POSTGRES_DB", "test")
    .withEnv("POSTGRES_USER", "test")
    .withEnv("POSTGRES_PASSWORD", "test")
    .withExposedPorts(5432)
    .withNetworkMode(this.network.getName())
    .start();

this.hasura = await new GenericContainer("hasura/graphql-engine")
    .withName("test-hasura")
    .withEnv("HASURA_GRAPHQL_DATABASE_URL", `postgres://test:test@test-postgresql:5432/test`)
    .withEnv("HASURA_GRAPHQL_ADMIN_SECRET", "test")
    .withExposedPorts(8080)
    .withNetworkMode(this.network.getName())
    .start();
...
```
