### ISSUE TITLE
Error printed when $HOME/...docker.json does not exists

### ISSUE THREAD

**Issue by belgattitude** [testcontainers/testcontainers-node#181]
Since V7 and the introduction of auth https://github.com/testcontainers/testcontainers-node/pull/179, it seems that I have a problem regarding 

```
Error: ENOENT: no such file or directory, open '/home/username/.docker/config.json'
```

Is there a catch missing here ? -> 

https://github.com/testcontainers/testcontainers-node/blob/2c17ea715521a5fd57ae2cb68eb19ae81e8ffb9b/src/registry-auth-locator/index.ts#L27

**Comment by cristianrgreco** [comment]
Thanks @belgattitude. I've raised a PR, once it passes I'll release a patch 7.0.1

**Comment by belgattitude** [comment]
Wonderful.  Thanks a lot
