### ISSUE TITLE
Support for custom env-file in docker-compose

### ISSUE THREAD

**Issue by lamuertepeluda** [testcontainers/testcontainers-node#184]
Hi there, and thanks for your great work.

I am trying to use a different `.env` file configuration for my test environment, e.g. like in [the official docs for compose cli](https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files).

Specifically, I'd like to

```bash
 docker-compose --env-file .env.test -f docker-compose.yml -f docker-compose.test.yml up
```

I want to stress on the option `--env-file .env.test`, which is the missing bit here.

Looking at [the implementation](https://github.com/testcontainers/testcontainers-node/blob/873ace5cc730d608ddb69bdbdde5b99f8997c9f1/src/docker-compose-environment.ts#L173), it does not seem possible to pass it to the env file correctly.

I use a lot variable interpolation in my compose files, which helps me to have similar but separated configurations.

## Proposal

add a `envFile?: string` option to the `DockerComposeEnvironment` class and pass the option down to the compose engine.

**Comment by cristianrgreco** [comment]
Hi @lamuertepeluda, thanks! This sounds good, I'm open to PRs if not I'll take a look at this in the next few days 🙂

**Comment by lamuertepeluda** [comment]
Yes that method looks fine. I'll try to do my best to make a PR

**Comment by lamuertepeluda** [comment]
@cristianrgreco after further investigations I resolved my issue in a declarative way, using the [env_file](https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option) configuration option directly in the docker-compose! I honestly didn't know about that.
I don't think it's necessary to add this method, after all.

I am closing this issue, but feel free to re-open it if you feel like it's the case to implement such a mechanism all the same.

**Comment by cristianrgreco** [comment]
@lamuertepeluda Sounds good, thanks for sharing how you solved this
