### ISSUE TITLE
Told "Cannot get container as it is not running" when invoking getContainer()

### ISSUE THREAD

**Issue by TingeOGinge** [testcontainers/testcontainers-node#187]
Failure when trying to invoke `getContainer(CONTAINER_NAME)` on a docker-compose environment. 

## Context

I am setting up hooks for a Cucumber JS test suite to apply to an existing project that uses a PostgreSQL database and NodeJs webapp, both in running Docker containers and built / run using docker-compose. 

When I try to get one of the containers from my `StarterDockedComposeEnvironment` I get the error message `Cannot get container "inse2c_server" as it is not running` but I can see that the containers are in fact still running. 

## Process

1. I have a `hooks.js` file that contains the following code 
```
const {AfterAll, BeforeAll} = require('@cucumber/cucumber');
const { DockerComposeEnvironment, Wait } = require("testcontainers");
const path = require('path');

BeforeAll({ timeout: 60 * 1000 }, async function () {
    const composeFilePath = path.resolve(__dirname, "..", "..", "..");
    const composeFile = 'docker-compose.yml'

    this.environment = await new DockerComposeEnvironment(composeFilePath, composeFile)
        .withBuild()
        .withWaitStrategy("inse2c_server", Wait.forLogMessage("Server started on port 5000"))
        .up();
    this.server = this.environment.getContainer("inse2c_server");
    this.serverUrl = `http://${this.server.getContainerIpAddress()}:${this.server.getMappedPort(5000)}`;
});
    
AfterAll({ timeout: 60 * 1000 }, async function () {
    await this.environment.down();
});
```
2. And a  corresponding `docker-compose.yml` file 
```
version: '3'

services:
  db:
    container_name: inse2c_db
    image: inse2c_db:latest
    build: ./pg
    ports:
      - 5432:5432
  
  server:
    container_name: inse2c_server
    image: inse2c_server:latest
    build: ./server
    ports:
      - 5000:5000
```
3. I run `npm run test` which invokes Cucumber however it crashes before reaching my `Given, When, Then` steps (which are very simple and currently only serve to help me develop the hooks)

## Expected result

The started `inse2c_server` image is returned as a `GenericContainer`.  

## Current result
I receive the error message below
```
VError: a BeforeAll hook errored, process exiting: features/support/hooks.js:5: Cannot get container "inse2c_server" as it is not running
    at /PATH_OMITTED/node_modules/@cucumber/cucumber/lib/runtime/index.js:64:23
caused by: Error: Cannot get container "inse2c_server" as it is not running
    at StartedDockerComposeEnvironment.getContainer (/PATH_OMITTED/node_modules/testcontainers/dist/docker-compose-environment.js:174:19)
    at /PATH_OMITTED/features/support/hooks.js:14:36
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
That is despite being able to see the following containers still running, as my `AfterAll` function is never reached. 
![image](https://user-images.githubusercontent.com/34174536/106789224-e4129180-6649-11eb-892a-4050ca9f82d4.png)
```
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS         PORTS                     NAMES
299f74b2e25b   inse2c_db:latest            "docker-entrypoint.s…"   7 seconds ago   Up 6 seconds   0.0.0.0:5432->5432/tcp    inse2c_db
8d294b70fbec   inse2c_server:latest        "./wait-for-postgres…"   7 seconds ago   Up 6 seconds   0.0.0.0:5000->5000/tcp    inse2c_server
013c82fb597a   testcontainers/ryuk:0.3.0   "/app"                   8 seconds ago   Up 8 seconds   0.0.0.0:36605->8080/tcp   testcontainers-ryuk-55bd401f23618dc4e706db3327dc3c1e
```

I've been stuck with this for a few days now, I have tried using variations of the image name inc/exc tags. I even implemented my own sleep function to wait 30s and make sure the container is definitely running but I received the same output. 

If I remove the line with `getContainer()` (and the other lines that try to use the resulting container) the hooks will proceed as expected and shut down my images when done.

**Comment by cristianrgreco** [comment]
Hi @TingeOGinge, could you please share the logs of the `inse2c_server` container? I suspect that it is never logging `Server started on port 5000`

**Comment by TingeOGinge** [comment]
Of course: 

```
> Executing task: docker logs --tail 1000 -f a5bcb6689de60560287f78e93c16de09ae98cacea88d8a4b287f02f1dc33d212 <

Connecting to 192.168.0.11 Failed

> server@1.0.0 start
> nodemon server.js

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
Server started on port 5000
```

The "Connecting to 192.168.0.11 Failed" is the result of an existing bash script I used to pause the starting of the server until the postgres database is up and ready.

**Comment by cristianrgreco** [comment]
Thanks @TingeOGinge, would you mind running `docker inspect inse2c_server` while it's running and share the output of `Config.Labels`?

**Comment by TingeOGinge** [comment]
`Config.Labels` output: 
```
"Labels": {
                "com.docker.compose.config-hash": "b057f45a6a124d7e6b0ee82fc5559004ceb8c5b24686d324a2305f4c75cd3c54",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "testcontainersa1f8d68f9d272ffd3ce2787eec99e68d",
                "com.docker.compose.service": "server",
                "com.docker.compose.version": "1.17.1"
            }
```

**Comment by cristianrgreco** [comment]
Hmm, could you upgrade to 7.4.0, and re-run the test with the env variable DEBUG=testcontainers* and share the output here? Could you also share your node/docker version? At the moment I don't see why you wouldn't be able to get the container

**Comment by TingeOGinge** [comment]
Ah you cracked it! It was the docker-compose version that seemed to be holding me back, I've since upgraded to the latest version (`1.17.1 => 1.28.2`) using the instructions directly from Docker, as previously I had installed it through `apt`.

I can now get the container using `this.environment.getContainer("inse2c_server")` and it seems my tests work using localhost and don't need to get the container IP address / mapped port etc. Thank you very much for taking the time to help me with this

**Comment by cristianrgreco** [comment]
Great news! I will think about how testcontainers can better surface this issue, perhaps we could log a warning if the versions of docker/docker-compose are below a certain version. Thanks for raising the issue and for the great level of detail!
