### ISSUE TITLE
TypeError: container.exec is not a function

### ISSUE THREAD

**Issue by zonk911** [testcontainers/testcontainers-node#19]
Hi Folks, 

i tried the example, "Running commands inside running container", from the README.md and i tumbled over the following issue.

`TypeError: container.exec is not a function
    at somefile.js:17:54
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)`

It is not part of the TestContainer interface so the GenericContainer is obviously not able to do this. Please adjust the README cause i'm now really sad cause i can not work around the getContainerIpAddress issue ;)

Cheers
Christian

**Comment by cristianrgreco** [comment]
Hi @zonk911 

It's part of the `StartedTestContainer` interface - did you `.start()` the `GenericContainer`?
If yes, could you provide an example code?

**Comment by zonk911** [comment]
I used the code from your README.md

`const { GenericContainer } = require("testcontainers");

(async () => {
  const container = await new GenericContainer("mysql")
      .withEnv("MYSQL_ALLOW_EMPTY_PASSWORD", "true")
      .start();

  const { output, exitCode } = await container.exec(["mysql", "--execute", "show databases"]);

  console.log(exitCode, output);

  await container.stop();
})();`

**Comment by cristianrgreco** [comment]
Works for me. What version of node/testcontainers are you using?

**Comment by zonk911** [comment]
I use ```"testcontainers": "^1.1.19",```. I will check if i can find a newer one.

**Comment by cristianrgreco** [comment]
The functionality was added in `1.2.0`.

**Comment by zonk911** [comment]
I didn't expected a new version. I just installed the module at the end of last week and assumed that i have the latest one. I will try it out, sry for interrupting. ;)

Thx and Cheers
