### ISSUE TITLE
Able to wait for container port

### ISSUE THREAD

**Issue by sazzer** [testcontainers/testcontainers-node#190]
I might be missing something obvious, but I can't see how to make testcontainers-node wait for the container to be listening on a given port.

There is a `HostPortWaitStrategy` class, but to construct it I need access to values that I don't have - specifically `DockerClient`.

On the `Wait` class there is only the ability to wait for log messages or healthchecks - the first of which isn't hugely reliable and the second needs the container to actually have a healthcheck.

# Example
```
    const container = new GenericContainer('postgres:12.4-alpine')
      .withExposedPorts(5432)
      .withEnv('POSTGRES_DB', 'db')
      .withEnv('POSTGRES_USER', 'user')
      .withEnv('POSTGRES_PASSWORD', 'pass')
      .withWaitStrategy(Wait.forLogMessage(/listening on IPv4 address/));
    const started = await container.start();
    await new Promise((resolve) => setTimeout(resolve, 500)); // Without this line, the test continues before the container is running
```

# Desirable
```
    const container = new GenericContainer('postgres:12.4-alpine')
      .withExposedPorts(5432)
      .withEnv('POSTGRES_DB', 'db')
      .withEnv('POSTGRES_USER', 'user')
      .withEnv('POSTGRES_PASSWORD', 'pass')
      .withWaitStrategy(Wait.forLogMessage(5432)); // This is new
    const started = await container.start();
```

**Comment by cristianrgreco** [comment]
Hi @sazzer, the default wait strategy is the host port wait strategy. So for example if you create a container with exposed port 8080, then testcontainers will by default wait for that port to be bound. Does that help answer your question? It says so here but I will make it clearer https://github.com/testcontainers/testcontainers-node#wait-strategies
