### ISSUE TITLE
 Connection refused to Ryuk in Docker engine 20.10.5

### ISSUE THREAD

**Issue by ab316** [testcontainers/testcontainers-node#193]
After updating the Docker desktop for Windows, the testcontainers fails to connect to the Ryuk container:

```
  1) "before all" hook in "{root}":
     Uncaught Error: connect ECONNREFUSED 127.0.0.1:46403
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
```

```
docker ps
CONTAINER ID   IMAGE                       COMMAND   CREATED          STATUS          PORTS                     NAMES
f14e21a05bfd   testcontainers/ryuk:0.3.0   "/app"    14 seconds ago   Up 13 seconds   0.0.0.0:46403->8080/tcp   testcontainers-ryuk-33d88285030f5f173ab9c77a94b261d1

docker logs -f f1
2021/03/09 09:26:18 Pinging Docker...
2021/03/09 09:26:18 Docker daemon is available!
2021/03/09 09:26:18 Starting on port 8080...
2021/03/09 09:26:18 Started!
```
NodeJs: 12
testcontainers version: 7.4.1
Docker Desktop version: 3.2.1 (61626)
Docker Engine: 20.10.5

**Comment by ab316** [comment]
This could be some wrong with the new Docker version, not sure.

**Comment by cristianrgreco** [comment]
Hi @ab316, thanks for raising, what version were you on previously and was that working?

**Comment by cristianrgreco** [comment]
Thanks for the info @ab316, the original issue was about docker engine 20.10.5, but it seems it's from testcontainers > 6.3.0 on docker engine 20.10.x ?

**Comment by ab316** [comment]
I have veried now. testcontainers 6.3.0 also doesn't work with Docker engine 20.10.5.
I get
```
     Uncaught Error: connect ECONNREFUSED 127.0.0.1:41135
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
```

That is connection refused to the Ryuk container.

**Comment by cristianrgreco** [comment]
@ab316 You mentioned this previously worked, what versions of testcontainers and docker-engine were you using that worked?

**Comment by ab316** [comment]
@cristianrgreco  testcontainers 6.3.0 and docker engine 20.10.2.

**Comment by cristianrgreco** [comment]
I’ve just tested the latest testcontainers on Windows against 19.03.8 and it works. Will update Docker and report back

**Comment by cristianrgreco** [comment]
@ab316 I’ve just run the entire test suite against docker 20.10.2 on windows and it works. Could you please share some reproducible example or somehow show that the issue is with testcontainers? Have you checked you have enough free space for docker to run?

**Comment by ab316** [comment]
Have you tried on Docker 20.10.5? because it's there where testcontainers completely break. Even 6.3.0 fails on it. The testscontainers testsuite is also failing. I have enough space for Docker to run. It could be an issue with Docker though. I can not easily provide an example for testcontainers 7.4.1 failing on Docker 20.10.2

**Comment by cristianrgreco** [comment]
@ab316 I’ve just upgraded to 20.10.5 and the test suite passes.

> The testscontainers testsuite is also failing

Can you share any logs? Without any logs/repro I will have to assume this is an issue on your side

**Comment by cristianrgreco** [comment]
Hi @ab316, please re-open this issue when you have a reproducible example

**Comment by SBD580** [comment]
same issue here, after upgrading yesterday nothing works (testcontainers v7.x and docker windows 20.10.5)

**Comment by cristianrgreco** [comment]
> testcontainers completely break
> also doesn't work with Docker engine 20.10.5
> after upgrading yesterday nothing works

Please provide a reproducible example and logs. I have also tested the latest testcontainers on the same version of Docker engine without issue.

**Comment by ab316** [comment]
Okay, a bit occupied right now so can't provide at the moment.
