### ISSUE TITLE
Provide ipc mode host

### ISSUE THREAD

**Issue by everflux** [testcontainers/testcontainers-node#195]
In order to run cypress in a testcontainer the following setting is required:
_If you are running long runs on Docker, you need to set the ipc to host mode._  as discussed in this issue https://github.com/cypress-io/cypress/issues/350 and documented on https://docs.cypress.io/guides/continuous-integration/introduction.html#Missing-binary
Currently there seems to be no way to configure it using testcontainers-node.

**Comment by cristianrgreco** [comment]
Hi @everflux, does the referenced PR work for you?

**Comment by everflux** [comment]
That was lightning fast! Change makes sense and looks good to me, is there an easy way to test it, or should I just wait for the next release?

**Comment by cristianrgreco** [comment]
I've never actually looked at the beta releases, I should at some point.. I will release for now because it's a new feature

**Comment by everflux** [comment]
Very cool, thanks!

**Comment by cristianrgreco** [comment]
Released in [7.6.0](https://github.com/testcontainers/testcontainers-node/releases/tag/v7.6.0)
