### ISSUE TITLE
Docker volume support for testcontainers 

### ISSUE THREAD

**Issue by da-kami** [testcontainers/testcontainers-node#20]
Similar to Java testcontainers it would be great to be able to mount files/volumes. (i.e. https://www.testcontainers.org/features/files/)

Thanks 😃

**Comment by cristianrgreco** [comment]
Hi @da-kami

Could you check out the PR and let me know if that works for you?

**Comment by cristianrgreco** [comment]
This functionality is available in v2.0.0.
