### ISSUE TITLE
Auth config for default registry not respected

### ISSUE THREAD

**Issue by crickford** [testcontainers/testcontainers-node#200]
If an image name does _not_ include a private registry, docker will attempt to pull from dockerhub. Credentials set for authenticated pulls from dockerhub are not respected by testcontainers-node, due to the image names not including a private registry.

Quick PR which fixes this behavior: #199

**Comment by cristianrgreco** [comment]
Released in https://github.com/testcontainers/testcontainers-node/releases/tag/v7.7.0. 
Thanks again @crickford !
