### ISSUE TITLE
Question regarding passing arguments

### ISSUE THREAD

**Issue by fondberg** [testcontainers/testcontainers-node#202]
Thanks for a great project!
I have a question regarding passing arguments.
I today start (in my case postgres) with `docker run .... -c fsync=off`. 
How would I translate this into APi calls?

**Comment by cristianrgreco** [comment]
Hi @fondberg, thanks! 🙂 Should be something like:

```javascript
new GenericContainer("postgres").withCmd(["....", "-c", "fsync=off"])
```

**Comment by fondberg** [comment]
Great thanks!
