### ISSUE TITLE
How to define hostname for container?

### ISSUE THREAD

**Issue by fondberg** [testcontainers/testcontainers-node#212]
Thanks for excellent work!
I'm trying to have one testcontainer connect to another testcontainer on a docker network (setup using `const network = await new Network().start();` and would like to use something like

```js
  const container = await new GenericContainer('postgres')
    .withEnv('POSTGRES_USER', 'testuser')
    .withEnv('POSTGRES_PASSWORD', 'test')
    .withEnv('POSTGRES_DB', 'apidb')
    .withExposedPorts(5432)
    .withHostName('postgrestest.mytest.local') // <- defined like this
    .withNetworkMode(network.getName()). // <-  using this network 
    .start();  
```

What are the recommendations here?

**Comment by cristianrgreco** [comment]
Hi @fondberg, thanks 🙂 Looking at the Java examples there's this:

```java
GenericContainer<?> foo = new GenericContainer<>(TestImages.TINY_IMAGE)
    .withNetwork(network)
    .withNetworkAliases("foo")
```

Which would allow another container on the same network to access this container like `http://foo`. Is this the kind of behaviour you are asking about? If so it's not currently implemented, but would be happy to add it

**Comment by fondberg** [comment]
That is exactly what I'm looking for. Great that you want to add it! Can I help somehow?

**Comment by cristianrgreco** [comment]
@fondberg Thanks for offering to help, I've raised a PR which implements this behaviour, I'll have it released as soon as the build passes/tasks are complete. Will update here once that's done

**Comment by fondberg** [comment]
Great!
