### ISSUE TITLE
Port not bound after 60000ms

### ISSUE THREAD

**Issue by kpeters-cbsi** [testcontainers/testcontainers-node#214]
The following code produces the error: `Error: Port 3000 not bound after 60000ms`

```
import { GenericContainer, Network, StartedTestContainer } from 'testcontainers'
import * as path from 'path'
import got from 'got'

const httpPort = 3000
const buildContext = path.resolve(__dirname, 'testWebsite')

const main = async () => {
  const getContainer = async () => {
    const c = await GenericContainer.fromDockerfile(buildContext)
      .withBuildArg('PORT', httpPort.toString())
      .build()
    return await c
      .withExposedPorts(httpPort)
      .start()
  }

  const container = await getContainer()
  console.log('Got container')
  container.stop()
}

(async () => await main())()
```

Dockerfile:
```
FROM abhin4v/hastatic

COPY html /opt/web
WORKDIR /opt/web
CMD ["/usr/bin/hastatic"]
```

**Comment by cristianrgreco** [comment]
Hi @kpeters-cbsi, are you sure your container exposes port 3000? Also you are providing a PORT build arg but the Dockerfile in the example doesn't have any build args.

**Comment by kpeters-cbsi** [comment]
As shown below, I updated the Dockerfile to expose port 3000; no change.

Dockerfile:
```
FROM abhin4v/hastatic

WORKDIR /opt/web
EXPOSE 3000
CMD ["/usr/bin/hastatic"]
```

**Comment by cristianrgreco** [comment]
@kpeters-cbsi I cannot even run that image via the CLI `docker run abhin4v/hastatic`:

```
docker: Error response from daemon: No command specified.
See 'docker run --help'.
```

This issue implies that the default wait strategy does not work, which is not the case as per the build. I will close this issue until you can show that this is an issue with testcontainers, providing logs would be a good start.

**Comment by kpeters-cbsi** [comment]
OK, that's on me. The Docker image I was using works fine from the CLI, but not with testcontainers.
