### ISSUE TITLE
docker-compose localstack container failing to start

### ISSUE THREAD

**Issue by tim-oe** [testcontainers/testcontainers-node#218]
using docker compose to start container times out with the following error:
Port 4571 not bound after 60000ms for cc2f2b8b37d2f1acfb3c8255e8d2976dd98f98eaefe6394ed5c36c308fcd3e6f
this port isn't exposed in my compose file, see attached.

if the container is already present i get the following error:
    ERROR: for localstack  Cannot create container for service localstack: Conflict. The container name "/localstack" is already in use by container "f572324877126aab54dfb6b071e9b8e8ab677f37393f3eefea46765c178e09b4". You have to remove (or rename) that container to be able to reuse that name.

  "testcontainers": "^7.11.1"

`export function containerEnv(): DockerComposeEnvironment {
  try {
    if (!localstackEnv) {
      const composeFilePath = path.resolve(__dirname, "..");
      const composeFile = "docker-compose.yml";

      localstackEnv = new DockerComposeEnvironment(
        composeFilePath,
        composeFile
      ).withWaitStrategy(
        "localstack_1",
        Wait.forLogMessage("Checking if there are idle containers ...")
      );
    }
  } catch (err) {
    console.error("failed to lanuch localstack\n" + JSON.stringify(err), err);
  }

  return localstackEnv;
}

// in test code
   localstack = await containerEnv().up();
`
docker compose file
[docker-compose.yml](https://github.com/testcontainers/testcontainers-node/files/6587170/docker-compose.txt)

**Comment by cristianrgreco** [comment]
Hi @tim-oe, when I run the attached docker-compose.yml, I see there is a container named `localstack` (the name is set in the docker-compose.yml) file, but the code defines a wait strategy for a container called `localstack_1`, which doesn't exist:

```javascript
.withWaitStrategy(
  "localstack_1",
  Wait.forLogMessage("Checking if there are idle containers ...")
);
```

Could you confirm that changing `localstack_1` to `localstack` solves the issue? If it does then I will see how this can be made clearer, for example setting a wait strategy for a container that doesn't exist could emit a warning.

**Comment by tim-oe** [comment]
good find, sorry about that. that fixes the clean run with increasing the jest timeout.

it still fails if I have run docker-compose externally from the tests.

**Comment by cristianrgreco** [comment]
> good find, sorry about that. that fixes the clean run with increasing the jest timeout.

No worries, good news!

> It still fails if I have run docker-compose externally from the tests.

Because the container has a name, and container names are unique, you cannot start another container with the same name, hence the conflict. What is the behaviour you expect?

**Comment by tim-oe** [comment]
I want to leverage the compose file for both dev/debugging and for testing, looking at the ctor is there a way to override the name in the jest test? kinda new to all the docker stuff.

`constructor(composeFilePath: string, composeFiles: string | string[], uuid?: Uuid);`

**Comment by tim-oe** [comment]
i removed the container name from to docker compose but how do you know the name to pass for the wait? also once removed with having the tests call down/stop only one test will run. others fail with name conflict or port in use errors

it seems compose can only be used via globalsetup

**Comment by cristianrgreco** [comment]
> how do you know the name to pass for the wait

It is based on the image name, for example if the image is `localstack` then it will create `localstack_1`, if there is more than one localstack image then it would be `localstack_2`, etc.

> fail with name conflict or port in use errors

The name conflict would be resolved by removing the name from the yaml file as you previously suggest. The port conflict would be resolved by removing the explicit binding, for example from

```
ports:
  - "4566:4566"
```

To 
```
ports:
  - "4566"
```

You can then get the mapped port with testcontainers as per the README, for example:

```javascript
const environment = await new DockerComposeEnvironment(composeFilePath, composeFile).up();

const localstackContainer = environment.getContainer("localstack_1");
const port = localstackContainer.getMappedPort(4566);
```

In general, let Docker generate container names and allocate ports for you, to eliminate the situation of a conflict occurring, that way you can parallelise your tests. Use testcontainers to get any necessary mapped ports.
