### ISSUE TITLE
Property 'logs' does not exist on type 'GenericContainer'

### ISSUE THREAD

**Issue by fondberg** [testcontainers/testcontainers-node#219]
It seems the logs method as described in the docs is not in the latest (^7.11.1) release for GenericContainer.
Is there another way of getting logs from the container?

This is my code:
```js
    const nodeContainer = await GenericContainer.fromDockerfile(
      buildContext,
    ).build();

    const apiContainer = await nodeContainer
      .withNetworkMode(network.getName())
      .withNetworkAliases(ApiNetworkName)
      .withExposedPorts(4000)
      .withEnv(
        'DATABASE_URL',
        `postgresql://testuser:test@${dbIpAddress}:5432/db`,
      )
      .withEnv('NODE_ENV', 'test')
      .withWaitStrategy(
        Wait.forLogMessage('Server is running on http://localhost:4000'),
      )
      .start();
```

**Comment by cristianrgreco** [comment]
Hi @fondberg, I'm not sure what you mean, as per this test you should be able to get logs out of the container: https://github.com/testcontainers/testcontainers-node/blob/master/src/generic-container.test.ts#L273-L280

**Comment by fondberg** [comment]
I think I made some mistake because not it works. Sorry to bother and keep up the good work!
