### ISSUE TITLE
Kafka module is not working with Schema Registry

### ISSUE THREAD

**Issue by katerina-semikina** [testcontainers/testcontainers-node#263]
Hey!

I've created PR https://github.com/testcontainers/testcontainers-node/pull/262. 
The changes are needed to make Kafka module work with Schema Registry https://github.com/confluentinc/schema-registry.
Also this is a kind of clean up for env variables defined in this Kafka Container.

It would be great if these changes could be merged. Thanks!

**Comment by cristianrgreco** [comment]
Thanks again @katerina-semikina! Released in [7.20.0](https://github.com/testcontainers/testcontainers-node/releases/tag/v7.20.0).
