### ISSUE TITLE
All exposed ports are subject to HostPortCheck, even if not bound to host

### ISSUE THREAD

**Issue by atkinchris** [testcontainers/testcontainers-node#265]
When setting up a Docker Compose environment, the exposed ports are read from the Docker container inspect data. These are all put into a map of "bound" ports. However, these ports may not actually be mapped be mapped to a host port, as there's no requirement for them to be. As such, `PublicPort` would be undefined, and the `socket.connect` would fail during the Host check.

I suspect that `containerInfo.Ports` should be filtered for only bindings that have both `PrivatePort` and `PublicPort`.

https://github.com/testcontainers/testcontainers-node/blob/341b230d578006e0c27d621004b78a77d545bf7e/src/docker-compose-environment/docker-compose-environment.ts#L122

**Comment by cristianrgreco** [comment]
Thanks for raising @atkinchris, fixed in [7.20.1](https://github.com/testcontainers/testcontainers-node/releases/tag/v7.20.1).

**Comment by atkinchris** [comment]
Awesome, thanks!
