### ISSUE TITLE
Errors on Docker Compose startup are incorrectly coerced to strings

### ISSUE THREAD

**Issue by atkinchris** [testcontainers/testcontainers-node#268]
Error objects thrown by the `docker-compose` library in `upMany/upAll` are neither `Error` objects nor strings. However, they are handled as either, which means that meaningful error objects are coerced into `[object Object]`.

https://github.com/testcontainers/testcontainers-node/blob/7c19f5e412954bb8a24e6e261fefcf6417a8459f/src/docker-compose/functions/docker-compose-up.ts#L18-L26

For example, if there's an error while building a container, an error object like the following will be logged.

```js
{
  exitCode: 1,
  err: 'Creating network "testcontainers-62676b556ffd0da781f7ebdc9282f8cb_default" with the default driver\n' +
    'Building REDACTED\n' +
    '#1 [internal] load build definition from Dockerfile\n' +
    '#1 sha256:19e974790edee939df57c9009d16d3f6452c6417fcbe20262b384de0e1eaad3e\n' +
    '#1 transferring dockerfile: 44B done\n' +
    '#1 DONE 0.0s\n' +
    '\n' +
    '#2 [internal] load .dockerignore\n' +
    '#2 sha256:3961014c6de9d919d4066a7ad6f61bd8b61448bb60f673724e01e5b5793d3292\n' +
    '#2 transferring context: 34B done\n' +
    '#2 DONE 0.0s\n' +
    '\n' +
    "Service 'REDACTED' failed to build : Build failed\n",
  out: ''
}
```

I suspect that a message should be parsed from the error object, for example:

```js
const errorMessage = err.err || err.message || err;
log.error(`Failed to up DockerCompose environment: ${errorMessage}`);

try {
  await dockerComposeDown(options);
} catch {
  log.warn(`Failed to down DockerCompose environment after failed up`);
}

throw new Error(errorMessage);
```

**Comment by cristianrgreco** [comment]
Thanks again @atkinchris, keep 'em coming! Fixed in [7.20.2](https://github.com/testcontainers/testcontainers-node/releases/tag/v7.20.2).
