### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by batuhancaglayan** [testcontainers/testcontainers-node#281]
Hello,

I take an error while i try to install package. I is not failing npm install process and everything works fine. 
The error is as below;

![exception_on_npm_install](https://user-images.githubusercontent.com/24773791/134771438-d15813f2-e0e7-4ac4-9b8c-81ae82e87ca4.PNG)

thanks for your helps.

**Comment by cristianrgreco** [comment]
Hi, did you read the error message? `cmake: not found` ..
