### ISSUE TITLE
Testcontainers don't work with docker-credential-gcloud on Win

### ISSUE THREAD

**Issue by michalosik88** [testcontainers/testcontainers-node#293]
When I try to run testcontainers using the GCP PubSub emulator, I got a message:
```
> Uncaught Error: spawn docker-credential-gcloud ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_errnoException (node:internal/errors:594:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

The problem doesn't occur on Linux.
Node version: 16.3.0 (here I got a timeout on spawning the containers) or 12.22.7 (here the problem occurs openly).
When I try to run the docker-credential-gcloud using node console:
```
const {spawn} = require('child_process');
spawn('docker-credential-gcloud', ['get']);
```
I got the same error message. However when I do:
```
const {spawn} = require('child_process');
spawn('docker-credential-gcloud', ['get'], {shell: true});
```
Everything looks fine (although I don't have access to the other shell from my test context of course).

**Comment by cristianrgreco** [comment]
Hi @michalosik88, that's interesting, I found this in the docs which would explain why setting `shell: true` fixes it for Windows:

https://nodejs.org/api/child_process.html#spawning-bat-and-cmd-files-on-windows

> The importance of the distinction between child_process.exec() and child_process.execFile() can vary based on platform. 
> 
> On Unix-type operating systems (Unix, Linux, macOS) child_process.execFile() can be more efficient because it **does not spawn a shell by default**. 
> 
> On Windows, however, .bat and .cmd files are not executable on their own without a terminal, and therefore cannot be launched using child_process.execFile(). **When running on Windows, .bat and .cmd files can be invoked using child_process.spawn() with the shell option set**...

I'd welcome a PR which sets `shell` depending on the OS. If not I'll get to it soon

**Comment by michalosik88** [comment]
Thank you @cristianrgreco , that would explain a lot. I am not sure however if adding `shell` would fix the whole problem, cause AFAIK it runs a new shell to run the command. So running a test container in another shell than the rest of the test suite may mean that it won't be seen by other containers, or am I wrong?

**Comment by cristianrgreco** [comment]
The process that gets the credentials runs before any container is started, and is killed as soon as we get them, so I think it should be fine

**Comment by cristianrgreco** [comment]
@michalosik88 could you please try version `7.22.1-beta.0` and let me know if it works for you?

**Comment by michalosik88** [comment]
Hi @cristianrgreco just tried that and unfortunately nothing changed. Maybe full DEBUG log may help you in some way.
```
  testcontainers DEBUG Creating new Docker instance +0ms
  testcontainers INFO  Using default Docker host: localhost +377ms
  testcontainers DEBUG Creating new Reaper for session: 42d474fd57148595d161dd66c5f56c1f +4ms
  testcontainers DEBUG Executing Docker credential provider: docker-credential-desktop +10ms
  testcontainers DEBUG Docker credential provider exited with code: 0 +3s
  testcontainers DEBUG Docker credential provider found auth config for [docker repo]: {"username":"[user]","password":"*******","registryAddress":"[docker repo]"} +1ms
  testcontainers DEBUG Found applicable registry auth locator for registry "[docker repo]": CredsStore +1ms
  testcontainers DEBUG Not pulling image as it already exists: testcontainers/ryuk:0.3.2 +18ms
  testcontainers INFO  Creating container for image: testcontainers/ryuk:0.3.2 +12ms
  testcontainers INFO  Starting container testcontainers/ryuk:0.3.2 with ID: [container id] +139ms
  testcontainers DEBUG Waiting for container to be ready: [container id] +1s
  testcontainers DEBUG Waiting for host port 36823 for [container id] +2ms
  testcontainers DEBUG Waiting for internal port 8080 for [container id] +3ms
  testcontainers DEBUG Host port 36823 ready for [container id] +17ms
  testcontainers DEBUG System diagnostics: {
  testcontainers   "node": {
  testcontainers     "version": "v12.22.7",
  testcontainers     "architecture": "x64",
  testcontainers     "platform": "win32"
  testcontainers   },
  testcontainers   "docker": {
  testcontainers     "serverVersion": "20.10.8",
  testcontainers     "operatingSystem": "Docker Desktop",
  testcontainers     "operatingSystemType": "linux",
  testcontainers     "architecture": "x86_64",
  testcontainers     "cpus": 8,
  testcontainers     "memory": 26758074368
  testcontainers   },
  testcontainers   "dockerCompose": {
  testcontainers     "version": "1.29.2\r"
  testcontainers   }
  testcontainers } +2s
  testcontainers DEBUG Internal port 8080 ready for [container id] +2s
  testcontainers INFO  Container is ready +1ms
  testcontainers DEBUG Connecting to Reaper [container id] on localhost:36823 +4ms
  testcontainers DEBUG Connected to Reaper [container id] +9ms
  testcontainers DEBUG Preparing to build Dockerfile: [my dockerfile] +2ms
  testcontainers DEBUG Executing Docker credential provider: docker-credential-gcloud +7ms

 RUNS  [test.ts]
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn docker-credential-gcloud ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn docker-credential-gcloud',
  path: 'docker-credential-gcloud',
  spawnargs: [ 'get' ]
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by cristianrgreco** [comment]
Hi @michalosik88, thanks for sharing that. I don't understand, you mentioned adding `{ shell: true }` to the `spawn` fixed it for you, which is the same as I've done: https://github.com/testcontainers/testcontainers-node/blob/293/src/registry-auth-locator/credential-provider.ts#L58

I'm not able to reproduce the issue myself so need your help, could you please let me know what's different between your fix and mine?

**Comment by cristianrgreco** [comment]
@michalosik88 would you be able to look at this?

**Comment by michalosik88** [comment]
Hi @cristianrgreco, yes, but I haven't found the cause of the issue. The difference between your fix and mine is just a way how we do it. I just do it in the CMD console, using node command and making spawn there, you do it in testcontainers source code. The result should be the same of course, but for some reason it still throws that error.

I will have to take a further look when I will find some time.

**Comment by cristianrgreco** [comment]
Haven't heard anything else regarding this so will close the issue and associated PR.
