### ISSUE TITLE
Testcontainer build using Dockerfile hangs on WSL 2 based engine if the Dockerfile directory contains .dockerignore

### ISSUE THREAD

**Issue by armen-ch** [testcontainers/testcontainers-node#301]
The command used:
const buildContext = <mypath>
const container = await GenericContainer.fromDockerfile(buildContext).build();

It hangs and never finishes. 
Tested on Windows 10:
- Docker Desktop v4.0.1(Engine: 20.10.8) with WSL2/Hyper-V engine enabled 
- WSL 2 distro Ubuntu
Passes if running on pure Linux VM (tested on RHEL)

**Comment by cristianrgreco** [comment]
Hi @armen-ch, could you please share the log output (run with `DEBUG=testcontainers*` env variable)?

**Comment by armen-ch** [comment]
Hi @cristianrgreco,

Here you go:

  Pact: Securities Provider Interface expected by Watchlist Provider verification
  testcontainers DEBUG Creating new Docker instance +0ms
Building microservice docker container...
  testcontainers DEBUG Creating new Reaper for session: 058a390c608c2c3e5b65ba092df0e9c7 +43ms
  testcontainers INFO  Docker host strategy OUTSIDE_CONTAINER: localhost +4ms
  testcontainers DEBUG Executing Docker credential provider: docker-credential-desktop.exe +4ms
  testcontainers DEBUG System diagnostics: {
  testcontainers   "node": {
  testcontainers     "version": "v14.18.0",
  testcontainers     "architecture": "x64",
  testcontainers     "platform": "linux"
  testcontainers   },
  testcontainers   "docker": {
  testcontainers     "serverVersion": "20.10.8",
  testcontainers     "operatingSystem": "Docker Desktop",
  testcontainers     "operatingSystemType": "linux",
  testcontainers     "architecture": "x86_64",
  testcontainers     "cpus": 8,
  testcontainers     "memory": 13195796480
  testcontainers   },
  testcontainers   "dockerCompose": {
  testcontainers     "version": "1.29.2"
  testcontainers   }
  testcontainers } +1s
  testcontainers DEBUG Docker credential provider exited with code: 0 +2s
  testcontainers DEBUG Docker credential provider found auth config for https://index.docker.io/v1/ +0ms
  testcontainers DEBUG Found applicable registry auth locator for registry "https://index.docker.io/v1/": CredsStore +0ms
  testcontainers DEBUG Not pulling image as it already exists: testcontainers/ryuk:0.3.2 +8ms
  testcontainers INFO  Creating container for image: testcontainers/ryuk:0.3.2 +4ms
  testcontainers INFO  Starting container testcontainers/ryuk:0.3.2 with ID: 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a +830ms
  testcontainers:containers TRACE 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a: 2021/11/18 10:42:05 Pinging Docker... +0ms
  testcontainers:containers TRACE 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a: 2021/11/18 10:42:05 Docker daemon is available! +0ms
  testcontainers:containers TRACE 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a: 2021/11/18 10:42:05 Starting on port 8080... +0ms
  testcontainers:containers TRACE 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a: 2021/11/18 10:42:05 Started! +0ms
  testcontainers DEBUG Waiting for container to be ready: 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a +940ms
  testcontainers DEBUG Waiting for host port 21790 for 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a +1ms
  testcontainers DEBUG Waiting for internal port 8080 for 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a +2ms
  testcontainers DEBUG Host port 21790 ready for 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a +12ms
  testcontainers:containers TRACE 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a: 2021/11/18 10:42:05 New client connected: 172.17.0.1:49044 +31ms
  testcontainers:containers TRACE 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a: 2021/11/18 10:42:05 Received the first connection +0ms
  testcontainers:containers TRACE 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a: 2021/11/18 10:42:05 EOF +1ms
  testcontainers:containers TRACE 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a: 2021/11/18 10:42:05 Client disconnected: 172.17.0.1:49044 +0ms
  testcontainers:containers TRACE 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a: 2021/11/18 10:42:06 New client connected: 127.0.0.1:34037 +1s
  testcontainers:containers TRACE 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a: 2021/11/18 10:42:06 EOF +0ms
  testcontainers:containers TRACE 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a: 2021/11/18 10:42:06 Client disconnected: 127.0.0.1:34037 +0ms
  testcontainers DEBUG Internal port 8080 ready for 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a +1s
  testcontainers INFO  Container is ready +0ms
  testcontainers DEBUG Connecting to Reaper 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a on localhost:21790 +1ms
  testcontainers DEBUG Connected to Reaper 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a +1ms
  testcontainers DEBUG Preparing to build Dockerfile: /home/achuljyan/workspace/testcontainers-node/fixtures/docker/docker/Dockerfile +0ms
  testcontainers DEBUG Re-using cached auth for registry https://index.docker.io/v1/ +2ms
  testcontainers INFO  Building image '5e6c359dcb2c952ae217d248a52bdda4:9f3985f50a60c54f326c1d491abbb6b5' with context '/home/achuljyan/workspace/testcontainers-node/fixtures/docker/docker' +1ms
  testcontainers:containers TRACE 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a: 2021/11/18 10:42:06 New client connected: 172.17.0.1:49050 +152ms
  testcontainers:containers TRACE 239a06dbb36471308418c05dc7dda33f5855d869d7c35f8157776ebef0b6c01a: 2021/11/18 10:42:06 Adding {"label":{"org.testcontainers.session-id=058a390c608c2c3e5b65ba092df0e9c7":true}} +0ms


It stops at this point. Once I remove .dockerignore and rerun the script with command it builds image successfully.

Thanks

**Comment by cristianrgreco** [comment]
Thanks @armen-ch, and could you please also share the `.dockerignore` file contents? I don't have access to a Windows machine too often so just want to get as much info as I can :slightly_smiling_face:

**Comment by armen-ch** [comment]
Hi @cristianrgreco,

It looks like you got right to the point :).

```
node_modules
npm-debug.log
Dockerfile
*.md
cfg
```
"Dockerfile" is the reason. If I delete it, the build passes through. Hopefully the fix will be pretty easy.

Thank you!

**Comment by cristianrgreco** [comment]
@armen-ch Fixed in [7.23.2](https://github.com/testcontainers/testcontainers-node/releases/tag/v7.23.2), thanks for raising!

**Comment by SBD580** [comment]
Hi,

@cristianrgreco I believe the fix is not bulletproof - you can't expect the Dockerfile name to appear there "as is" - it might be `*.Dockerfile` or completely missing if ignoring everything except for specific files:
```
*
!src
```

I think it's better to add the Dockerfile explicitly to the tar after adding the context. wdyt?

**Comment by SBD580** [comment]
I actually see we are not supporting the full syntax of `.dockerignore` like negative (`!`) matches - this should be mentioned in the docs I believe.

**Comment by cristianrgreco** [comment]
Thanks for raising those 2 points @SBD580, they've both been addressed in [8.6.0](https://github.com/testcontainers/testcontainers-node/releases/tag/v8.6.0)

**Comment by SBD580** [comment]
Awesome! Thank you for taking this and this entire wonderful lib!
