### ISSUE TITLE
Ability to add extra hosts

### ISSUE THREAD

**Issue by suchbalazs** [testcontainers/testcontainers-node#307]
Currently the extrahosts are private. It would be nice if we could change this just like in the Java and Python testcontainers version.

Especially it would be nice so that the linux version would have this `host.docker.internal` working too. Currently I cannot connect from a testcontainer running Java to a testcontainer MySQL database without this when it is run in docker in docker environment.

related: https://docs.docker.com/desktop/windows/networking/
https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal/61001152

What I tired: 
- Using '172.17.0.1' gateway IP
- Using `getHost()`
- Using `.getIpAddress(network.getName())`
- Using localhost
Of course I used these with the `getMappedPort(..)`-s and the gateway ip works perfectly on linux in case I don't run it from inside another docker. I have similar pipelines in Java and Python and those work properly with extra hosts.

**Comment by suchbalazs** [comment]
Some code that may help with understanding:
```
await new GenericContainer('mysql:8.0.21')
    .withNetworkMode(startedTestContainers.network.getName())
    .withEnv('MYSQL_USER', testSettings.MYSQL_USER)
    .withEnv('MYSQL_PASSWORD', testSettings.MYSQL_PASSWORD)
    .withEnv('MYSQL_ROOT_PASSWORD', testSettings.MYSQL_ROOT_PASSWORD)
    .withEnv('MYSQL_DATABASE', testSettings.KEYCLOAK_MYSQL_DATABASE)
    .withExposedPorts(testSettings.DATABASE_EXPOSED_PORT)
    .withTmpFs({'/var/lib/mysql': 'rw'})
    .withWaitStrategy(Wait.forLogMessage('mysqld: ready for connections.'))
    .start()
    .then(container => {
      logger.info('Keycloak MySQL container started...')
      startedTestContainers.containers.keycloakMysqlContainer = container
    })
    .catch(error => {
      logger.error('Failed to start Keycloak MySQL container...')
      logger.error(error)
      shutdown(startedTestContainers)
      process.exit(1)
    })
    
await new GenericContainer(
  'something/keycloak:latest',
)
  .withPullPolicy(new AlwaysPullPolicy())
  .withNetworkMode(startedTestContainers.network.getName())
  .withEnv('DB_DATABASE', testSettings.KEYCLOAK_MYSQL_DATABASE)
  .withEnv(
    'DB_ADDR',
    getContainerHost(startedTestContainers.containers.keycloakMysqlContainer),
  )
  .withEnv('DB_PASSWORD', testSettings.MYSQL_ROOT_PASSWORD)
  .withEnv(
    'DB_PORT',
    startedTestContainers.containers.keycloakMysqlContainer
      .getMappedPort(testSettings.DATABASE_EXPOSED_PORT)
      .toString(),
  )
  .withEnv('DB_USER', 'root')
  .withEnv('DB_VENDOR', 'mysql')
  .withEnv('JDBC_PARAMS', 'allowPublicKeyRetrieval=true&useSSL=false')
  .withExposedPorts(testSettings.KEYCLOAK_EXPOSED_PORT)
  .withWaitStrategy(Wait.forLogMessage('--- Configuration done!'))
  .withStartupTimeout(600000)
  .start()
  .then(container => {
    logger.info('Keycloak container started...')
    startedTestContainers.containers.keycloakContainer = container
  })
  .catch(error => {
    logger.error('Failed to start Keycloak container...')
    logger.error(error)
    shutdown(startedTestContainers)
    process.exit(1)
  })
  
export const getContainerHost = (
  startedTestContainer: StartedTestContainer,
  isConnectionFromHost = false,
) => {
  return platform() == 'linux'
    ? '172.17.0.1'
    : testSettings.DOCKER_DESKTOP_HOST
}
```

**Comment by cristianrgreco** [comment]
Hi @suchbalazs, see the referenced PR, would something like this work for you?

```javascript
const { GenericContainer } = require("testcontainers");

const container = await new GenericContainer("alpine")
  .withExtraHosts([
    { host: "foo", ipAddress: "10.11.12.13" },
    { host: "bar", ipAddress: "11.12.13.14" }
  ])
  .start();

expect((await container.exec(["nslookup", "foo"])).exitCode).toBe(0);
expect((await container.exec(["nslookup", "bar"])).exitCode).toBe(0);
```

**Comment by suchbalazs** [comment]
This was quick 😄. This seems good to me.

**Comment by cristianrgreco** [comment]
Awesome, released in [7.24.0](https://github.com/testcontainers/testcontainers-node/releases/tag/v7.24.0)

**Comment by suchbalazs** [comment]
Hello there.
Sorry for commenting here again, but the example seems to be incorrect.
```
  .withExtraHosts([
    { host: "foo", ipAddress: "10.11.12.13" },
    { host: "bar", ipAddress: "11.12.13.14" }
  ])
```
Should be this instead according to the current implementation (because the spread operator):
```
  .withExtraHosts(
    { host: "foo", ipAddress: "10.11.12.13" },
    { host: "bar", ipAddress: "11.12.13.14" }
  )
  ```
  Also I tried this out today and it seems to not work for me. `nslookup` found nothing from inside or outside of the docker. Any idea why?

**Comment by suchbalazs** [comment]
Probably the issue is on my side then, but the following doesn't work for me:
```
 it("should set extra hosts", async () => { 
   const container =   await new GenericContainer('alpine')
     .withExtraHosts({
        host: 'host.docker.internal',
        ipAddress: 'host-gateway',
     })
    .withCmd(['tail', '-f', '/dev/null'])
    .start()
  
   expect((await container.exec(["nslookup", "host.docker.internal"])).exitCode).toBe(0); 
  
   await container.stop();
 }); 
 ```
Thanks.

**Comment by suchbalazs** [comment]
I did a bit further investigation and it seems like to not work with the `alpine` image and I don't know yet why. It is working as expected with your `cristianrgreco/testcontainer:1.1.12` image.

**Comment by suchbalazs** [comment]
Hey @cristianrgreco, any idea why this wouldn't work with some images? Like `nslookup` doesn't even find it and yet it is in the `etc/hosts`.

**Comment by cristianrgreco** [comment]
Hey @suchbalazs

> I did a bit further investigation and it seems like to not work with the alpine image and I don't know yet why. It is working as expected with your cristianrgreco/testcontainer:1.1.12 image

The testcontainer image used for testing is based on alpine. Perhaps there is some issue with the host/ipAddress values you are providing? Does the `nslookup` work if you run it with Docker from the CLI?

**Comment by suchbalazs** [comment]
`await container.exec(["nslookup", "host.docker.internal"])).exitCode` was `0` with the `cristianrgreco/testcontainer:1.1.12` image and it wasn't with the `alpine` image.
Sadly at the moment I cannot reproduce it as it is a linux specific issue (`host.docker.internal` is already mapped on Docker Desktop so on windows and mac). Tomorrow I can copy some logs. `nslookup` works as expected just does not find the gateway ip based on the `host-gateway` for `host.docker.internal` host.
```
  const alpineContainer = await new GenericContainer('alpine')
  .withExtraHosts({
     host: 'host.docker.internal',
     ipAddress: 'host-gateway',
  })
 .withCmd(['tail', '-f', '/dev/null'])
 .start()

  const alpineResult = await alpineContainer.exec(["nslookup", "host.docker.internal"])
  logger.info(`Failing result exit code: ${alpineResult.exitCode}`)
  logger.info(`Failing result output: ${alpineResult.output}`)

  const testcontainerContainer = await new GenericContainer('cristianrgreco/testcontainer:1.1.12')
  .withExtraHosts({
     host: 'host.docker.internal',
     ipAddress: 'host-gateway',
  })
 .withCmd(['tail', '-f', '/dev/null'])
 .start()

  const okayResult = await testcontainerContainer.exec(["nslookup", "host.docker.internal"])
  logger.info(`Okay result exit code: ${okayResult.exitCode}`)
  logger.info(`Okay result output: ${okayResult.output}`)

  await testcontainerContainer.stop();
  await alpineContainer.stop();
```
