### ISSUE TITLE
Feature: Reuse containers created by testcontainers

### ISSUE THREAD

**Issue by Zomono** [testcontainers/testcontainers-node#319]
The maintainers of testcontainers-java have implemented a functionallity to reuse an already created container. They implemented this by setting a flag on their GenericContainer. This flag indicates that a similar container also created by testcontainers with the reuse flag set can be reused by another test.

The use case is to speed up test runs and reduce resource usage. If you have a lot of test suits, each spawning e.g. a database container, this could be quite expensive in cpu time and in memory. Each test has to create such a container and wait for it to be ready. Having a bunch of database containers at the same time can also hit your memory limit very fast.

Spawning the container globally in the setup and teardown phase of your test library may not be a solution, because then every test suit will spawn the defined containers, even if it is executed as a single test and it does not use any container. I tried this setup but it slows down single test runs to much leading in a poor developer experience.

I hope to see this feature in testcontainers-node as well.
Thanks so far for this libary!

**Comment by cristianrgreco** [comment]
@Zomono completely agree, will look into this when I can, PRs also welcome 👍

**Comment by cristianrgreco** [comment]
@cwkang1998 please feel free to raise issues for the missing features, we will get there eventually 🙂

**Comment by cristianrgreco** [comment]
Released in [8.5.0](https://github.com/testcontainers/testcontainers-node/releases/tag/v8.5.0).
