### ISSUE TITLE
Error with PostgreSqlContainer

### ISSUE THREAD

**Issue by Duarte007** [testcontainers/testcontainers-node#322]
Hello, im trying to use testcontainer in my aplication using postgres and i am recive this error:

```
error: the database system is starting up
```

I've done some research but to no avail...

I also cloned this repository and tried to run `postgresql-container.test` but I get the same error

Can someone help me?

**Comment by cristianrgreco** [comment]
Hi @Duarte007, could you share some repro, are you using a `GenericContainer` or the `PostgreSqlContainer`? ..

**Comment by Duarte007** [comment]
> Hi @Duarte007, could you share some repro, what version of tc-node, are you using a `GenericContainer` or the `PostgreSqlContainer`? ..

Hello @cristianrgreco 
I'm using `PostgreSqlContainer` and `"testcontainers": "^8.2.0"`

Here ir my code 

```
beforeAll(async () => {
        configService = new ConfigService()
        const postegresConfig = configService._config.postgres

        container = await new MySqlContainer('mysql')
            .withName('test_mysql')
            .withExposedPorts(5432)
            .withUsername(postegresConfig.username)
            .withUserPassword(postegresConfig.password)
            .withDatabase(postegresConfig.database)
            .start()

        const pgConfig = {
            host: container.getHost(),
            port: container.getPort(),
            database: container.getDatabase(),
            user: container.getUsername(),
            password: container.getUserPassword(),
        }

        client = new Client(pgConfig)

        await client
            .connect()
            .then(() => console.log('connected'))
            .catch((err) => console.error('connection error', err.stack))

        const moduleRef = await Test.createTestingModule({
            imports: [PurchaseTokenModule],
        }).compile()

        app = moduleRef.createNestApplication()
        await app.init()
    })
```

The error ocurrs in this snippet

```
await client
            .connect()
            .then(() => console.log('connected'))
            .catch((err) => console.error('connection error', err.stack))

```

Always falls in the catch

**Comment by Duarte007** [comment]
@cristianrgreco 

I added a promise that waits for 10 seconds before trying to connect and it connected correctly
But I started getting authentication error

`error: password authentication failed for user "dev"`

And I'm certainly trying to connect with the same username and password that I passed in the parameters for creating the container, because I'm getting it from a configuration file.
