### ISSUE TITLE
Environment Variables With Cypress

### ISSUE THREAD

**Issue by luismqoliveira** [testcontainers/testcontainers-node#330]
Hello @cristianrgreco,

I'm tying to migrate from protractor to cypress and keep using your testcontainers project but I'm struggling with the environment variables because I'm not able to set any of them (I was using DEBUG and RYUK_CONTAINER_IMAGE).

In protractor i was using in my protractor.conf.js file this way:
`const process = require('process');
process.env.DEBUG = 'testcontainers*';
process.env.RYUK_CONTAINER_IMAGE = privateRegistry/testcontainers/ryuk:0.3.1';`

With Cypress I was able to start my containers in '/cypress/plugins/index.js' file but somehow I'm not able to use the DEBUG and RYUK_CONTAINER_IMAGE variables the same way as protractor. Do you have any thoughts on this?

Thank you for your pacience

**Comment by luismqoliveira** [comment]
I have some updates on this. I managed to get to override the RIUK IMAGE but I can't figure out why I can't enable the your testcontainers logs. This is what I'm try to do (my package.json):
` "cypress:run": "cross-env NODE_ENV=dev DEBUG=testcontainers* RYUK_CONTAINER_IMAGE=mycompany.com/testcontainers/ryuk:0.3.1 DEBUG=cypress:server:plugins ./node_modules/.bin/cypress run "`

**Comment by cristianrgreco** [comment]
Hi @luismqoliveira, this seems to be an issue with how cypress reads environment variables, they provide some documentation about it: https://docs.cypress.io/guides/guides/environment-variables
