### ISSUE TITLE
Feature request: HttpWaitStrategy & StartupCheckStrategies

### ISSUE THREAD

**Issue by cwkang1998** [testcontainers/testcontainers-node#341]
Referencing the docs for `testcontainer-java`, I would like to see implementation of HttpWaitStrategy and StartupCheckStategies in `testcontainers-node`.

https://www.testcontainers.org/features/startup_and_waits/

I am willing to contribute myself.

**Comment by cristianrgreco** [comment]
https://github.com/testcontainers/testcontainers-node/releases/tag/v9.1.0
