### ISSUE TITLE
Support for health checks using CMD rather than CMD-SHELL

### ISSUE THREAD

**Issue by richjharris** [testcontainers/testcontainers-node#342]
Currently only `CMD-SHELL` health checks are supported which require a shell on the docker container to run. `distroless` docker images like [mockserver](https://hub.docker.com/r/mockserver/mockserver/) don't have a shell so that mechanism doesn't work, see https://github.com/GoogleContainerTools/distroless/issues/183.

To support docker containers without a shell the health check needs to be in the format
```
test: ['CMD', '/path/to/program', 'arg1', 'arg2', 'arg3']
```

**Comment by richjharris** [comment]
Here is a PR to support `CMD` health checks https://github.com/testcontainers/testcontainers-node/pull/343

**Comment by richjharris** [comment]
@cristianrgreco is there an expected time frame for this to get merged?

**Comment by cristianrgreco** [comment]
@richjharris sorry for the delay, haven't had much time to work on this lately. I'm hoping to get this done in the next couple of weeks

**Comment by cristianrgreco** [comment]
Released in 9.0.0
