### ISSUE TITLE
Kafka containers are not reusable

### ISSUE THREAD

**Issue by apokralipsa** [testcontainers/testcontainers-node#351]
**Expected Behaviour**
Kafka containers should be reusable when the `withReuse` method is called before the container is started.

**Actual Behaviour**
Containers are kept alive after the test is done, but new ones are created each time.
This is because a random zookeeper port is being selected and exposed each time.

**Testcontainer Logs**
None

**Steps to Reproduce**
Run the following test:
```typescript
describe("KafkaContainer", () => {
  jest.setTimeout(240_000);

  it("should be reusable", async () => {
    const originalKafkaContainer = await new KafkaContainer().withReuse().start();
    const newKafkaContainer = await new KafkaContainer().withReuse().start();

    expect(newKafkaContainer.getId()).toBe(originalKafkaContainer.getId());

    await originalKafkaContainer.stop()
  });
})
```

**Environment Information**
- Operating System: macOS 12.2.1
- Docker Version: 20.10.6
- Node version: v17.9.0
- Testcontainers version: 8.7.0

**Comment by cristianrgreco** [comment]
Released in 8.7.1
