### ISSUE TITLE
Feature request: Make setting up SASL and SSL in Kafka containers easier.

### ISSUE THREAD

**Issue by apokralipsa** [testcontainers/testcontainers-node#353]
Production Kafka clusters may require the application to use encryption and to authenticate using the SASL mechanism.
In such a case it might be best to also configure the test container to require it, so that the test and production environments are as similar as possible.

Currently setting it up using the provided module is a bit cumbersome. It requires extending the `KafkaContainer` class so that the listener list set up in the `postStart` method can be changed, setting multiple environment variables and calling commands on the running container to create a user that can be used in the SASL authentication.

It would be nice to introduce a method to configure a separate SASL_SSL listener. Something like:
```typescript
const kafkaContainer = await new KafkaContainer()
      .withSaslSslListener({
        port: 9094,
        user: {
          name: "app-user",
          password: "userPassword"
        },
        keystore: {
          pfx: fs.readFileSync(path.resolve(pathToCertificates, "kafka.server.keystore.pfx")),
          passphrase: "serverKeystorePassword"
        },
        truststore: {
          pfx: fs.readFileSync(path.resolve(pathToCertificates, "kafka.server.truststore.pfx")),
          passphrase: "serverTruststorePassword"
        }
      })
      .withExposedPorts(9093, 9094).start();
``` 

Keeping the existing 9093 port would be useful so that the tests can produce messages without having to provide additional config.

I can provide a PR that will introduce this.

**Comment by cristianrgreco** [comment]
Released in [v8.8.0](https://github.com/testcontainers/testcontainers-node/releases/tag/v8.8.0), thanks again @apokralipsa !
