### ISSUE TITLE
Feature request: allow configuration of exposed ports for PostgreSQL container

### ISSUE THREAD

**Issue by Robin-Hoodie** [testcontainers/testcontainers-node#356]
When calling `start` on an instance of `PostgreSQLContainer` https://github.com/testcontainers/testcontainers-node/blob/7580ad550b2e4a2221f55c75a7bb0774de6c07f0/src/modules/postgresql/postgresql-container.ts#L32 the exposed ports are hardcoded to `5432` so calling `withExposedPorts` while configuring the container does not work. 

A workaround is using an instance of `GenericContainer`.

Happy to create a PR if this issue is accepted.

**Comment by cristianrgreco** [comment]
Hi @Robin-Hoodie, yes I see that the exposed ports are overridden in the PostgreSQL container module, what is the use case for exposing non-postgres ports from the container?

**Comment by Robin-Hoodie** [comment]
Thanks for the swift reaction. 

No need to expose non-postgres ports. I do however want to specify the host port and not have this determined at random. I know this is not recommended.
The application that I want to test runs in another process. The Postgres client also lives in that application, so I can not easily control which port it uses to connect to the Postgres container. Otherwise I could have used `container#getPort`. 

Does that make sense?

**Comment by cristianrgreco** [comment]
Yes I think I understand, thanks for explaining - What you would like to do is replace the Postgres module's

```typescript
this.withExposedPorts(5432)
```

With:

```typescript
const myPort = 5432;

.withExposedPorts({
  container: 5432,
  host: myPort
})
```

Is my understanding correct? If so, my question is what should happen with the default exposed ports. Do you think the user provided ports should be appended to the existing or replace the existing?

**Comment by Robin-Hoodie** [comment]
> Is my understanding correct? 
Yes!
> what should happen with the default exposed ports. Do you think the user provided ports should be appended to the existing or replace the existing
I think we should indeed replacing the existing ports

**Comment by cristianrgreco** [comment]
Sounds good, we should probably do that in all the modules, PR welcome!
