### ISSUE TITLE
Support docker networks in order to resolve containers IPs by name

### ISSUE THREAD

**Issue by Quaiks** [testcontainers/testcontainers-node#36]
Hello!

I am trying to connect two containers but without any success. The only way I know to achieve this is using networks.

I've tried to add the feature myself but I am struggling a bit with typescript. Can I make this possible without networks?

I have this workaround using dockerode

```js
const opts = {
    "limit": 1,
    "filters": `{"name": ["${mysql.getName()}"]}`
};
const container = (await dockerode.listContainers(opts))[0];
const mysqlContainer = dockerode.getContainer(container.Id);
const ins = await mysqlContainer.inspect();
console.log(`My working IP! ${ins.NetworkSettings.IPAddress}`);
```

Regards!

**Comment by cristianrgreco** [comment]
Hi @Quaiks 

It looks to me that you're trying to get the IP address of a container. 
Here's an example from the README:

```typescript
const container = await new GenericContainer("redis")
    .withExposedPorts(6379)
    .start();

const ipAddress = container.getContainerIpAddress();
const port = container.getMappedPort(6379)
```

Does that help?

**Comment by Quaiks** [comment]
The problem is that `getContainerIpAddress` is returning the ip of the docker client, not the actual IP of the container.

https://github.com/testcontainers/testcontainers-node/blob/8b94ff8d22f3fbe6cd566a6aa402bb713b8e9f4f/src/generic-container.ts#L113-L120

I am always getting `locahost` as the IP address. I think a container does not resolve `localhost` to the the host running docker.

**Comment by cristianrgreco** [comment]
Yes I think that's correct, that the IP address of the container is the same as the Docker client, because they're on the same network.

If you try to connect to the result of `getContainerIpAddress()`, does it work? What is `dockerode` returning in your example?

**Comment by Quaiks** [comment]
It does not work with `getContainerIpAddress()` which returns localhost. In the example `ins.NetworkSettings.IPAddress` is returning `172.17.0.2` or whatever IP address inside the docker network. 

Using `getContainerIpAddress()` and the mapped port do not work.

**Comment by cristianrgreco** [comment]
What environment is this running in? 
Running the example I sent you I can connect to the container via localhost.

**Comment by Quaiks** [comment]
I am running this locally in a MacOS

**Comment by glerendegui** [comment]
I'm having this trouble to connect between container.
It looks similar to this bug of the java testcontainer implementation.
https://github.com/testcontainers/testcontainers-java/issues/1719
