### ISSUE TITLE
Question about version 8 comparing to version 7

### ISSUE THREAD

**Issue by jackkainov** [testcontainers/testcontainers-node#363]
Hi, sorry, didn't find any other type of issue, only a bug.
We have observed a strange behavior of version 8 on a Jenkin's agent, which is a Kubernetes pod. If I use the v8.9 of testcontainers, either as a generic container or a docker-compose environment, according to logs the process just halts, e.g.
```
testcontainers DEBUG Creating new Docker instance +0ms
testcontainers INFO  Docker host strategy OUTSIDE_CONTAINER: localhost +1s
testcontainers DEBUG Executing Docker credential provider: docker-credential-desktop +10ms
testcontainers DEBUG No credential found for registry: "https://index.docker.io/v1/" +430ms
  ```
  nothing is happening after this. My assumption is that the new changes in v8 require a connection to the docker daemon before proceeding? If it is correct, then what can be an issue in the docker inside a docker environment? 
  Sorry for the vague question, we have downgraded the version to v7 in our setup and it's been working fine since then.

**Comment by cristianrgreco** [comment]
Hi @jackkainov, some of those logs do not exist in version 8.9.0 of testcontainers. Could you please update to the latest version (8.9.0) and try again? If there is still an issue, please provide a repro of the code, and provide more information about the environment - it would have been very helpful if you filled out the bug report template.

**Comment by jackkainov** [comment]
Thx for answering @cristianrgreco, I didn't use the bug report because to me it seems like a configuration issue on our side. The working version was 7.24.0, and I did indeed try the v8.9.0. I can try to pinpoint if all v8 versions behave the same way or not.

**Comment by cristianrgreco** [comment]
No need to pinpoint all v8 versions. Please share the logs when using the latest version, as well as a code repro
