### ISSUE TITLE
Multistage Dockerfile with private registries does not build

### ISSUE THREAD

**Issue by daviian** [testcontainers/testcontainers-node#365]
**Expected Behaviour**

A Dockerfile containing multiple stages that also uses private registries should build fine and use the provided auth configs.

**Actual Behaviour**

The AuthLocator always tries to get the credentials for the DEFAULT_REGISTRY "https://index.docker.io/v1/" as it tries to find auth configs based on the registries in the Dockerfile.

The getDockerFileImages from dockerfile-parser.ts does not respect the form `FROM <registry>/<image>:<tag> as <stage>` and returns no registry for the affected FROM statement.

**Testcontainer Logs**
...

**Steps to Reproduce**
1. Create a Dockerfile with the content `FROM cristianrgreco/testcontainer-private:1.1.12 as first-stage`
2. Try to build the Dockerfile using `GenericContainer.fromDockerfile(context).withPullPolicy(new AlwaysPullPolicy()).build()`
4. See error...

**Environment Information**
- Operating System: Windows 10
- Docker Version:  20.10.12
- Node version: 16.15.0
- Testcontainers version: 8.4.0

**Comment by cristianrgreco** [comment]
Thanks @daviian, released in [8.10.1](https://github.com/testcontainers/testcontainers-node/releases/tag/v8.10.1)
