### ISSUE TITLE
No Docker client strategy found caused by invoked exported dockerClient

### ISSUE THREAD

**Issue by calvintwr** [testcontainers/testcontainers-node#367]
**Expected Behaviour**
No error should occur when setup files involving `dockerClient` are called.
...

**Actual Behaviour**
`No Docker client strategy found` error appears.
...

**Testcontainer Logs**
With `DEBUG=testcontainers*` on, testcointainers will run:
```
  testcontainers DEBUG Found applicable Docker client strategy: UnixSocketStrategy +0ms
  testcontainers DEBUG Testing Docker client strategy URI: unix:///var/run/docker.sock +1s
  testcontainers WARN  Docker daemon is not reachable: Error: connect ENOENT /var/run/docker.sock +118ms
  testcontainers WARN  Docker client strategy UnixSocketStrategy is not reachable +0ms
```
And the error:
```
No Docker client strategy found

      at node_modules/testcontainers/dist/docker/docker-client.js:46:11
      at fulfilled (node_modules/testcontainers/dist/docker/docker-client.js:5:58)
```
...

**Steps to Reproduce**
1. Write a generic setup "boilerplate" file like:

```ts
// setup.ts:
export const container = await new GenericContainer('postgres').withExposedPorts(5432).start()
```

```ts
// index.ts
import { container } from './setup.ts'

function start() {
    return null
}
start()
```

2. When you run `$ ts-node index.ts`, notice that you will get the error. But `container` was never used, only imported.

**Environment Information**
- Operating System: MacOS Monterey 12.4
- Docker Version: 4.8.1
- Node version: 16.13.1
- Testcontainers version: v8.10.1

**Comment by cristianrgreco** [comment]
@calvintwr share the test containers logs

**Comment by calvintwr** [comment]
@cristianrgreco I have created the PR for the fix.

**Comment by cristianrgreco** [comment]
@calvintwr I'm more interested in fixing why the Docker client was not found instead of making it lazy

**Comment by calvintwr** [comment]
@cristianrgreco the issue is not that it’s not found. The issue has more to do the search (`dockerClient`) being invoked when it shouldn’t have been. You can check my PR and advise how best to resolve this further.
