### ISSUE TITLE
Unable to run tests on AWS CloudBuild

### ISSUE THREAD

**Issue by Shpota** [testcontainers/testcontainers-node#369]
I have a Node.js project with Testcontainers used for staring Redis and Prostgress for tests.

I want to run these tests as a part of CI. For that purpose, I use an alpine image of Node.js with Docker installed on top of it. The tests work well on my local machine, but they fail in CloudBuild.

**Expected Behaviour**
Tests run well in AWS CloudBuild

**Actual Behaviour**
An error appears in logs
> No Docker client strategy found

**Steps to Reproduce**
1. Created Node.js project with it's tests cfreating a test container:
```
await new GenericContainer('postgres:14.2-alpine')
    .withEnv('POSTGRES_USER', 'mydb')
    .withEnv('POSTGRES_PASSWORD', 'mydb')
    .withEnv('POSTGRES_DB', 'mydb')
    .withExposedPorts(5432)
    .start();
 ```
2. Create a Docker builder image (the one that will be used in CloudBuild) based on `node:17.5.0-alpine`
3. Add Docker to the image:
```
wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
  wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.32-r0/glibc-2.32-r0.apk && \
  apk update --no-cache && apk add glibc-2.32-r0.apk docker && rm glibc-2.32-r0.apk
```
4. Run this project in CodeBuild and see the error.

**Environment Information**
- Operating System: Alpine
- Docker Version: 2.32-r0
- Node version: 17.5.0
- Testcontainers version: 7.20.5

**Comment by cristianrgreco** [comment]
@Shpota could you please share the testcontainers logs?

**Comment by Shpota** [comment]
@cristianrgreco I don't see anything specific to testcontainers in logs, this is all what I get (I changed names of test classes):
```
[Container] 2022/05/20 13:15:16 Running command yarn test
yarn run v1.22.17
$ jest
PASS apps/my-service/src/working-service/working-service.service.spec.ts (6.698 s)
FAIL apps/my-service/src/failing-service/failing-service.service.spec.ts
  ● FailingService › name of the test
    No Docker client strategy found
      at node_modules/testcontainers/dist/docker/docker-client.js:46:11
      at fulfilled (node_modules/testcontainers/dist/docker/docker-client.js:5:58)
```

**Comment by cristianrgreco** [comment]
@Shpota you'll need to run the tests with `DEBUG=testcontainers*` environment variable set, it's at the top of the readme

**Comment by Shpota** [comment]
Thank you @cristianrgreco 
This is what I get if I add debug:
```
2022-05-25T13:09:11.494Z testcontainers DEBUG Found applicable Docker client strategy: UnixSocketStrategy
2022-05-25T13:09:11.531Z testcontainers DEBUG Testing Docker client strategy URI: unix:///var/run/docker.sock
2022-05-25T13:09:11.539Z testcontainers DEBUG No registry auth locator found for registry: "https://index.docker.io/v1/"
2022-05-25T13:09:11.543Z testcontainers WARN  Docker daemon is not reachable: Error: connect ENOENT /var/run/docker.sock
2022-05-25T13:09:11.543Z testcontainers WARN  Docker client strategy UnixSocketStrategy is not reachable
2022-05-25T13:09:11.544Z testcontainers ERROR Failed to list images: Error: No Docker client strategy found
2022-05-25T13:09:11.544Z testcontainers ERROR Failed to pull image "postgres:14.2-alpine": Error: No Docker client strategy found
```

**Comment by cristianrgreco** [comment]
I haven't used AWS code build before but it seems the docker socket is not in its default location. Do you need to mount it into your build container or something?

**Comment by cristianrgreco** [comment]
@Shpota I see there was an answer https://stackoverflow.com/a/72396224/964145, did it help?
