### ISSUE TITLE
Container version tags don't work as expected

### ISSUE THREAD

**Issue by sazzer** [testcontainers/testcontainers-node#37]
When I'm using TestContainers with just an image name and nothing else, everything works fantastic. However, if I use a versioned image name then for some reason the container now no longer works.

For example, this works great:
```
    const postgres = await new GenericContainer('postgres')
        .withExposedPorts(5432)
        .start();
```
But this doesn't:

```
    const postgres = await new GenericContainer('postgres:11.5-alpine')
        .withExposedPorts(5432)
        .start();
```

On the second, I get the following output:
```
    (HTTP code 400) unexpected - invalid reference format

      at node_modules/docker-modem/lib/modem.js:257:17
      at getCause (node_modules/docker-modem/lib/modem.js:287:7)
      at Modem.Object.<anonymous>.Modem.buildPayload (node_modules/docker-modem/lib/modem.js:256:5)
      at IncomingMessage.<anonymous> (node_modules/docker-modem/lib/modem.js:232:14)
```

Cheers

**Comment by cristianrgreco** [comment]
Hi @sazzer 

The version is a separate argument: `new GenericContainer('postgres', '11.5-alpine')`.

I'll update the docs because it's not clear.

Does that help?

**Comment by sazzer** [comment]
That's perfect. Thank you :)

**Comment by cristianrgreco** [comment]
I've updated the README with an example. Thanks for flagging!
