### ISSUE TITLE
Can't start a container in Cypress project

### ISSUE THREAD

**Issue by alimMax** [testcontainers/testcontainers-node#374]
**Expected Behaviour**
Starting container with custom image

**Actual Behaviour**
Error while trying to start test:
`Cannot read properties of undefined (reading 'DEFLATE')`

![Screenshot from 2022-06-03 11-57-34](https://user-images.githubusercontent.com/56675132/171798212-7424faa8-aade-4338-82c9-cec0d9fa1895.png)

**Testcontainer Logs**
No logs, because I can't even start them :)

**Steps to Reproduce**
Here is my Cypress config:
_package,json_
`{
  "name": "cypress-typescript-example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "open": "cypress open"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^10.0.1",
    "testcontainers": "^8.10.1",
    "typescript": "^4.7.2"
  }
}
`
_tsconfig.json_
`{
    "compilerOptions": {
        "target": "es5",
        "lib": ["es5", "dom"],
        "types": [ "cypress", "node" ],
        "baseUrl": ".."
    },
    "include": [
        "**/*.ts"
    ]
}`

and some test example
`
describe("example test", () => {
    let container;

    before(async () => {
        container = await new GenericContainer("custom-image:latest")
            .withWaitStrategy(Wait.forLogMessage('nothing to update'))
            .start();
    })

    after(async () => {
        await container.stop()
    })

    it('checks', async () => {
        cy.visit('https://some.site');
        cy.get('.input').type('some search{enter}');
        cy.debug();
    })
})
`

**Environment Information**
- Operating System: Linux
- Docker Version: 20.10.14
- Node version: 16.15.0
- Testcontainers version: 8.10.1

**Comment by cristianrgreco** [comment]
@alimMax testcontainers cannot run in a browser, perhaps run it in a separate process to cypress?

**Comment by alimMax** [comment]
@cristianrgreco it works! Thanks a lot!
But now have another issue with starting containers in an interactive mode. I have put some executable files into the container. In order to properly run the container, I need to mark command as interactive. Otherwise, a container is just shut down. So, is there any way to do something like this?
`docker run -it DOCKER_IMAGE`

**Comment by cristianrgreco** [comment]
@alimMax there isn't an interactive mode. You could do like in the README and start the container with:

```javascript
.withCmd(["sleep", "infinity"])
```

And execute the commands needed manually:

```javascript
const { output, exitCode } = await container.exec(["echo", "hello", "world"]);
```

**Comment by alimMax** [comment]
@cristianrgreco thank you for your help!
