### ISSUE TITLE
Feature request: Remove docker-compose-environment associated volumes

### ISSUE THREAD

**Issue by gdonoso94** [testcontainers/testcontainers-node#376]
As well as for other containers, passing config object to `stop` is allowed, it'd be great to have this feature for Docker Compose environments `down` or `stop` methods. Such as
```
await dockerComposeEnvironment.stop({
  removeVolumes: true
});
```

```
await dockerComposeEnvironment.down({
  removeVolumes: true
});
```

Thanks.

**Comment by cristianrgreco** [comment]
Hi @gdonoso94, removing volumes isn't supported by docker-compose `stop`, but is in `down`, i'll raise a PR to support it. I'll also add the timeout so the options are the same for docker-compose as for a standard container.

**Comment by cristianrgreco** [comment]
Just seen that removing volumes is the default behaviour. Regardless I'm making it configurable.
