### ISSUE TITLE
require side effect : socket access on docker asynchronously triggered by import

### ISSUE THREAD

**Issue by tcharlat** [testcontainers/testcontainers-node#377]
**Expected Behaviour**
When I don't execute `new PostgreSqlContainer()` I expect require()'ing the library to be no-op with no side effect

**Actual Behaviour**
On the developer side, the library works as expected.
On circle ci, "docker in docker" is unavailable and the test image is started via the circleci.yml config.
Our test setup distinguished the developper env and the ci env and only starts a container when running tests on the developper side.

When running tests on the ci tests are passing if I required asynchronously, tests will throw at some point with
`
Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
`

I can fix this throw by requiring `testcontainer`conditionnally like so
```typescript
import type { StartedPostgreSqlContainer } from "testcontainers";
export async function startPostgresContainer() {
  const { PostgreSqlContainer } = await import("testcontainers");
  const container = await new PostgreSqlContainer()
    .withTmpFs({
      "/var/lib/postgresql/data": "rw,noexec,nosuid",
    })
    .start();
  const postgresSettings: PostgresConnection = {
    host: container.getHost(),
    port: container.getPort(),
    database: container.getDatabase(),
    user: container.getUsername(),
    password: container.getPassword(),
  };
  storeInstance(container);
  return postgresSettings;
}
``` 

**Testcontainer Logs**
...

**Steps to Reproduce**
1. In this environment : circle ci node:alpine-lts
2. With this config : require("testcontainers")
3. Run tests

**Environment Information**
- Operating System: unknown
- Docker Version: unknown
- Node version: lts
- Testcontainers version: ^7

**Comment by cristianrgreco** [comment]
Hi @tcharlat, this PR should fix it, but it seems to have been abandoned: https://github.com/testcontainers/testcontainers-node/pull/368, WDYT @calvintwr?

**Comment by cristianrgreco** [comment]
Fixed in [8.11.1](https://github.com/testcontainers/testcontainers-node/releases/tag/v8.11.1)

**Comment by calvintwr** [comment]
@cristianrgreco thanks much! Sorry I just didn’t had time at all. I’ll check it out. Once again thanks!

**Comment by tcharlat** [comment]
@cristianrgreco Thanks for the lightning fast fix, I missed the notification on github to thank you in due time.
I left the client context where I encountered this issue though so can't check myself.

@FannyMonet could you check if it's fixed for you ?
