### ISSUE TITLE
Configure AWS ECR

### ISSUE THREAD

**Issue by rudemex** [testcontainers/testcontainers-node#379]
**Expected Behaviour**
Hi, how are you? first of all, I wanted to thank you for this amazing library! it made my application development so much easier, but I need to configure the pull of the images to be done from an ECR from AWS, how can I do this configuration?

Thank you very much in advance.

**Actual Behaviour**
...

**Testcontainer Logs**
...

**Steps to Reproduce**
1. In this environment...
2. With this config...
3. Run '...'
4. See error...

**Environment Information**
- Operating System:
- Docker Version:
- Node version:
- Testcontainers version:

**Comment by rudemex** [comment]
Hi @cristianrgreco.

Great, I was reviewing a little bit the code, and I saw that there is an environment variable that calls a config.json with the registry data, but apparently it is not taking the data well.

```
DOCKER_CONFIG=<path-of-project>/.docker
```

inside the .docker folder there is a config.json file with the following data structure

```
{
  "auths": {
    "<url-ecr>": {
      "auth": "<hash-auth>"
    }
  }
}

```

**Comment by cristianrgreco** [comment]
@rudemex this scenario is covered by https://github.com/testcontainers/testcontainers-node/blob/91d9127f3e157a59f7371bec59effc5889096b1d/src/registry-auth-locator/auths.test.ts#L38-L53

Have you double checked the `DOCKER_CONFIG` path is correct? Can you confirm that the `<url-ecr>` matches the repository of the image you are trying to pull from? Could you run your app with the env variable `DEBUG=testcontainers*` and share the logs?
