### ISSUE TITLE
Override option for entrypoint

### ISSUE THREAD

**Issue by bikash001** [testcontainers/testcontainers-node#382]
There is no way to override entrypoint for the images which has entrypoint defined. Docker client has that option but testcontainers hasn't exposed it.

**Comment by cristianrgreco** [comment]
Sure @bikash001, would you be able to raise a PR?

**Comment by bikash001** [comment]
> Sure @bikash001, would you be able to raise a PR?

Yes, I will raise a PR.

**Comment by dicolasi** [comment]
Hi all,
I am struggling to understand how to override the entry point of a docker image. Has the functionality been implemented?

**Comment by cristianrgreco** [comment]
Hi @dicolasi, this hasn't been implemented, it would make for a good first PR if you're up for it

**Comment by dicolasi** [comment]
I have 0 idea how to implement this. Sorry @cristianrgreco
