### ISSUE TITLE
Unable to connect to sibling container on same network using network alias

### ISSUE THREAD

**Issue by maggie-weber** [testcontainers/testcontainers-node#385]
I'm trying to run two sibling containers on the same network such that `barContainer` is able to make HTTP connections to `fooContainer`. I ran into this issue when trying to implement a feature in a close-source project, so I copied the implementation from [the Java testcontainers documentation](https://www.testcontainers.org/features/networking/#advanced-networking) to get a minimal reproduction. It doesn't appear that `bar` is able to see `foo` using the network alias.

```
const { GenericContainer, Network } = require("testcontainers")

async function main() {
    console.log("Starting main()");
    
    const network = await new Network().start();
    const foo = await new GenericContainer("alpine:3.10")
        .withNetworkMode(network.getName())
        .withNetworkAliases("foo")
        .withCmd(
            "/bin/sh",
            "-c",
            "while true ; do printf 'HTTP/1.1 200 OK\\n\\nyay' | nc -l -p 8080; done"
        )
        .start();
    const bar = await new GenericContainer("alpine:3.10")
        .withNetworkMode(network.getName())
        .withCmd("top")
        .start();

    const { output, exitCode } = await bar.exec(["wget", "-O", "-", `http://foo:8080`]);
    console.log(`Exit Code: [${exitCode}]\nOutput: [${output}]`);
    
    await foo.stop();
    await bar.stop();
}

(async() => {
    await main();
})();
``` 

```
PS C:\Users\mweber\workspaces\node-projects\test> node index.js
Starting main()
Exit Code: [1]
Output: []
```
**Environment Information**
- Operating System: Windows 10 21H2 (OS Build 19044.1826)
- Docker Version: Docker Desktop 4.10.1 (82475). Engine>Version 20.10.17
- Node version: v16.16.0
- Testcontainers version: ^8.12.0 
- A colleague observed the same behavior on a Mac.

**Comment by cristianrgreco** [comment]
Hi @maggie-weber, this functionality is tested as part of the CI/CD pipeline. 
Please have a look on your side what could be different: https://github.com/testcontainers/testcontainers-node/blob/8f6ad11e0c73ac5f2b232902404a087a67b3315f/src/generic-container/generic-container.test.ts#L114-L133
