### ISSUE TITLE
testcontainers is unable to start in CodeBuild

### ISSUE THREAD

**Issue by YashchenkoN** [testcontainers/testcontainers-node#388]
I have a simple test starting postgres container:
```
describe('Test', () => {
    let pgContainer: StartedPostgreSqlContainer

    beforeAll(async () => {
        pgContainer = await new PostgreSqlContainer("public.ecr.aws/docker/library/postgres:14.2-alpine")
            .withWaitStrategy(Wait.forLogMessage('database system is ready to accept connections'))
            .start()
    })

    afterAll(async () => pgContainer.stop())

    it('should connect to pg', async () => {
        // test
    })
})
```

It works perfectly well on my laptop.

**Expected Behaviour**
I expect this test to run successfully in AWS CodeBuild.

**Actual Behaviour**
CodeBuild build hangs while starting the container and eventually times out.

**Testcontainer Logs**
```
testcontainers DEBUG Found applicable registry auth locator for registry "public.ecr.aws": Auths
testcontainers DEBUG Found applicable Docker client strategy: UnixSocketStrategy
testcontainers DEBUG Testing Docker client strategy URI: unix:///var/run/docker.sock

thrown: "Exceeded timeout of 120000 ms for a hook.
Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
```

**Environment Information**
- Operating System: Amazon Linux 2 x86_64 standard image, version 4.0
- privileged flag is set to true (as stated in https://stackoverflow.com/questions/72278034/aws-codebuild-how-to-run-tests-that-require-starting-docker)
- Node version: 16
- Testcontainers version: 8.12.0

**Important note**
I tried running the same test written in Java, within the same CodeBuild env, and it completes successfully, without any issues / timeouts. It leads me to think that the issue comes from `testcontainers-node` and not env configuration.

**Comment by cristianrgreco** [comment]
> I tried running the same test written in Java, within the same CodeBuild env, and it completes successfully, without any issues / timeouts. It leads me to think that the issue comes from testcontainers-node and not env configuration.

Interesting, thanks for raising, I will take a look when I can.

**Comment by mukitmomin** [comment]
Facing the same issue. Any updates @cristianrgreco? 

The `testcontainer` works like a charm on my local machine but hangs on AWS CodeBuild. I checked to make sure the docker daemon on aws codebuild, with privileged access, but facing the same issue.

**Environment Information**
- Amazon Linux 2, version 5
- Node version: 16
- Testcontainers version: 8.13.0

**Comment by knihit** [comment]
+1

**Comment by cristianrgreco** [comment]
Hi, should be fixed in version [8.13.2](https://github.com/testcontainers/testcontainers-node/releases/tag/v8.13.2), please confirm

**Comment by mukitmomin** [comment]
Hey @cristianrgreco, can confirm, this update fixed the issue. Many thanks!

**Comment by YashchenkoN** [comment]
Now everything works very well! Thank you!

**Comment by ywilkof** [comment]
I can confirm this has solved same issue when running test-containers with our self hosted Github runners.
