### ISSUE TITLE
Can't connect to postgres container

### ISSUE THREAD

**Issue by rflpazini** [testcontainers/testcontainers-node#39]
I'm facing some troubles when trying to connect to Postgres container. In my integration tests, I'm using jest and supertest to run...

This is the error message
```sh
findAll() >> Error: Error: connect ECONNREFUSED 127.0.0.1:5432
          at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
```

And here is my test class:

```js
const { GenericContainer } = require('testcontainers');
const request = require('supertest');

const { Promise } = require('bluebird')
const cmd = require('node-cmd');

const app = require('../../app');

describe('User routes', () => {
  jest.setTimeout(45000);

  let container = '';

  beforeAll(async () => {
    container = await new GenericContainer('postgres', 'alpine')
      .withEnv('POSTGRES_USER', 'bidu')
      .withEnv('POSTGRES_PASSWORD', 'test')
      .withExposedPorts(5432)
      .start();

    process.env.DATABASE_URL = `postgres://bidu:test@localhost:${container.getMappedPort(
      5432
    )}/bidu`;

    const getAsync = Promise.promisify(cmd.get, { multiArgs: true, context: cmd })

    await getAsync('npm run migrate up').then(data => {
      console.log('cmd data', data)
    }).catch(err => {
      console.log('cmd err', err)
    });
  });

  afterAll(async () => {
    await container.stop();
  });

  test('should return 200 on get all users', async (done) => {
    request(app)
      .get('/v1.0/users/all')
      .end((err, res) => {
        console.log(res);
        expect(res).not.toBeNull();
        expect(res.statusCode).toBe(200);
        done();
      });
  });
});
```

Could you give more examples of how to connect with Postgres or something like that?

**Comment by cristianrgreco** [comment]
Is `localhost` correct for this environment? 
Could you replace it with `container.getContainerIpAddress()` and try again?

**Comment by rflpazini** [comment]
`localhost` replaced  and get the same error 😢

**Comment by rflpazini** [comment]
If you want to see, my project is on github... Here is the [link](https://github.com/rflpazini/bidu/tree/feat/create-database)

**Comment by cristianrgreco** [comment]
Could you re-run the test with DEBUG output?
For example: `DEBUG=testcontainers npm test`

**Comment by rflpazini** [comment]
```
2019-09-18T16:02:20.694Z testcontainers INFO: Using Docker defaults
2019-09-18T16:02:20.744Z testcontainers INFO: Creating container for image: postgres:alpine
2019-09-18T16:02:20.866Z testcontainers INFO: Starting container with ID: 3fb18b4e64e9330dd11b3fee54201985b8f38ce889afd13160c6d4f8ce8d8448
2019-09-18T16:02:21.491Z testcontainers DEBUG: Starting container health checks
2019-09-18T16:02:21.491Z testcontainers DEBUG: Waiting for host port :52492
2019-09-18T16:02:21.496Z testcontainers DEBUG: Waiting for internal port :5432
2019-09-18T16:02:23.642Z testcontainers DEBUG: Container health checks complete
 FAIL  test/service/UserService.test.js (5.547s)
  ● Console
```

**Comment by cristianrgreco** [comment]
Maybe it's unrelated, but can you do `async (done)` in a test? I thought it one or the other (either `async () -> {}` or `done -> { done() }`

**Comment by rflpazini** [comment]
I'm currently running `done => { done() }` in my test "/

```js
test('should return 200 on get all users', done => {
    request(app)
      .get('/v1.0/users/all')
      .end((err, res) => {
        console.log(res);
        expect(res).not.toBeNull();
        expect(res.statusCode).toBe(200);
        done();
      });
  });```

**Comment by cristianrgreco** [comment]
I don't see what the issue could be, there don't seem to be any errors from Testcontainers, you're just not able to connect to a container which is supposedly running.

Perhaps you could start Postgres via Testcontainers and leave the container running. 
Then see via the Docker CLI if you can connect.

**Comment by rflpazini** [comment]
I will do that @cristianrgreco and try to figure out what is happening ... Thanks for your help

**Comment by Reiser-meta** [comment]
@rflpazini in your error msg, your application is trying to connect port 5432 and not the ephemeral port of docker, i think the error is in there

**Comment by rflpazini** [comment]
@Reiser-meta Do you know how to change it to ephemeral port instead of `5432`?

**Comment by cristianrgreco** [comment]
@rflpazini Are you sure that the port is set to `container.getMappedPort(5432)` everywhere you connect?

**Comment by Reiser-meta** [comment]
@rflpazini when you require the app.js, maybe it is trying to connect your database, can you move this requie after you set the env DATABASE_URL?

**Comment by rflpazini** [comment]
You're awesome guys @cristianrgreco @Reiser-meta 🥰 . It's working now!!! I have only to fix my migration script that stills pointing to `localhost:5432`
