### ISSUE TITLE
testcontainers works only when setting DOCKER_CONFIG

### ISSUE THREAD

**Issue by Nilegfx** [testcontainers/testcontainers-node#410]
**Expected Behaviour**
test container works fine when logged in with a private docker registry and having `~/.docker/config.json` in place

**Actual Behaviour**
test container only works if I set the `DOCKER_CONFIG` env although my docker config is at `~/.docker/config.json` which I can see that this is the default [here](https://github.com/testcontainers/testcontainers-node/blob/e7a52d3c26fd3b0adafdb47bcbe093c6bf7a0819/src/registry-auth-locator/index.ts#L16) 

**Testcontainer Logs**
```
  testcontainers DEBUG Found applicable Docker client strategy: UnixSocketStrategy +0ms
  testcontainers DEBUG Testing Docker client strategy URI: unix:///var/run/docker.sock +1ms
  testcontainers INFO  Using Docker client strategy: UnixSocketStrategy, Docker host: localhost +6ms
  testcontainers DEBUG Fetching system diagnostics +0ms
  testcontainers DEBUG Executing Docker credential provider: docker-credential-private-registry-name +1ms
  testcontainers DEBUG System diagnostics: {"node":{"version":"v16.15.0","architecture":"arm64","platform":"darwin"},"docker":{"serverVersion":"20.10.18","operatingSystem":"Alpine Linux v3.16","operatingSystemType":"linux","architecture":"aarch64","cpus":5,"memory":8323563520},"dockerCompose":{"version":"2.11.1"}} +55ms
  testcontainers ERROR Unexpected response from Docker credential provider LIST command: "" +199ms
```
**Steps to Reproduce**
1. in mac M1 
2. with this config 
```
{
  "auths": {},
  "credHelpers": {
    "private.subdomain.domain.com": "private_registry_name"
  },
  "credsStore": "osxkeychain"
}
```
4. Run the example in the read me file
5. See error
```
  testcontainers ERROR Unexpected response from Docker credential provider LIST command: "" +199ms
```

**Environment Information**
- Operating System: Mac
- Docker Version:
```
Client:
 Version:           20.10.17-rd
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        c2e4e01
 Built:             Fri Jul 22 18:32:57 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a6d3c55ceda3bd5475be7aae6036d02db3
  Built:            Sun Sep 11 07:10:00 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        5fd4c4d144137e991c4acebb2146ab1483a97925
 docker-init:
  Version:          0.19.0
  GitCommit:
```
- Node version: tested on 12, 14 and 16
- Testcontainers version: 9.0.0

I am using rancher desktop 
and here is my mac details
![image](https://user-images.githubusercontent.com/1198975/200150262-35dc5263-4b0c-4fc2-bff3-e945a6857e81.png)

the workaround is to set the `DOCKER_CONFIG` env to `$HOME/.docker/config.json` in my bash profile 

```bash
export DOCKER_CONFIG=$HOME/.docker/config.json
```

but this is inconvenient as my colleagues has to set it and in case I changed my mac later I have to remember how did I fix the issue. 

I tried to debug the issue from VSCode (when I don't set the `DOCKER_CONFIG`) by adding break points in `node_modules/testcontainers/dist/registry-auth-locator/index.js` at line 49 and 54 but those line never executes. 

I can debug further if there are some development instruction on how to debug using the source code not the compiled code as it is super tricky with the compiled code. I have strong feeling that one of the promises are rejecting but not quite sure which one. 

### update 
I think I misunderstood the issue. so when setting`DOCKER_CONFIG=$HOME/.docker/config.json` the code adds another `/config.json` 
```
const dockerConfigLocation = process.env.DOCKER_CONFIG || `${os.homedir()}/.docker`;
const dockerConfigFile = path.resolve(dockerConfigLocation, "config.json");
```
which means it sets the `DOCKER_CONFIG` incorrectly and that makes it work.  

when testcontainer code finds my docker config correctly somehow it can't use correctly. I confirmed this assumption by setting: 
```
export DOCKER_CONFIG="invalid path" 
```
and indeed it worked. 

not sure how to debug the credentials though :(

**Comment by Nilegfx** [comment]
I was able to debug my issue. looks like an issue from our internal setup/tooling. 

when I changed the config to 
```json
{
  "auths": {},
  "credHelpers": {
    "private.subdomain.domain.com": "osxkeychain" # instead of our private credentials program name 
  },
  "credsStore": "osxkeychain"
}
```
things worked.

**Comment by Nilegfx** [comment]
I guess [this line](https://github.com/testcontainers/testcontainers-node/blob/e7a52d3c26fd3b0adafdb47bcbe093c6bf7a0819/src/registry-auth-locator/credential-provider.ts#L21) and the following couple of lines are the root cause of my issue as my internal credentials program doesn't support list command and all what this code does it try to find the credentials to log one message. is logging this message is that important or we can remove this check or try to handle it better? I can provide PR.

**Comment by cristianrgreco** [comment]
HI @Nilegfx, that line doesn't just log a message, it returns undefined, which [tells testcontainers that it hasn't found authentication info for the given repository](https://github.com/testcontainers/testcontainers-node/blob/e7a52d3c26fd3b0adafdb47bcbe093c6bf7a0819/src/registry-auth-locator/index.ts#L48). I don't think that the issue lies within testcontainers to handle custom credential providers which don't follow spec (they should support LIST, and return JSON)
