### ISSUE TITLE
Looking for help using the `KafkaContainer`

### ISSUE THREAD

**Issue by sylhare** [testcontainers/testcontainers-node#416]
Using the [KafkaContainer](https://github.com/testcontainers/testcontainers-node/blob/master/src/modules/kafka/kafka-container.ts) I am trying to get the bootstrap server so I can connect my producer/consumer to it, however it's not advertised in the `StartedKafkaContainer`.

Looking at the java [documentation](https://www.testcontainers.org/modules/kafka/), I was expecting to be able to do something like:

```ts
const kafka: StartedKafkaContainer = await new KafkaContainer('confluentinc/cp-kafka').start();

// Does not exist
const brokers = kafka.getBootstrapServers();
```

Is there some more documentation on how I should be doing it with the node version? I see a `bootstrapServers` in the `KafkaContainer` class, so I am guessing we could get it that way too.

Thanks!

**Comment by eddumelendez** [comment]
@sylhare look at the test

https://github.com/testcontainers/testcontainers-node/blob/08454582aee7efd74312236040dc76d6c907d3a5/src/modules/kafka/kafka-container.test.ts#L114-L118

**Comment by sylhare** [comment]
Ah indeed! Thanks 👌
