### ISSUE TITLE
Unhandled failure of docker-credential-desktop causes silent failure

### ISSUE THREAD

**Issue by manterfield** [testcontainers/testcontainers-node#420]
## Summary

I've just chased down a bug when using this library as part of jest `globalSetup` (via a fork of the `jest-testcontainers` library).

If the library is ran without being logged into docker, it silently fails. (This may be MacOS specific, and the silence is likely exacerbated by jest).

I would be happy to create the fix, but I'm not 100% on the implications for the wider code.

## Info

Looking at `runCredentialProvider` function here: https://github.com/testcontainers/testcontainers-node/blob/master/src/registry-auth-locator/credential-provider.ts#L57-L81

This code never rejects its promise in the event of an exception or non-zero exit code. In my case, I hadn't ran `docker login` and so this process was returning an error message instead of credentials. The function above continues to process this error message as if it were json, catches the JSON parse exception, logs and then continues, leaving the promise in a pending state.

Interestingly, earlier versions of the library (`4.7.0`) successfully spawned the containers regardless of me being logged in or not.

**Steps to Reproduce**
Not sure I can create an isolated, reproducible error given the dependencies between docker, my OS, this library, etc.

**Environment Information**
- Operating System: MacOS 12.6
- Docker Version:  20.10.14
- Node version: v16.15.0
- Testcontainers version: 9.0.0 (also tested 9.1.0)

**Comment by cristianrgreco** [comment]
Hi @manterfield, thanks for raising, though I wish you'd filled out the issue template because now I'll need to ask you to share the logs 🙂 I'm also on MacOS, and tried running this test after a `docker logout`:

https://github.com/testcontainers/testcontainers-node/blob/86ef45d792dae55cbb35fc898fcb8b3786f427a3/src/generic-container/generic-container.test.ts#L40-L49

The test fails immediately with the following expected error as expected:

```
Error: (HTTP code 404) unexpected - pull access denied for cristianrgreco/testcontainer-private, 
repository does not exist or may require 'docker login': denied: requested access to the resource is denied 
```

I'll need the logs to be able to debug further

**Comment by cristianrgreco** [comment]
Could you try out version 9.1.2-beta.1 and let me know if it fixes your issue?

**Comment by manterfield** [comment]
Sorry,  I figured since I'd debugged down to a definite issue in the code it'd be no big deal - but yeah, that was silly on my part. Of course you'd want to check the original issue. 😄 

I probably would have been better off raising this on a place for discussion first as I was happy to fix once I'd had a sense check, but failed to spot if such a place exists. (apologies if I just missed it, my bad).

---
## More info:

This wasn't actually a private registry. It's a public one (`postgres` on docker hub).

Logs:
```
Determining test suites to run...  testcontainers DEBUG Found applicable Docker client strategy: UnixSocketStrategy +0ms
  testcontainers DEBUG Testing Docker client strategy URI: unix:///var/run/docker.sock +0ms
  testcontainers INFO  Using Docker client strategy: UnixSocketStrategy, Docker host: localhost +15ms
  testcontainers DEBUG Fetching system diagnostics +0ms
  testcontainers DEBUG Executing Docker credential provider: docker-credential-desktop +1ms
  testcontainers WARN  Docker credential provider exited with code: 1 +58ms
  testcontainers ERROR Unexpected response from Docker credential provider GET command: "credentials not found in native keychain
  testcontainers " +0ms
  testcontainers DEBUG System diagnostics: {"node":{"version":"v16.15.0","architecture":"arm64","platform":"darwin"},"docker":{"serverVersion":"20.10.14","operatingSystem":"Docker Desktop","operatingSystemType":"linux","architecture":"aarch64","cpus":5,"memory":10434543616},"dockerCompose":{"version":"2.4.1"}} +67ms
```

I can login and it goes away, log out again and get the above.

Whilst I haven't used private images with this package, I have private docker registries configured on my machine (GCP artifact registry using their credential helpers).

**Comment by cristianrgreco** [comment]
Thanks @manterfield, could you try version `9.1.2-beta.1` and let me know if it fixes your issue?
