### ISSUE TITLE
Authenticate using gitlab DOCKER_AUTH_CONFIG env variable

### ISSUE THREAD

**Issue by owodunni** [testcontainers/testcontainers-node#428]
**Expected Behaviour**
When using gitlab CI and running `testcontainers` I would like it to use the gitlab environment variable config. It is set on the environment variable DOCKER_AUTH_CONFIG. It already needs to be setup for gitlab to be able to fetch from [private registries](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#access-an-image-from-a-private-container-registry) so being able to reuse it for `testcontainers` to authenticate seams pretty plesent. 

**Actual Behaviour**
testcontainers fail to fetch containers.

**Testcontainer Logs**
```No Docker client strategy found
    at ../../node_modules/testcontainers/dist/docker/docker-client.js:46:11
    at fulfilled (../../node_modules/testcontainers/dist/docker/docker-client.js:5:58)
```

**Steps to Reproduce**
1. In a gitlab ci runner try to fetch from a private registry

**Environment Information**
- Operating System: Docker in docker executing in node:16 container
- Docker version: unclear
- Node version: 16
- Testcontainers version: 8.13.0

**Comment by owodunni** [comment]
I managed to get a simple test repository up and failing! https://gitlab.com/alexanderp2/testcontainers-dind-test

Looking at it some more I'm not confident that the fixes that I proposed on github will actually solve the issue. It might just be that the authentication needs to be configured outside of testcontainers when running in this type of nested CI environment. Ohh well, more debugging I guess.

**Comment by owodunni** [comment]
I got some more feedback, 

"From a quick look it seems you’re missing DOCKER_HOST config.

If I had to guess I’d say you’re mounting docker socket from the underlying system and running directly on it and not the dind service:
 2022-12-22T05:42:13.735606282Z failed to load listeners: can't create unix socket /var/run/docker.sock: device or resource busy
You can access the host docker through /var/run/docker_host.sock on shared runners although"

I guess my test repository is not configured correctly.

**Comment by cristianrgreco** [comment]
Will be supported by https://github.com/testcontainers/testcontainers-node/pull/476, thanks for raising @owodunni
