### ISSUE TITLE
TypeError: Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by rashid5** [testcontainers/testcontainers-node#44]
Hello,

First of all, thanks for the great library! 👍 

I'm having a problem when running my test using jest - it happens only intermittently on my machine, but seems to happen all the time in CircleCI.

This is my test code:

```
let pgContainer: StartedTestContainer;
let pgPort: number;

beforeAll(async () => {
  pgContainer = await new GenericContainer("postgres", "11.5")
    .withEnv("POSTGRES_USER", "postgres")
    .withEnv("POSTGRES_PASSWORD", "postgres")
    .withExposedPorts(5432)
    .start();
  pgPort = pgContainer.getMappedPort(5432);
});

afterAll(async () => {
  await pgContainer.stop();
});
```

This is the error I get from jest:
```
Test suite failed to run

    TypeError: Cannot read property 'stop' of undefined

      20 | 
      21 | afterAll(async () => {
    > 22 |   await pgContainer.stop();
         |                     ^
      23 | });
      24 | 
      25 | describe("Database Integration", () => {

      at services/notifications/src/app.spec.ts:22:21
      at services/notifications/src/app.spec.ts:8:71
      at Object.<anonymous>.__awaiter (services/notifications/src/app.spec.ts:4:12)
      at Object.<anonymous> (services/notifications/src/app.spec.ts:21:21)
```

Thanks!

**Comment by cristianrgreco** [comment]
Hi @rashid5 

Your example shows that `pgContainer` is assigned the result of starting the container. Unless there's been some exception and the result is `undefined` it's not possible for `pgContainer.stop()` to throw.

Could you please share a complete/reproducible example?

**Comment by rashid5** [comment]
Hi @cristianrgreco 

Thanks for your response!

Yeah, I know right - it doesn't make sense to me either.

It's hard to get something completely reproducible since the problem is intermittent, but I was able to reproduce it with the pared down but complete example below. I stopped and removed all my docker containers before running, and ran 6 times - 3 passed and 3 failed.

```
import "reflect-metadata";
import { createConnection } from "typeorm";
import { StartedTestContainer, GenericContainer } from "testcontainers";

let pgContainer: StartedTestContainer;
let pgPort: number;

beforeAll(async () => {
  pgContainer = await new GenericContainer("postgres", "11.5")
    .withEnv("POSTGRES_USER", "postgres")
    .withEnv("POSTGRES_PASSWORD", "postgres")
    .withExposedPorts(5432)
    .start();
  pgPort = pgContainer.getMappedPort(5432);
});

afterAll(async () => {
  await pgContainer.stop();
});

describe("Database Integration", () => {
  test("Test that the createDatabseConnection returns a valid connection to the database", async () => {
    const connection = await createConnection({
      type: "postgres",
      host: "localhost",
      port: pgPort,
      username: "postgres",
      password: "postgres",
      database: "postgres",
      synchronize: true,
      entities: ["src/entities/**/*.ts"]
    });
    expect(connection.isConnected).toBeTruthy();
    await connection.close();
  });
});
```
![Screenshot 2019-12-06 at 12 40 30](https://user-images.githubusercontent.com/5686867/70323784-a3d93880-1825-11ea-8db3-7f95c44a8d9b.png)

![Screenshot 2019-12-06 at 12 37 44](https://user-images.githubusercontent.com/5686867/70323706-7096a980-1825-11ea-87fe-61dc7396aacc.png)

Those results are all with the exact same code. Really quite bizarre, right?

**Comment by cristianrgreco** [comment]
Hi @rashid5 

My assumption is that the default jest timeout isn't enough to pull the postgres image and start it. The tests are more likely to fail on CI envs as it's unlikely they'll already have the postgres image.

I was also able to reproduce the issue with your code (thanks!) and can verify that it's working after increasing the timeout in the beforeAll:

```javascript
beforeAll(async () => {
  jest.setTimeout(60000);
  pgContainer = await new GenericContainer("postgres", "11.5")
    .withEnv("POSTGRES_USER", "postgres")
    .withEnv("POSTGRES_PASSWORD", "postgres")
    .withExposedPorts(5432)
    .start();
  pgPort = pgContainer.getMappedPort(5432);
});
```

**Comment by rashid5** [comment]
Hi @cristianrgreco 

Ahh interesting - it's cool that you were able to reproduce the error.

I've tried increasing the timeout all the way to 600000 but I still get the error in CI - I'm not sure but I don't think it can take 10 minutes to pull and start the image, even in CircleCI... On the other hand, it does seem to have made it disappear locally, which would be some evidence in favour of your assumption being correct.

I wonder if building to javascript and then running might make a difference, rather than running using ts-jest...I might try that tomorrow and will let you know.

**Comment by cristianrgreco** [comment]
@rashid5 Could you run your tests with DEBUG=testcontainers set as an environment variable and share the output? I'm curious to see if/where testcontainers is getting stuck.

**Comment by rashid5** [comment]
@cristianrgreco Yep sure (included text for searchability and screenshot for colours):

```
#!/bin/bash -eo pipefail
echo "$DEBUG"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
yarn test:integration --forceExit --ci --runInBand

testcontainers
yarn run v1.19.2
$ yarn workspace notifications test:integration --forceExit --ci --runInBand
$ jest --testPathPattern=spec\.ts$ --forceExit --ci --runInBand
  testcontainers INFO: Using Docker configuration from DOCKER_HOST: tcp://104.155.171.195:2376 +0ms
  testcontainers INFO: Using Docker in Docker method +2ms
  testcontainers INFO: Pulling image: postgres:11.5 +346ms
  testcontainers DEBUG: Docker version: 17.09.0-ce +88ms
  testcontainers WARN: Docker environment should have more than 2GB free disk space +0ms
  testcontainers INFO: Creating container for image: postgres:11.5 +9s
  testcontainers INFO: Starting container with ID: d5a13f0e6cd0730b484a84b91710e7eba83f605dfb2f72e1105b7f7efead45f1 +1s
  testcontainers DEBUG: Starting container health checks +506ms
  testcontainers DEBUG: Waiting for host port :42941 +1ms
  testcontainers DEBUG: Waiting for internal port :5432 +2ms
 FAIL  src/app.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'stop' of undefined

      17 | 
      18 | afterAll(async () => {
    > 19 |   await pgContainer.stop();
         |                     ^
      20 | });
      21 | 
      22 | describe("Database Integration", () => {

      at src/app.spec.ts:19:21
      at step (src/app.spec.ts:33:23)
      at Object.next (src/app.spec.ts:14:53)
      at src/app.spec.ts:8:71
      at Object.<anonymous>.__awaiter (src/app.spec.ts:4:12)
      at Object.<anonymous> (src/app.spec.ts:18:10)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        76.62s
Ran all test suites matching /spec.ts$/i.
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /root/.yarn/lib/cli.js test:integration --forceExit --ci --runInBand
Directory: /root/project/services/notifications
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
```

![Screenshot 2019-12-10 at 12 41 32](https://user-images.githubusercontent.com/5686867/70530273-70aae800-1b4a-11ea-9b9c-04063653e3db.png)

**Comment by cristianrgreco** [comment]
@rashid5 Looks like the postgres container isn't able to listen on port 5432. I think this is more an issue of your CI environment setup. Are you able to inspect the logs of the postgres container to see what it's doing? I've also found this documentation about using testcontainers in Circle CI: https://www.testcontainers.org/supported_docker_environment/continuous_integration/circle_ci/

**Comment by rashid5** [comment]
@cristianrgreco Ah interesting, thanks for sharing that link. Interestingly what they recommend is how I was running the tests in CircleCI originally, with the 600s timeout, and it was still failing - but it does seem likely that the problem is to do with the CI config in some way, I'm just not sure exactly how.

Feel free to close this issue - I might post an update if I do manage to figure out how to make it work, for anyone who comes across this in future.

Thanks very much for your help :)

**Comment by totalamd** [comment]
@rashid5 So???
