### ISSUE TITLE
withReuse ignores any custom labels set on the container

### ISSUE THREAD

**Issue by henrinormak** [testcontainers/testcontainers-node#442]
**Expected Behaviour**
Any labels added via `withLabels` should be present on the container, even if `withReuse` is used.

**Actual Behaviour**
Seems like [withReuse](https://github.com/testcontainers/testcontainers-node/blob/master/src/generic-container/generic-container.ts#L125) drops any specified labels

This assumption comes from the fact that the hashing takes the labels into account, therefore it should be safe to assume that the labels are the same, which should also mean they are safe to be added to the container.

I would imagine that the fix should be as simple as changing that one line to not replace the labels entirely, but to combine the hash label with the other labels? If so, I can file a PR for this if that helps.

**Testcontainer Logs**
N/A

**Steps to Reproduce**
1. Configure a generic container with some custom labels
2. Enable reuse with `withReuse`
3. Once container is started, check the labels via `docker inspect` or just use `container.getLabels()`
4. Notice that the custom labels are not present (only the hash label is), even if the container was created and previously did not exist

**Comment by henrinormak** [comment]
@cristianrgreco any chance to address this? Would not want to fork the library just for this small thing, for what it's worth, I am willing to help with some other changes as well if needed, the package seems like a good fit for the stack we use where I work and if the integration of it works out, I don't see a reason why I could not help with some of the maintenance.

**Comment by cristianrgreco** [comment]
Released in https://github.com/testcontainers/testcontainers-node/releases/tag/v9.1.2, thanks @henrinormak
