### ISSUE TITLE
Get Database URL from PostgreSqlContainer

### ISSUE THREAD

**Issue by nikeee** [testcontainers/testcontainers-node#448]
The `StartedPostgreSqlContainer` has getter functions for password, username, etc. This is everything needed to connect to the DB.

Some DB APIs support connecting using an URL like this ([source](https://www.prisma.io/dataguide/postgresql/short-guides/connection-uris)):
```
postgres[ql]://[username[:password]@][host[:port],]/database[?parameter_list]
```

This could be accomplished with the URL type, which takes care of properly escaping names/passwords:
```js
const url = new URL("", "postgres://");
url.hostname = pg.getHost();
url.port = pg.getPort().toString();
url.pathname = pg.getDatabase();
url.username = pg.getUsername();
url.password = pg.getPassword();

url.toString(); // connection string
```

Is this in scope and/or open for contribution?

**Comment by cristianrgreco** [comment]
@nikeee it is indeed! A PR would be most welcome 🙂
