### ISSUE TITLE
unknown flag: --env-file with docker compose v2 when using withEnvironmentFile function

### ISSUE THREAD

**Issue by viswanr** [testcontainers/testcontainers-node#480]
**Expected Behaviour**
The DockerComposeEnvironment is successfully created

**Actual Behaviour**
Errors out with:
unknown flag: --env-file
    See 'docker --help'.

    Usage:  docker [OPTIONS] COMMAND

**Steps to Reproduce**
1. Install Docker Desktop on Windows with WSL enabled and Docker Compose V2 enabled.

The following code fails:
```
// Setup docker compose environment
    const env = new DockerComposeEnvironment(
      ".",
      "docker-compose.yml"
    ).withBuild();
    if (envFile && envFile.length > 0) {
      env.withEnvironmentFile(envFile);
    }

    // Starting services within container
    this.sandbox = await env.up(this.functionAppServices);
```
**Environment Information**
- Operating System: Windows
- Docker Version: Docker Desktop 4.16.3 (96739), Docker Engine v20.10.22
- Node version: v16.19.0
- Testcontainers version: "^9.1.3"

Looks like there is some ordering problem of arguments to docker with compose v2?

**Comment by cristianrgreco** [comment]
Hi @viswanr, thanks for raising - I've tried on a Mac with compose V2 and it works. I see there's a similar issue here about this feature not working in Windows, could it be what you're seeing? https://github.com/docker/compose/issues/6965

**Comment by viswanr** [comment]
I don't think it's the same thing. I clearly see an error saying --env-file is an unknown flag. Any idea how I can grab test container logs?

**Comment by viswanr** [comment]
Callstack:
```
at node_modules/testcontainers/dist/docker-compose/functions/docker-compose-up.js:37:15
          at Generator.throw (<anonymous>)
      at rejected (node_modules/testcontainers/dist/docker-compose/functions/docker-compose-up.js:6:65)
```

**Comment by viswanr** [comment]
So if i select the following, it fails. If i deselect, it works. How can we set the version of docker compose?
<img width="423" alt="image" src="https://user-images.githubusercontent.com/62660433/222953609-01f72912-72a4-4750-9b73-4e10d108b400.png">

**Comment by cristianrgreco** [comment]
I've just tested an environment file with spaces, also no issue. 
If the issue persists please provide a small repro and I will re-open, closing this for now.

**Comment by Lysander086** [comment]
The command option order really matters. The below is what works for my Windows 11.
```shell
docker compose -f .\local.yml --env-file .\docker_local.env up 
```
