### ISSUE TITLE
Does not work with podman

### ISSUE THREAD

**Issue by td0m** [testcontainers/testcontainers-node#487]
**Expected Behaviour**
Setting `DOCKER_HOST` to podman socket and disabling `RYUK` should work correctly such as with other testcontainer implementations (works fine with `go` and `java`)

**Actual Behaviour**
It fails on trying to obtain credentials [here](https://github.com/testcontainers/testcontainers-node/blob/351973a08f7fe5ab6a211736dd0086c6f13a8c17/src/registry-auth-locator/credential-provider.ts#L19) because the docker related binaries are not there..

**Testcontainer Logs**
```
Error: An error occurred listing credentials
```

**Steps to Reproduce**
Start any generic container after disabling RYUK and setting `DOCKER_HOST` to a podman socket.

**Environment Information**
- Operating System: MacOS
- Docker Version: -
- Node version: LTS
- Testcontainers version: 9.1.3

**Comment by cristianrgreco** [comment]
Hi @td0m, the implementation is the same as tc-java (https://github.com/testcontainers/testcontainers-java/blob/f591ac7ef68119503473bd7d09b7b3a5cf4b3db8/core/src/main/java/org/testcontainers/utility/RegistryAuthLocator.java#L332), could you please elaborate on why that's causing an issue?

**Comment by cristianrgreco** [comment]
I am integrating podman as a workflow here: https://github.com/testcontainers/testcontainers-node/pull/494. I am not sure about officially supporting podman, but already I've found an issue which would prevent tc-node from recognising podman via the `DOCKER_HOST`, will keep you updated.
