### ISSUE TITLE
Can't run in AWS CodeBuild after version 1.3.1

### ISSUE THREAD

**Issue by stalar** [testcontainers/testcontainers-node#49]
When running versions higher than 1.3.1 in AWS CodeBuild I get an error saying "Error: Port :39195 not bound after 60000ms".

This is the full output running with "DEBUG=testcontainers":

    2020-02-03T12:35:46.072Z testcontainers INFO: Using Docker in Docker method
    2020-02-03T12:35:46.106Z testcontainers INFO: Pulling image: postgres:11.5
    2020-02-03T12:35:58.817Z testcontainers INFO: Creating container for image: postgres:11.5
    2020-02-03T12:36:00.850Z testcontainers INFO: Starting container with ID: 25734549ff033c92c0fb07ce168387f69d6d6e823f86e88467097dc1bf3f7707
    2020-02-03T12:36:01.504Z testcontainers DEBUG: Starting container health checks
    2020-02-03T12:36:01.505Z testcontainers DEBUG: Waiting for host port :39195
    2020-02-03T12:36:01.508Z testcontainers DEBUG: Waiting for internal port :5432
    Error: Port :39195 not bound after 60000ms
        at retryStrategy.retryUntil (/codebuild/output/src627916599/src/github.com/Pepins/pepinsx/lambda-js/node_modules/testcontainers/dist/wait-strategy.js:59:23)
        at IntervalRetryStrategy.<anonymous> (/codebuild/output/src627916599/src/github.com/Pepins/pepinsx/lambda-js/node_modules/testcontainers/dist/retry-strategy.js:35:28)
        at Generator.next (<anonymous>)
        at fulfilled (/codebuild/output/src627916599/src/github.com/Pepins/pepinsx/lambda-js/node_modules/testcontainers/dist/retry-strategy.js:4:58)
        at process._tickCallback (internal/process/next_tick.js:68:7)

My code looks like this:

    dbContainer = await new GenericContainer('postgres', '11.5')
        .withEnv('POSTGRES_PASSWORD', 'xxxx')
        .withEnv('POSTGRES_USER', 'yyyy')
        .withExposedPorts(5432)
        .start();

I'm using the `aws/codebuild/standard:1.0` image in AWS CodeBuild.

**Comment by stalar** [comment]
Could this be caused by "nc" not being installed in the image?

**Comment by cristianrgreco** [comment]
Hi @stalar, I assume you mean version 2.3.1? If so, could you please confirm that the issue does not exist in a previous version? For example 2.3.0 and 2.2.0? If it works on a previous version I assume the issue isn't a missing `nc` as that hasn't changed.

**Comment by stalar** [comment]
Hi! I tested 1.3.1 (works), 2.0.0 (does not work), 2.3.1 (does not work). I think I tested 2.2.0 as well, but can't remember - no version above 1.3.1 worked. I can do additional testing if you know what I should look for.

**Comment by cristianrgreco** [comment]
One relevant difference between 1.3.1 and 2.0.0 is https://github.com/testcontainers/testcontainers-node/commit/5655a1701fa43c50c406867f4c9c860db6374ac1#diff-ecd99b80d72b339d9b4c0e6cafbdb1b7R25, which added support for running testcontainers using docker in docker, which from your log (`INFO: Using Docker in Docker method` seems to be the case.

I am not sure why that method doesn't seem to work with AWS code build. 

Are you able to try setting the `DOCKER_HOST` environment variable as described here https://github.com/testcontainers/testcontainers-node#usage?

**Comment by stalar** [comment]
I can set `DOCKER_HOST`, although I'm not sure what the value should be. I tried "tcp://docker:2375", but that didn't work (tried with 2.3.1):

    Error: getaddrinfo ENOTFOUND docker docker:2375
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)

The code looks like the value of DOCKER_HOST isn't used. It is checked, but then the if-statement after will override it unless I am missing something: https://github.com/testcontainers/testcontainers-node/blob/215461f37cca8c4d2fabbf38577647fe7d6b491b/src/docker-client-factory.ts#L25

**Comment by cristianrgreco** [comment]
I tried running the tests for this project via AWS code build and it would fail when trying to find the default gateway. Node was throwing an ENOENT error. 

The default-gateway package we use spawns a child process which I think is running into this: https://forums.aws.amazon.com/thread.jspa?threadID=290406.

**Comment by stalar** [comment]
> The default-gateway package we use spawns a child process which I think is running into this:
> https://forums.aws.amazon.com/thread.jspa?threadID=290406.

I think that link refers to a problem with spawning processes on windows (at least they talk about launching cmd.exe). The problem with default-gateway can be that "ip" is not installed in the AWS image.

I did some more experiments, and CodeBuild exposes the docker daemon through `/var/run/docker.sock` which is the default method for dockerode to connect to it. CodeBuild also has a `/.dockerenv` file in the filesystem which confuses testcontainers. For running on CodeBuild it would be best to run the last else-statement in the `DockerodeClientFactory` constructor. 

I'm not sure how to rewrite the logic to make that happen, though. In particular I am not certain under which circumstances `/.dockerenv` is present (other than in CodeBuild). One thought is to accept `unix:///var/run/docker.sock` as a value for `DOCKER_HOST` and then call the dockerode constructor `new Docker({socketPath: process.env.DOCKER_HOST});`. A drawback would be that anyone running on CodeBuild would need to set that variable.

**Comment by stalar** [comment]
I modified `DockerodeClientFactory` to only run the code in the last else-statement, and all tests in testcontainers pass on CodeBuild.

**Comment by cristianrgreco** [comment]
Hi @stalar, thanks for investigating. 

Do you think this commit will solve the issue? Essentially it's checking if an environment variable set by code build exists and if so follows the code branch that works: https://github.com/testcontainers/testcontainers-node/commit/4ca8e7430eb384dcd52973f488fdc44393d59f66

**Comment by stalar** [comment]
Hi @cristianrgreco!

That commit should work. `CODEBUILD_CI` isn't document, though: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html, so maybe picking `CODEBUILD_BUILD_NUMBER` or `CODEBUILD_BUILD_ARN` instead?

**Comment by cristianrgreco** [comment]
@stalar PR: https://github.com/testcontainers/testcontainers-node/pull/50

**Comment by cristianrgreco** [comment]
@stalar 2.3.2 has been released, could you upgrade and let me know how it goes?

**Comment by stalar** [comment]
@cristianrgreco Works like a charm - all of my tests are passing now! 💯

**Comment by cristianrgreco** [comment]
Awesome, thanks for raising the issue and helping fix it @stalar!
