### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by henrinormak** [testcontainers/testcontainers-node#495]
Seems like it has been a while since 9.1.3 release and quite a few updates have landed in master since then, any plan for a release to get these out? Most specifically I'm after the performance improvements of #453

**Comment by cristianrgreco** [comment]
Hey @henrinormak, yes definitely, there are a couple of fixes I'm trying to get out first and will release it then, almost certainly this week

**Comment by henrinormak** [comment]
Anything I could help out with? I wouldn't mind taking on something, working with this library has been a nice change of pace.

**Comment by cristianrgreco** [comment]
@henrinormak regarding the release, I'm running into some issues this morning with it. The publish pipeline was using Node 12 which didn't publish correctly after the latest changes. I've updated the pipeline to 18 and see it published correctly (https://github.com/testcontainers/testcontainers-node/actions/runs/4435262927/jobs/7782209003), but the version isn't showing up on NPM, it's been several mins now, haven't seen such a delay before.. I guess I will continue to monitor.. I'm not seeing any reported issues with NPM.

> Anything I could help out with? I wouldn't mind taking on something, working with this library has been a nice change of pace.

That's great! If you're familiar with any of the modules that exist in other TC implementations, it'd be great to get them into tc-node to reach feature parity. WDYT?

**Comment by henrinormak** [comment]
I have not played around with other flavours of TC, but if you can point me in the direction of any specific module that would be good to have, I can start to dig in.

**Comment by cristianrgreco** [comment]
Thanks @henrinormak! Here's a list of modules supported by tc-java: https://www.testcontainers.org/modules/redpanda/. _Any_ contribution greatly appreciated, it doesn't have to be modules, your performance improvements and bug fixes were also very helpful

**Comment by cristianrgreco** [comment]
@henrinormak 9.2.1 released!
