### ISSUE TITLE
docker-modem depencency  new version breaks tests

### ISSUE THREAD

**Issue by fx-it** [testcontainers/testcontainers-node#496]
**Expected Behaviour**
Tests work correctly: postgres db runs in docker correctly

**Actual Behaviour**
Got error: No Docker client strategy found

**Testcontainer Logs**
testcontainers DEBUG Found applicable Docker client strategy: UnixSocketStrategy +0ms
testcontainers DEBUG Testing Docker client strategy URI: unix:///var/run/docker.sock +1ms
testcontainers WARN  Docker client strategy UnixSocketStrategy is not reachable +59ms
No Docker client strategy found
at node_modules/.pnpm/testcontainers@9.1.3/node_modules/testcontainers/dist/docker/docker-client.js:46:11
at fulfilled (node_modules/.pnpm/testcontainers@9.1.3/node_modules/testcontainers/dist/docker/docker-client.js:5:58)

**Environment Information**
- Operating System: Ubuntu 22.04.2 LTS
- Docker Version: Docker version 23.0.1, build a5ee5b1
- Node version: v18.12.1
- Testcontainers version: 9.1.3 (^9.0.0).

**Description**
Hello. After i today reinstall node-modules, i face the problem during tests running: No Docker client strategy found. But last week (on friday) everything was normal. I started looking for problem:
1. Increased testcontainers version from 8.16.0 to 9.1.3 - no changes.
2. Found that testcontainers's dependency - dockerode relesed a new version these holidays: 3.3.4 -> 3.3.5. I decreased it to 3.3.4 again in package.json in overrides section - no changes.
3.  Found that dockerode's dependency - docker-modem relesed a new version these holidays: 3.0.6 -> 3.0.7. I decreased it to 3.0.6 again in package.json in overrides section. My tests started work correctly. There are the changes: https://github.com/apocas/docker-modem/compare/v3.0.6...v3.0.7.

I use testcontainers to run postges db this common way:
```
const container = await new GenericContainer('postgres:14-alpine')
      .withEnvironment({
        POSTGRES_DB: 'db_name',
        POSTGRES_USER: 'db_user_name',
        POSTGRES_PASSWORD: 'db_password',
      })
      .withExposedPorts('db_port')
      .withStartupTimeout(300000)
      .start();
 ```

Actually i don't know who should care about this problem (testcontainer or docker-modem maintainers)

**Comment by cristianrgreco** [comment]
Thanks for raising @fx-it, I will look into it.

**Comment by Gaen** [comment]
Stepped on it just now

<img width="755" alt="image" src="https://user-images.githubusercontent.com/1899551/224677174-0ccaed48-3c76-40a5-bff5-c1e0a52379d8.png">
<img width="740" alt="image" src="https://user-images.githubusercontent.com/1899551/224677367-f79370c3-382e-4d30-b5e0-39baea6e5a50.png">

**Comment by Gaen** [comment]
[docker-modem](https://github.com/apocas/docker-modem) has been released with a [breaking change](https://github.com/apocas/docker-modem/pull/150) as a patch bump `v3.0.6` -> `v3.0.7`.

Suggestion: pin `v3.0.6` until resolved.

**Comment by cristianrgreco** [comment]
Hi @fx-it, @Gaen, could you please test testcontainers@9.1.4-beta.2 and confirm it's working for you?

**Comment by cristianrgreco** [comment]
Although I see the author of docker-modem is rolling back the change as another patch release, so I think there's nothing for us to do here.

**Comment by fx-it** [comment]
Tomorrow will try on the lastest version of docker-modem and with stable version of testcontainers. I have to go now.

**Comment by cristianrgreco** [comment]
With the new docker-modem version this is resolved.

**Comment by fx-it** [comment]
confirmed, works
