### ISSUE TITLE
Documentation does not include Log flag options

### ISSUE THREAD

**Issue by andonyns** [testcontainers/testcontainers-node#517]
**Expected Behaviour**
Previous versions had an explanation of the environment variables that could be configured for debugging.

See https://github.com/testcontainers/testcontainers-node/commit/f59ec732e8bacfb8c41e72fa7945a1b6f744906b#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L25

**Actual Behaviour**

There is no information about these flags on the website. This is very useful for debugging, might be easier for new users.

**Comment by cristianrgreco** [comment]
You're right, thanks @andonyns, I will get this added back
