### ISSUE TITLE
No Docker client strategy found (M2 Mac)

### ISSUE THREAD

**Issue by LuisMalhadas** [testcontainers/testcontainers-node#523]
**Expected Behaviour**
Tests run correctly, connecting to mongodb

**Actual Behaviour**
as pointed on the title:
I am using Jest like tests in bun.js runtime, and I get "No Docker client strategy"

**Testcontainer Logs**
Don't have much of a log:
luismal@Luiss-MBP _AA % bun install                                                       
bun install v0.5.8 (1a25af5e)
 + testcontainers@9.4.0

 1 packages installed [22.00ms]
luismal@Luiss-MBP Sia_AA % DOCKER_HOST=unix:///Users/luismal/.docker/run/docker.sock bun test
bun test v0.5.8 (1a25af5e)

AccessManager.test.ts:
53 |             else {
54 |                 logger_1.log.warn(`Docker client strategy ${strategy.getName()} is not reachable`);
55 |             }
56 |         }
57 |     }
58 |     throw new Error("No Docker client strategy found");
              ^
error: No Docker client strategy found
      at /Users/luismal/Projects/_AA/node_modules/testcontainers/dist/src/docker/docker-client.js:58:10
      at fulfilled (/Users/luismal/Projects/_AA/node_modules/testcontainers/dist/src/docker/docker-client.js:5:47)

**Steps to Reproduce**
1. In this environment...

2. With this config...

import { MongoDBContainer, StartedMongoDBContainer } from "testcontainers";

let startedContainer: StartedMongoDBContainer;
let manager: AccessManager;

beforeAll(async () => {
    startedContainer = await new MongoDBContainer("mongo:latest").start();
    manager = ManagerFactory.createAccessManager();
});

3. Run ''
DOCKER_HOST=unix:///Users/luismal/.docker/run/docker.sock bun test
4. See error...
Pointed on the logs

**Environment Information**
- Operating System: Mac M2 (Ventura 13.3)
- Docker Version: (Docker Desktop 4.17.0 (99724))
- Node version: Bun.JS 0.5.8
- Testcontainers version: 9.4.0

I have read previous issues similar to mine, but none have worked...

**Comment by cristianrgreco** [comment]
Hi @LuisMalhadas 

The logs would greatly help here. Re-run your scenario with the environment variable `DEBUG=testcontainers*` and provide the output here.

Is there a reason you're providing the `DOCKER_HOST` environment variable? Latest versions of testcontainers will pick up the socket from your home dir.

The error says that the client is not reachable, which is just the result of trying to ping Docker via the socket. Please provide the output of the following:

```bash
curl --unix-socket /Users/luismal/.docker/run/docker.sock http://localhost/_ping
```

If this output is OK, then I will review the logs when you provide them, but I suspect is an issue with bun.js. Could you please also try with NodeJS?

**Comment by LuisMalhadas** [comment]
Hi @cristianrgreco,

Thanks for your availability.

I was trying the various solutions I found in the closed issues from this repository, so the DOCKER_HOST was just to show it.

The quickstart example works, using Node.js only.
But couldn't make something that is closer to my example work, due to other (well, most likely lack of knowledge) issues like timeouts and imports that are not well referenced by me.

Bun.JS is very compatible with NodeJs, so it shouldn't be so complicated to sort this... but I'm not very knowledgable here. Here is a compatibility list: https://bun.sh/docs/ecosystem/nodejs in case it helps... Bun is also a WIP.

The curl output:
```shell
luismal@Luiss-MBP _AA % curl --unix-socket /Users/luismal/.docker/run/docker.sock http://localhost/_ping
OK%
```

And the logs:
```shell
luismal@Luiss-MBP _AA % DEBUG=testcontainers* bun test
bun test v0.5.9 (f3ab445c)

AccessManager.test.ts:
  testcontainers DEBUG Loaded properties:  +0ms
  testcontainers DEBUG Found applicable Docker client strategy: UnixSocketStrategy +3ms
  testcontainers DEBUG Testing Docker client strategy URI: unix:///var/run/docker.sock +0ms
end {
  "objectMode": false,
  "highWaterMark": 16384,
  "finalCalled": false,
  "needDrain": false,
  "ending": false,
  "ended": false,
  "finished": false,
  "destroyed": false,
  "decodeStrings": true,
  "defaultEncoding": "utf8",
  "writing": false,
  "corked": 0,
  "sync": true,
  "bufferProcessing": false,
  "onwrite": [Function: onwrite],
  "writecb": null,
  "writelen": 0,
  "afterWriteTickInfo": null,
  "buffered": [],
  "bufferedIndex": 0,
  "allBuffers": true,
  "allNoop": true,
  "pendingcb": 0,
  "constructed": true,
  "prefinished": false,
  "errorEmitted": false,
  "emitClose": true,
  "autoDestroy": true,
  "errored": null,
  "closed": false,
  "closeEmitted": false,
  [Symbol(kOnFinished)]: [],
  "getBuffer": [Function: getBuffer],
  "bufferedRequestCount": [Getter]
}
finishMaybe -- state, sync {
  "objectMode": false,
  "highWaterMark": 16384,
  "finalCalled": false,
  "needDrain": false,
  "ending": true,
  "ended": false,
  "finished": false,
  "destroyed": false,
  "decodeStrings": true,
  "defaultEncoding": "utf8",
  "writing": false,
  "corked": 0,
  "sync": true,
  "bufferProcessing": false,
  "onwrite": [Function: onwrite],
  "writecb": null,
  "writelen": 0,
  "afterWriteTickInfo": null,
  "buffered": [],
  "bufferedIndex": 0,
  "allBuffers": true,
  "allNoop": true,
  "pendingcb": 0,
  "constructed": true,
  "prefinished": false,
  "errorEmitted": false,
  "emitClose": true,
  "autoDestroy": true,
  "errored": null,
  "closed": false,
  "closeEmitted": false,
  [Symbol(kOnFinished)]: [],
  "getBuffer": [Function: getBuffer],
  "bufferedRequestCount": [Getter]
} true
needFinish true
needFinish true
  testcontainers WARN  Docker daemon is not reachable: ConnectionRefused: Unable to connect. Is the computer able to access the url? +4ms
  testcontainers WARN  Docker client strategy UnixSocketStrategy is not reachable +0ms
  testcontainers DEBUG Found applicable Docker client strategy: RootlessUnixSocketStrategy +0ms
  testcontainers DEBUG Testing Docker client strategy URI: unix:///Users/luismal/.docker/run/docker.sock +0ms
end {
  "objectMode": false,
  "highWaterMark": 16384,
  "finalCalled": false,
  "needDrain": false,
  "ending": false,
  "ended": false,
  "finished": false,
  "destroyed": false,
  "decodeStrings": true,
  "defaultEncoding": "utf8",
  "writing": false,
  "corked": 0,
  "sync": true,
  "bufferProcessing": false,
  "onwrite": [Function: onwrite],
  "writecb": null,
  "writelen": 0,
  "afterWriteTickInfo": null,
  "buffered": [],
  "bufferedIndex": 0,
  "allBuffers": true,
  "allNoop": true,
  "pendingcb": 0,
  "constructed": true,
  "prefinished": false,
  "errorEmitted": false,
  "emitClose": true,
  "autoDestroy": true,
  "errored": null,
  "closed": false,
  "closeEmitted": false,
  [Symbol(kOnFinished)]: [],
  "getBuffer": [Function: getBuffer],
  "bufferedRequestCount": [Getter]
}
finishMaybe -- state, sync {
  "objectMode": false,
  "highWaterMark": 16384,
  "finalCalled": false,
  "needDrain": false,
  "ending": true,
  "ended": false,
  "finished": false,
  "destroyed": false,
  "decodeStrings": true,
  "defaultEncoding": "utf8",
  "writing": false,
  "corked": 0,
  "sync": true,
  "bufferProcessing": false,
  "onwrite": [Function: onwrite],
  "writecb": null,
  "writelen": 0,
  "afterWriteTickInfo": null,
  "buffered": [],
  "bufferedIndex": 0,
  "allBuffers": true,
  "allNoop": true,
  "pendingcb": 0,
  "constructed": true,
  "prefinished": false,
  "errorEmitted": false,
  "emitClose": true,
  "autoDestroy": true,
  "errored": null,
  "closed": false,
  "closeEmitted": false,
  [Symbol(kOnFinished)]: [],
  "getBuffer": [Function: getBuffer],
  "bufferedRequestCount": [Getter]
} true
needFinish true
needFinish true
  testcontainers WARN  Docker daemon is not reachable: ConnectionRefused: Unable to connect. Is the computer able to access the url? +1ms
  testcontainers WARN  Docker client strategy RootlessUnixSocketStrategy is not reachable +0ms
53 |             else {
54 |                 logger_1.log.warn(`Docker client strategy ${strategy.getName()} is not reachable`);
55 |             }
56 |         }
57 |     }
58 |     throw new Error("No Docker client strategy found");
              ^
error: No Docker client strategy found
      at /Users/luismal/Projects/_AA/node_modules/testcontainers/dist/src/docker/docker-client.js:58:10
      at fulfilled (/Users/luismal/Projects/_AA/node_modules/testcontainers/dist/src/docker/docker-client.js:5:47)
✗ Create a user
```

**Comment by fabien-h** [comment]
oh 😥

Bun is super practical with the typescript support.

I've lost 4 hours to try to understand why this was failing I believed it was a docker issue. Maybe a quick note in the doc about this incompatibility could help the next guy.
