### ISSUE TITLE
Add support for checking container health status if using HEALTHCHECK

### ISSUE THREAD

**Issue by sgronblo** [testcontainers/testcontainers-node#53]
Docker supports defining a separate HEALTHCHECK command that can be run internally to check whether the container is "healthy".

`testcontainers-node` mentions doing its own "health checks" at https://github.com/testcontainers/testcontainers-node/blob/878e2ef087939e4ff7d024eeb7de12024e6006c4/src/generic-container.ts#L180

However, this seems to refer only to checking that ports are listening. In some cases such as starting a postgres container this is not enough. The port may be opening but the DB isn't ready to receive queries, resulting in the error: "error: the database system is starting up". Note: this is not 100% verified.

`testcontainers-java` has another wait strategy called `Wait.forHealthcheck` https://github.com/testcontainers/testcontainers-java/blob/f113979ad5207464490cc4f19f488bb27795802c/core/src/main/java/org/testcontainers/containers/wait/strategy/Wait.java#L69 which basically keeps checking the `.State.Health.Status` of the container until its true.

From my understanding of a quick check of the source code of `testcontainers-node` this does not seem to be supported. It is possible that healthchecks are implicitly included somewhere along the line, but based on the Java version needing an explicit healthcheck wait strategy I assume a similar strategy would be needed for the Node version.

So what we would like is something like:

`new GenericContainer('postgres').withWaitStrategy(Wait.healthcheck()).start()`

One issue that seems to come up here is that you can currently only have a single wait strategy. It might be the case that you want to wait for a combination of conditions, but let's keep that out of scope for this issue.

**Comment by cristianrgreco** [comment]
Hi @sgronblo 

Please review https://github.com/testcontainers/testcontainers-node/pull/54

**Comment by cristianrgreco** [comment]
Available in version 2.5.0.
