### ISSUE TITLE
`No Docker client strategy found` with `podman`

### ISSUE THREAD

**Issue by sneko** [testcontainers/testcontainers-node#539]
Hi @cristianrgreco ,

I read other posts about `podman` but not totally sure how people succeeded in using it with `testcontainers` (for basic usage I mean). (Note that I used your library with Docker without troubles previously).

When running a test I get `No Docker client strategy found`.

From what I understand `testcontainers` is not finding the socket. So to find it I use:
```
podman machine inspect --format '{{.ConnectionInfo.PodmanSocket.Path}}'
```

That gives me `/Users/sneko/.local/share/containers/podman/machine/qemu/podman.sock`.

---

So I tried to customize it:
```
export DOCKER_HOST=/Users/sneko/.local/share/containers/podman/machine/qemu/podman.sock
```

It says `[ERR_INVALID_URL]: Invalid URL`

---

Then tried:
```
export DOCKER_HOST=unix:///Users/sneko/.local/share/containers/podman/machine/qemu/podman.sock
```

It says
```
(HTTP code 500) server error - fill out specgen: unix:///Users/sneko/.local/share/containers/podman/machine/qemu/podman.sock:/var/run/docker.sock:rw: incorrect volume format, should be [host-dir:]ctr-dir[:option]
```

---

I also `unset DOCKER_HOST` and then try both:
```
export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/Users/sneko/.local/share/containers/podman/machine/qemu/podman.sock
export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=unix:///Users/sneko/.local/share/containers/podman/machine/qemu/podman.sock
```

But nothing changes...

---

I'm a bit lost, do you know what's needed please?

Thank you,

**Environment Information**
- Operating System: MacOS
- Testcontainers version: `v9.5.0`

**Comment by sneko** [comment]
@cristianrgreco found a working solution by using both:
```
export DOCKER_HOST=unix:///Users/sneko/.local/share/containers/podman/machine/qemu/podman.sock
export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/Users/sneko/.local/share/containers/podman/machine/qemu/podman.sock
```

But I'm not sure to understand. Why I need to have both at the same time? Can't `testcontainers` infer `DOCKER_HOST` according to `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE`? Or vice-versa?

Thank you,

**Comment by cristianrgreco** [comment]
Hi @sneko, 

Take a look at how Podman is setup and used in this project's CICD pipeline: https://github.com/testcontainers/testcontainers-node/blob/main/.github/workflows/test.yml#L70-L84

One difference is the location of the socket that's used.

Note that there is a PR that's been merged to improve Podman support: https://github.com/testcontainers/testcontainers-node/pull/515, but it hasn't yet been released.

**Comment by sneko** [comment]
I saw https://github.com/testcontainers/testcontainers-node/blob/main/.github/workflows/test.yml#L70-L84 but for whatever reason I did something wrong. Indeed just retested and `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE` is not needed.

Thank you 👍

**Comment by cristianrgreco** [comment]
Hi @sneko, I recently updated the supported container runtimes doc with a section for MacOS/Podman: https://node.testcontainers.org/supported-container-runtimes/

Could you please have a look and let me know if the workaround fixes your issue?

**Comment by sneko** [comment]
Using `export TESTCONTAINERS_RYUK_DISABLED=true` was the solution! Thank you for the reactivity.

About https://node.testcontainers.org/supported-container-runtimes/ you should probably replace `XDG_RUNTIME_DIR` by running `podman machine inspect --format '{{.ConnectionInfo.PodmanSocket.Path}}'`. On my MacOS `$XDG_RUNTIME_DIR` is empty.

**Comment by cristianrgreco** [comment]
> About https://node.testcontainers.org/supported-container-runtimes/ you should probably replace XDG_RUNTIME_DIR by running podman machine inspect --format '{{.ConnectionInfo.PodmanSocket.Path}}' because on my MacOS $XDG_RUNTIME_DIR is empty.

This is a good point, I will update the docs.

> (curious to know how to use Ryuk? Because I tried podman machine set --rootful so I thought permissions would work properly?)

I also would love to know how to make it work :slightly_smiling_face: As of now I don't know what's the issue. Ryuk is also working fine in colima and rancher, so the issue may be Podman specific.
