### ISSUE TITLE
(HTTP code 400) bad parameter - Client sent an HTTP request to an HTTPS server.

### ISSUE THREAD

**Issue by narraressan** [testcontainers/testcontainers-node#55]
I always run into this error when running `npm run test`

```
(HTTP code 400) bad parameter - Client sent an HTTP request to an HTTPS server.


      at node_modules/docker-modem/lib/modem.js:257:17
      at getCause (node_modules/docker-modem/lib/modem.js:287:7)
      at Modem.Object.<anonymous>.Modem.buildPayload (node_modules/docker-modem/lib/modem.js:256:5)
      at IncomingMessage.<anonymous> (node_modules/docker-modem/lib/modem.js:232:14)
```

I totally have no idea why.

a few info that may help

`node: v10.16.1`
`Docker version 18.09.3, build 774a1f4eee` -- using docker toolbox instead of desktop

cheers!

**Comment by cristianrgreco** [comment]
Hi @narraressan 

Could you share some code which reproduces the issue? Are you able to start containers via the docker CLI? Also the stack trace is from docker modem, why is it an issue for testcontainers?
