### ISSUE TITLE
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"

### ISSUE THREAD

**Issue by jonny64** [testcontainers/testcontainers-node#565]
how do I 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"' on container startup?

needs something like withInitScript ()

https://github.com/testcontainers/testcontainers-java/issues/2728

**Comment by cristianrgreco** [comment]
Hi @jonny64, `withInitScript` isn't implemented in testcontainers-node. PR is welcome :slightly_smiling_face:

**Comment by cristianrgreco** [comment]
Hi @jonny64, I've taken a quick look at this. It seems the official postgres image supports this already: https://hub.docker.com/_/postgres/

> If you would like to do additional initialization in an image derived from this one, add one or more *.sql, *.sql.gz, or *.sh scripts under /docker-entrypoint-initdb.d (creating the directory if necessary). After the entrypoint calls initdb to create the default postgres user and database, it will run any *.sql files, run any executable *.sh scripts, and source any non-executable *.sh scripts found in that directory to do further initialization before starting the service.

Based on this, the following should work, let me know if it doesn't:

```ts
const postgresContainer = await new PostgreSqlContainer()
  .withCopyFilesToContainer([{ source: "/path/to/initscript", target: "/docker-entrypoint-initdb.d/initscript" }])
  .start();
```

**Comment by jonny64** [comment]
@cristianrgreco thanks!

I've read https://node.testcontainers.org/modules/postgresql/

`withCopyFilesToContainer` seems like undocumented hack for me

**Comment by cristianrgreco** [comment]
@jonny64 Do you mean this? https://node.testcontainers.org/features/containers/#with-filescontent
