### ISSUE TITLE
Option to remove a container 

### ISSUE THREAD

**Issue by Duchynko** [testcontainers/testcontainers-node#60]
Hello,

Would it make sense to implement a wrapper around `dockerode.remove()`? 

I want to clean up containers after tests have finished running. Instead of installing dockerode separately in my application, this could be a nice enhancement to the library. I think it's a quite straightforward feature, but just to provide an example, I'd like to be able to do something like this.

```javascript
afterAll(() => {
	pgContainer.stop({ timeout: new Duration(10, TemporalUnit.SECONDS) })
	pgContainer.remove()
})
```

I'll be happy to create a PR if that gets approval from maintainers... :)

**Comment by cristianrgreco** [comment]
Hi @Duchynko, the containers should be being cleared up automatically when the container is stopped. Is this not what you're seeing?

**Comment by Duchynko** [comment]
Hey @cristianrgreco, I figured out it was a problem with my test setup and jest instead. 

```javascript
afterAll(async () => {
	await pgContainer.stop({ timeout: new Duration(1, TemporalUnit.SECONDS) })
})
```

Everything works as expected now and containers are removed after being stoped. 

Thanks
