### ISSUE TITLE
withCopyDirectoriesToContainer not available

### ISSUE THREAD

**Issue by if-mar** [testcontainers/testcontainers-node#613]
**Expected Behaviour**
In version 9.10.1 there is a function to copy a directory to the container (see https://node.testcontainers.org/features/containers/#with-filesdirectoriescontent)

**Actual Behaviour**
When I just copy the example from the docs, it fails with `Property 'withCopyDirectoriesToContainer' does not exist on type 'GenericContainer'.`

**Steps to Reproduce**
1. Install testcontainers@9.10.1
2. Run example from docs.

**Environment Information**
- Operating System: Win 10
- Docker Version:  20.10.17, build 100c701
- Node version: 16.16.0
- Testcontainers version: 9.10.1

**Comment by cristianrgreco** [comment]
Hi @if-mar, this function has recently been merged but not yet released. The docs reflect what is in `main` and not what's released so apologies for the confusion. This feature will be released soon in 9.11.0.

**Comment by cristianrgreco** [comment]
Version [9.11.0](https://github.com/testcontainers/testcontainers-node/releases/tag/v9.11.0) released
