### ISSUE TITLE
Naming of containers depends on environment

### ISSUE THREAD

**Issue by GoldJns** [testcontainers/testcontainers-node#647]
**Expected Behaviour**
The implicit naming for the testcontainers is the same for ci environment and local environment.

**Actual Behaviour**

`Local Environment`:
When the docker compose environment starts, the container names cosist of the service names in the docker-compose.yml and an additional "-1". Everything works fine.

`Ci Environment`:
Im using azure pipelines.  I get this error:
Error: Cannot get container "frontend-1" as it is not running. After testing i recognized that the container in the ci-environment
is named with  an additional "_1" instead of "-1".

Because of the different naming behaviuor certain steps like the wait strategies are not working because they depend on the  container name. 

**Steps to Reproduce**
1. This is the setup of the docker-compose environment:`
 ```
  test.beforeEach(async ({ page }) => {
        environment = await new DockerComposeEnvironment('playwrightTests', 'docker-compose.yml')
            .withBuild()
            .withWaitStrategy('postgres-1', Wait.forListeningPorts(),)
            .withWaitStrategy('frontend-1',
                Wait.forAll([
                    Wait.forListeningPorts(), Wait.forLogMessage(/start worker processes/)]))
            .withWaitStrategy('api-1', Wait.forListeningPorts())
            .up();
        const frontendPort = environment.getContainer("frontend-1").getMappedPort(8080);
        await page.goto(`http://localhost:${frontendPort}`);
    })`

```
6. Docker compose yml: 
```
version: '3'
services:
    frontend:
        image: my-frontend
        environment:
            DEBUG: testcontainers*
        ports:
            - '8080'
    api:
        image: my-api
        environment:
            ASPNETCORE_ENVIRONMENT: 'Development'
            CONNECTIONSTRINGS__POSTGRES: 'Host=postgres;Username=admin;Password=admin;Database=my-db'
            DEBUG: testcontainers*
        ports:
            - '1234:80'

    postgres:
        image: postgres:14.6
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: my-db
            DEBUG: testcontainers*
        ports:
            - '5432'
```
8.  The docker compose environment starts when running `npx playwright test`, The `test.beforeEach` hook is defined at the top of a playwright testfile

**Environment Information**
- Operating System: Windows 10.0.19045 Build 19045
- Docker Version: 24.0.5, build ced0996
- Node version: 19.9.0
- Testcontainers version: 9.9.1

**Comment by kiview** [comment]
In general, the actual container name should be considered an internal implementation detail and you should not rely on it in other parts of your code. However, you are right that the methods provided by`DockerComposeEnvironment` should abstract this way 👍 

So in your case it means, locally you are using Docker Compose v2, while CI is using Docker Compose v1, correct? As a workaround, I'd strongly suggest to use the same Docker Compose version across environments (either by using v1 locally, or trying to upgrade to v2 on CI).
