### ISSUE TITLE
Throw an exception if GenericContainer.withCmd is unsuccesful?

### ISSUE THREAD

**Issue by jayarjo** [testcontainers/testcontainers-node#65]
If GenericContainer is started with a command and command fails (exits with the error), shouldn't the whole thing throw and exception? 

Doesn't seem to be a case.

**Comment by cristianrgreco** [comment]
No. The exit code is returned to the user and the user can handle it as they wish.

**Comment by jayarjo** [comment]
But amn't I the user? Suppose I'm running:

```javascript
const container = await new GenericContainer("cristianrgreco/testcontainer", "1.1.12")
      .withCmd(["node", "index.js", "one", "two", "three"])
      .withExposedPorts(8080)
      .start();
``` 

And `Cmd` failed. How do I know from inside node application if it doesn't throw?

**Comment by cristianrgreco** [comment]
What if you run a command like `top` which doesn't return? Or something like starting a web server?

**Comment by jayarjo** [comment]
I mean only if command has returned with like obvious error.

**Comment by cristianrgreco** [comment]
Sounds like you want to use `.withHealthCheck()`, which allows you to define whether or not the container is healthy, which retries/intervals/timeouts, etc.

**Comment by jayarjo** [comment]
@cristianrgreco I just realized that what you say means that the fact that one awaits for `start()` method to return before proceeding, doesn't necessarily mean that a command from `withCmd` will be finished by then... is it so @cristianrgreco ?

**Comment by cristianrgreco** [comment]
Yes that's right, `.start()` by default waits for the container ports to be bound. If you want to change this to rely on the result of `.withCmd()`, then use `.withHealthCheck()` as mentioned above.
