### ISSUE TITLE
Question regarding passing arguments

### ISSUE THREAD

**Issue by TieyanFu** [testcontainers/testcontainers-node#658]
**Expected Behaviour**
Referring to the previous [issue](https://github.com/testcontainers/testcontainers-node/issues/202), I'd like to pass also some parameters to a postgres docker container. However, when using the mentioned method, seems the API has changed from "withCmd" to "withCommand", and the results in following error

```
const postgresContainer = new GenericContainer('postgres:14.3-bullseye')
  .withUser('postgres')
  .withEnvironment({
    POSTGRES_PASSWORD: 'example',
    POSTGRES_DB: 'idmp',
  })
  .withExposedPorts(5432)
  //.withSharedMemorySize(1024 * 1024 * 1024)
  .withHealthCheck({
    test: ['CMD-SHELL', 'pg_isready'],
    interval: 5000,
    timeout: 1000,
    retries: 5,
  })
  .withCommand(["...", "-c", "shared_buffers=256MB"])
```
**Actual Behaviour**
...

**Testcontainer Logs**
testcontainers [DEBUG] [e045ff701ce2] Fetching container logs... +1ms
  testcontainers [DEBUG] [e045ff701ce2] Demuxing stream... +4ms
  testcontainers [DEBUG] [e045ff701ce2] Demuxed stream +1ms
  testcontainers [DEBUG] [e045ff701ce2] Fetched container logs +0ms
  testcontainers [DEBUG] [e045ff701ce2] Waiting for container to be ready... +0ms
  testcontainers [DEBUG] [e045ff701ce2] Waiting for health check... +0ms
  testcontainers [DEBUG] [e045ff701ce2] Inspecting container... +0ms
  **testcontainers:containers [e045ff701ce2] /usr/local/bin/docker-entrypoint.sh: line 341: exec: ...: not found +0ms**
  testcontainers [DEBUG] [e045ff701ce2] Inspected container +6ms
  testcontainers [ERROR] [e045ff701ce2] Health check failed: unhealthy +0ms
  testcontainers [ERROR] [e045ff701ce2] Container failed to be ready: Error: Health check failed: unhealthy +0ms
  testcontainers [DEBUG] [e045ff701ce2] Stopping container... +0ms
  testcontainers [DEBUG] [e045ff701ce2] Container already stopped +27ms
  testcontainers [DEBUG] [e045ff701ce2] Removing container... +0ms

**Environment Information**
- Operating System: MacOS 13.5.2
- Docker Version: 4.1.1
- Node version: 
- Testcontainers version: "10.2.1"

**Comment by cristianrgreco** [comment]
Hi @TieyanFu, you are running this command:

```
.withCommand(["...", "-c", "shared_buffers=256MB"])
```

Note the `...`. Docker is returning this error:

```
testcontainers:containers [e045ff701ce2] /usr/local/bin/docker-entrypoint.sh: line 341: exec: ...: not found +0ms
```

Docker is telling you that the binary `...` does not exist, which makes sense
