### ISSUE TITLE
Default to compose v2

### ISSUE THREAD

**Issue by jalaziz** [testcontainers/testcontainers-node#659]
It seems that the current version of `testcontainers` [first attempts to use compose V1, then tries V2](https://github.com/testcontainers/testcontainers-node/blob/73d3a2d73aad62b04d37b9c4e959895a467705a1/packages/testcontainers/src/container-runtime/clients/compose/compose-client.ts#L29-L45).

In environments where both V1 and V2 are installed (e.g. GitHub Actions), this will always default to V1 with no easy option to use the newer version.

Since V1 is deprecated, `testcontainers` should probably default to V2. Alternatively, it would be great if there was a way to override the default.

**Comment by daniel-glazer** [comment]
hey, looks like a good first issue to me.. can I take it? 
can you share a link to the guide on how to contribute? @cristianrgreco
