### ISSUE TITLE
Set minimum nodejs version to 18

### ISSUE THREAD

**Issue by Meir017** [testcontainers/testcontainers-node#666]
Version 16 is not supported anymore, 18 is the LTS version

https://nodejs.org/en/about/previous-releases
![image](https://github.com/testcontainers/testcontainers-node/assets/9786571/fe89d965-9458-488e-9906-caa99c0f7cfe)

**Comment by javierlopezdeancos** [comment]
Part of this issue is resolve on this PR, the CI part https://github.com/testcontainers/testcontainers-node/pull/675
