### ISSUE TITLE
expose inspect result

### ISSUE THREAD

**Issue by jayarjo** [testcontainers/testcontainers-node#67]
I see there's an inspect method buried in the depths of private variables. Why not expose it? Also would be great to have access to the full response rather than very [limited sub-set](https://github.com/testcontainers/testcontainers-node/blob/master/src/container.ts#L11). 

I was looking for a way to retrieve an internal ip of the container on the default bridge network. Might be useful, especially without support for user-defined networks.

**Comment by cristianrgreco** [comment]
It's not exposed because it shouldn't be part of the public API. If you want a way to query internals of a Docker container then something like `dockerode` sounds like a better fit.

**Comment by jayarjo** [comment]
Why not? Knowing internal IP of the container is quite crucial during testing. Isn't it? Potentially I think one could simply use `dockerode` for the whole thing. But that's not the point, right?

**Comment by cristianrgreco** [comment]
The IP of the container is exposed via `getContainerIpAddress()`, as shown in the first example in the README. Whether or not it's internal is irrelevant.

**Comment by jayarjo** [comment]
It is irrelevant only if you support user-defined networks. Otherwise if one requires to launch more than one container - they can't communicate. At least I don't know how.

**Comment by jayarjo** [comment]
I mean if it was user-defined network, then they could communicate through container names (and that feature would become actually useful).

**Comment by cristianrgreco** [comment]
Closing this as this feature is now supported via networks (thanks again @jayarjo)

```javascript
const network = await new Network().start();

const container1 = await new GenericContainer("cristianrgreco/testcontainer", "1.1.12")
  .withName("container1")
  .withNetworkMode(network.getName())
  .start();

const container2 = await new GenericContainer("cristianrgreco/testcontainer", "1.1.12")
  .withName("container2")
  .withNetworkMode(network.getName())
  .start();

const { exitCode } = await container1.exec(["ping", "-c", "3", "container2"]);
```
