### ISSUE TITLE
PostgreSqlContainer cannot be reused without username/password

### ISSUE THREAD

**Issue by yukha-dw** [testcontainers/testcontainers-node#673]
Because `username` and `password` are randomly generated, it's impossible to reuse the container when we don't specify them. In my case, i want to use unsafe parameter `POSTGRES_HOST_AUTH_METHOD=trust`, removing the needs of password. But when i tried to reuse it, `testcontainers` refused.

```js
import { PostgreSqlContainer } from 'testcontainers';

export const createPostgresContainer = async () => {
  process.env.TESTCONTAINERS_RYUK_DISABLED = 'true';
  const postgresContainer = await new PostgreSqlContainer('postgis/postgis:16-3.4')
    .withName('place-postgres-testcontainer')
    .withEnvironment({ POSTGRES_HOST_AUTH_METHOD: 'trust' })
    .withDatabase('test')
    .withUsername('postgres')
    // .withPassword('p455w0r1ddd')
    .withReuse()
    .start();

  return postgresContainer;
};

export const stop = async () => {
  const postgresContainer = await createPostgresContainer();
  await postgresContainer.stop();
};

stop();

```

**Comment by cristianrgreco** [comment]
Hi @yukha-dw, the username/password are hardcoded to `test`, not randomly generated. 

Is there a reason you cannot use `container.getUsername()` / `container.getPassword()` and have to use `POSTGRES_HOST_AUTH_METHOD=trust`? If yes then this isn't supported without adding something like:

```js
  const postgresContainer = await new PostgreSqlContainer('postgis/postgis:16-3.4')
    .withoutAuth()
    .start();
```

But this seems a very uncommon use case.
