### ISSUE TITLE
Debug option to print log output of compose containers

### ISSUE THREAD

**Issue by jalaziz** [testcontainers/testcontainers-node#685]
**Expected Behaviour**

When using `DEBUG="testcontainers*"`, `DEBUG=testcontainers:containers`, or `DEBUG=testcontainers:compose` we should see the output of containers started via Docker Compose.

**Actual Behaviour**

Compose build and higher-level logs are printed, but container logs are not. This is particularly annoying when trying to debug why a container is failing to start. The logs will indicate that the container failed to start, but won't print any logs from the container.

**Testcontainer Logs**
...

**Steps to Reproduce**
1. Create a docker compose setup with a container that fails to start
2. Start docker compose environment with `DockerComposeEnvironment(composeFilePath, fileName).up();`
3. Observe the lack of container logs

**Environment Information**
- Operating System: Linux
- Docker Version: 24.0.7
- Node version: 16
- Testcontainers version: 10.2.1

**Comment by cristianrgreco** [comment]
Sounds like a great addition, thanks for raising @jalaziz

**Comment by wimdeblauwe** [comment]
+1 for this.

**Comment by cristianrgreco** [comment]
PR welcome

**Comment by cristianrgreco** [comment]
This is already supported

**Comment by jalaziz** [comment]
@cristianrgreco maybe I'm missing something, but where is this supported? Or was it a recent addition?

**Comment by cristianrgreco** [comment]
Logs from compose itself can be enabled with `DEBUG=testcontainers:compose`. Logs from the containers upped by compose can be enabled with `DEBUG=testcontainers:containers`: https://github.com/testcontainers/testcontainers-node/blob/824cd8dbac0615ae00a83d82e8625a108b885ecb/packages/testcontainers/src/docker-compose-environment/docker-compose-environment.ts#L143-L147

**Comment by jalaziz** [comment]
Ahh indeed. I now see the issue we are facing on occasion.

Container logs do work, but _only_ after all containers have started successfully.

The issue we have been facing is that when a container fails to start for some reason and compose fails (due to a wait strategy or a `service_healthy` condition), no container logs are printed, making it very difficult to debug start up issues.
