### ISSUE TITLE
[Documentation] Improve `testcontainers-node` Colima setup docs

### ISSUE THREAD

**Issue by wujekbogdan** [testcontainers/testcontainers-node#689]
- Go has [such a section](https://golang.testcontainers.org/system_requirements/using_colima/)
- Java [has such a section too](https://java.testcontainers.org/supported_docker_environment/#colima)

However, there's nothing for `testcontainers-node`. I finally managed to set up Colima using the Java documentation, but it's not the most obvious place to look. Additionally, it doesn't rank high in Google search results, making the documentation harder to find for `testcontainers-node` users.

By the way, I'm not even sure if each tech stack needs its own Colima setup page. This information is quite generic and could potentially be moved elsewhere.

**Comment by cristianrgreco** [comment]
Hi @wujekbogdan, there is an entire top-level page called "supported container runtimes" in the testcontainers-node docs: https://node.testcontainers.org/supported-container-runtimes/

**Comment by wujekbogdan** [comment]
@cristianrgreco 

I'm afraid this documentation isn't complete. 

The solution for the _"Failed to connect to Reaper"_ error is the following, according to the docs:

``` sh
export NODE_OPTIONS=--dns-result-order=ipv4first
```

whereas, setting:

``` yml
network:
  address: true
```

together with:

``` sh
export TESTCONTAINERS_HOST_OVERRIDE=$(colima ls -j | jq -r '.address')
```

also works.
