### ISSUE TITLE
testcontainers-node creates lots of docker images and doesn't clean after itself

### ISSUE THREAD

**Issue by jayarjo** [testcontainers/testcontainers-node#69]
testcontainers-node has flooded my docker with these images:

![Screen Shot 2020-04-21 at 8 24 00 PM](https://user-images.githubusercontent.com/150075/79888837-44fc1080-840e-11ea-84f3-8fb799d92b15.png)

I don't even remember running jest test or anything, so not sure how this might have happened.

**Comment by jayarjo** [comment]
Ok, I get now how this happened - husky triggered tests on commit and that's how these were created. Still an issue, IMHO.

**Comment by cristianrgreco** [comment]
@jayarjo Each test will remove the container it created, perhaps it doesn't if a test fails? Would you be able to reproduce the issue and provide some more info?

**Comment by cristianrgreco** [comment]
Fixed in 2.9.0.
