### ISSUE TITLE
Wait strategy is always overwritten on start

### ISSUE THREAD

**Issue by thake** [testcontainers/testcontainers-node#711]
**Expected Behaviour**
A manually set wait strategy won't be overwritten on start.

**Actual Behaviour**
On start, a manually set the wait strategy will be overwritten with `withWaitStrategy(testcontainers_1.Wait.forLogMessage("Ready", 1))`.

**Comment by cristianrgreco** [comment]
Hi @thake, not sure what you mean here, could you give a code example showing the problem?

**Comment by thake** [comment]
One example:
```javascript
const container = await new LocalstackContainer()
    ..withWaitStrategy(Wait.forLogMessage('<<<Bootstrapping localstack complete>>>'))
    .start();
```
I would expect that the passed wait strategy will be respected, but instead, it will be overridden on `start()` with `withWaitStrategy(testcontainers_1.Wait.forLogMessage("Ready", 1))`.
