### ISSUE TITLE
Host expose ports is not supported

### ISSUE THREAD

**Issue by polaroi8d** [testcontainers/testcontainers-node#72]
I would like to expose for example MySQL container ports, how can I define the container host ports? There is a function like in the Java package called `.withFixedExposedPort(3306, 3306)` where I can define the host and the container ports?

**Comment by cristianrgreco** [comment]
Hi @polaroi8d , I have been asked by the Java team not to provide this functionality, instead users should work with random ports. Refer to this blog post for more info: https://bsideup.github.io/posts/testcontainers_fixed_ports/

**Comment by polaroi8d** [comment]
Hy @cristianrgreco, thanks for the post. I learned it now and try to do it with random ports. Thanks again!
