### ISSUE TITLE
Healthchecks seem to have a hard timeout of 60,000ms (60s)

### ISSUE THREAD

**Issue by rathboma** [testcontainers/testcontainers-node#721]
Hey all!

First - this project is amazing.

I'm having a problem with a test oracle database that I have to bootstrap with lots of stuff. Here's my definition:

```js
    container = await new GenericContainer('gvenzl/oracle-xe:18')
      .withName('oracle')
      .withEnv("ORACLE_PASSWORD", 'password')
      .withEnv('ORACLE_DATABASE', 'beekeeper')
      .withEnv('APP_USER', 'beekeeper')
      .withEnv('APP_USER_PASSWORD', 'password')
      .withExposedPorts(1521)
      .withBindMount(localDir, '/docker-entrypoint-initdb.d', 'ro')
      .withHealthCheck({
        test: "sqlplus -s beekeeper/password@//localhost/BEEKEEPER <<< \"select * from actor;\" | grep 'no rows'",
        interval: 10000,
        timeout: 10000,
        retries: 12, // 2 minutes
        startPeriod: 60000
      })
      .withWaitStrategy(Wait.forHealthCheck())
      .start()

```

This constantly times out with a messaging saying `healthcheck not healthy after 60000ms`, even though I've set much more generous health check options.

Hoping you can help?

Using testcontainers 8.9.0

**Comment by cristianrgreco** [comment]
Hey @rathboma , thanks for the kind words! You'll need to set `withStartupTimeout(120000)` on the container as well. The health check config is separate from the container startup config, although I've noted in this case that's not intuitive

**Comment by rathboma** [comment]
AAAAH yes you're right. I was confused because the message mentioned `healthcheck`, so I was hyper focused on that syntax.

Thanks!
