### ISSUE TITLE
Restarting a container reusing the same port fails with 'port is already allocated'

### ISSUE THREAD

**Issue by esmiralha** [testcontainers/testcontainers-node#724]
**Expected Behaviour**
- Start a container x1
- Get the mapped host port y
- stop container x1
- start container x2 reusing mapped port y
- container x2 is started and port y is exposed

**Actual Behaviour**
- Start a container x1
- Get the mapped host port y
- stop container x1
- start container x2 reusing mapped port y
- start command fails with '(HTTP code 500) server error - driver failed programming external connectivity on endpoint unruffled_moser (a9e76ec2df217d4634381a201b2a3b15c238f8ae4ecf421cc79342b0745e47d6): Bind for :::33291 failed: port is already allocated’

**Environment Information**
- Operating System: Mac OS Sonoma
- Docker Version: 25.0.2
- Node version: 18.19.0
- Testcontainers version: 10.7.2

**Comment by cristianrgreco** [comment]
> start container x2 reusing mapped port y

Ports are allocated dynamically and so may change between container restarts. Don't store the mapped port, get it again after the container restarts.

**Comment by esmiralha** [comment]
First, thanks for the prompt response.

I understand your point, but, let me explain my use case. I want to do a resilience test with rabbitmq consumers that tests consumer recovery after a rabbitmq restart. If I just restart the container and let it map a new port, the consumers won't recover properly because the port is part of the startup environment.

So, I got the mapped port, stored it and then asked the container to reuse it when restarted. I expected the port to be unbound when the container is stopped and then rebound when restarted. But it does not work like that, apparently.

Thank for any help you can throw my way!

**Comment by cristianrgreco** [comment]
Hi @esmiralha, yep I understand the use case. 

By default when you stop/restart a container via Testcontainers, we set an implicit timeout of `0`, which basically means "do not bother blocking the code waiting for the container to stop". In your case it's possible that the container is still running when you try to start it again on the same port. 

You should be able to set a timeout to give time for the existing container to stop `container.restart({ timeout: 60000 })`. Note that this waits until _either_ the container stops, or 60s have elapsed.

For resiliency testing, I'd highly recommend something like ToxiProxy, which lets you simulate all kinds of issues (connectivity, latency, etc), without having to physically restart containers.

**Comment by esmiralha** [comment]
One last question, the restart operation will reuse the same port previously exposed or expose a new random port? If the latter is true, then I believe I will be in the same situation as before. Is it possible to add a parameter to restart like `reuseHostPort: boolean` and make the container expose the same host port on restart?

**Comment by cristianrgreco** [comment]
The latter is true. Something like `reuseHostPort` doesn't exist. If you need control over the port you can set it yourself:

```js
.withExposedPorts({ container: 80, host: 8080 })
```

Then you can skip using `getMappedPort(80)` as it'll always be `8080`, even if the container restarts.

**Comment by esmiralha** [comment]
Crap on my side, obviously! Closing the issue.
Thanks for the prompt help, @cristianrgreco !
