### ISSUE TITLE
Support OneShotStartupCheckStrategy like testcontainers-java

### ISSUE THREAD

**Issue by omerlh** [testcontainers/testcontainers-node#731]
Hey!
Very happy users of testcontainers here :) We have a use case where we need something similar to [`OneShotStartupCheckStrategy`](https://java.testcontainers.org/features/startup_and_waits/#one-shot-startup-strategy-example) that test containers java supports. 
It is pretty easy to implement it ourselves using `StartupCheckStrategy` but I am also happy contribute the code back to the library so others could use it as well.

While trying to write and test for it I am getting weird error:
```
Container runtime strategy "UnixSocketStrategy" does not work TypeError: dockerode.info is not a function 
```

I added the exception to find out why my tests are not passing and this is the additional string on the error. Happens both locally and when running on codespaces. What am I a doing wrong? I would like help so I could open a pull request - i pushed my (not working changes) to a branch - #730.

**Comment by cristianrgreco** [comment]
Hey @omerlh, thanks for contributing! I'll reply with feedback on the PR on the PR itself

**Comment by cristianrgreco** [comment]
Added in https://github.com/testcontainers/testcontainers-node/pull/730
