### ISSUE TITLE
Use a Kafka container

### ISSUE THREAD

**Issue by marcelo-turrin** [testcontainers/testcontainers-node#74]
Hi great library thanks for it.
Does it support to run a kafka server?
I tried a basic generic container  but probably I don't understand how to do it correctly.

Thanks in advance for you answer.

**Comment by polaroi8d** [comment]
Hello @marcelo-turrin you can use any type of container. There is a bunch of example in the readme. For example, I am using a latest MySQL image.

```
const mysqlContainer = await new GenericContainer('mysql', 'latest')
nv('MYSQL_USER', MYSQL_USER)
      .start()
```

**Comment by jayarjo** [comment]
@marcelo-turrin check if this helps: https://www.testcontainers.org/modules/kafka/

**Comment by cristianrgreco** [comment]
HI @marcelo-turrin , were you able to get the help you needed?

**Comment by katerina-semikina** [comment]
@cristianrgreco Hi! Seems like currently there is no easy way to create a Kafka container.
First of all, zookeeper and Kafka need to be in a network to communicate (luckily, custom network creation was released recently). 

Second, we need to provide environment variable with advertised listeners to Kafka, which contains port accessible from host (mapped port). In java implementation for Kafka container they set advertised listeners in "containerIsStarting" method which is called after ports are bound but before container starts: [KafkaContainer.java#L125](https://github.com/testcontainers/testcontainers-java/blob/master/modules/kafka/src/main/java/org/testcontainers/containers/KafkaContainer.java#L125).

Please, could you let me know if there is an option to provide bound port to env variables for container? Or is it something that needs contributing? Thanks!

**Comment by jayarjo** [comment]
@katerina-semikina I can tell you that there's none, I specifically had discussion with maintainers of Java version about letting me implement ability to specify a port to map to directly (since they have that method) and they quite aggressively told me that I shouldn't, they even have a big blog article about why that is a very bad idea and they like to link it to everybody 😄

@cristianrgreco also rejected my PR, I believe following the principles in that article.

In my fork I have it implemented though, since it's an essential feature and I think it's not the kind of thing they should decide for us.

**Comment by jayarjo** [comment]
@katerina-semikina у них так кстати какой-то русский там верховодит, спроси лично его, вдруг девичья просьба растопит его очерствевшее сердце 😄

**Comment by katerina-semikina** [comment]
> @katerina-semikina I can tell you that there's none, I specifically had discussion with maintainers of Java version about letting me implement ability to specify a port to map to directly (since they have that method) and they quite aggressively told me that I shouldn't, they even have a big blog article about why that is a very bad idea and they like to link it to everybody 😄
> 
> @cristianrgreco also rejected my PR, I believe following the principles in that article.
> 
> In my fork I have it implemented though, since it's an essential feature and I think it's not the kind of thing they should decide for us.

Yeah, I've read those article and mostly I agree, except such cases as Kafka containers. If testcontainers stick to random ports approach, it's okay, as long as it can be implemented in a way similar to java Kafka container, which I may try. Anyway, I think it is an important feature.

**Comment by jayarjo** [comment]
> it's okay, as long as it can be implemented in a way similar to java Kafka container

I suspect that the only reason they can support that way is because they have a method to map the port to predefined value in first place.

Happy to be corrected, if that's not the case.

**Comment by katerina-semikina** [comment]
> > it's okay, as long as it can be implemented in a way similar to java Kafka container
> 
> I suspect that the only reason they can support that way is because they have a method to map the port to predefined value in first place.
> 
> Happy to be corrected, if that's not the case.

There is a method, where environment variables are exported after ports are bound, but before container starts. That's why it is possible.

**Comment by jayarjo** [comment]
> There is a method, where environment variables are exported after ports are bound, but before container starts. That's why it is possible.

Exported to where? Don't you need the final value of the port in the host system? Can you link that method?

**Comment by cristianrgreco** [comment]
Hi @katerina-semikina, were you able to get this working?

**Comment by katerina-semikina** [comment]
Hi @cristianrgreco, yes, thank you for releasing. I was able to successfully create Kafka test container.

**Comment by cristianrgreco** [comment]
@katerina-semikina That's great! I don't suppose you could share some code to help @marcelo-turrin? :slightly_smiling_face:

**Comment by cristianrgreco** [comment]
@katerina-semikina Just following up in case you missed my last message. If not I'll look at doing this over the next few days

**Comment by katerina-semikina** [comment]
@cristianrgreco sorry for delay. Yes, I'll prepare an example soon.

**Comment by katerina-semikina** [comment]
@cristianrgreco @marcelo-turrin I provided an example with possible way to create Kafka container here: https://github.com/katerina-semikina/node-examples/blob/master/src/__tests__/KafkaTestContainer.ts

**Comment by cristianrgreco** [comment]
Thanks @katerina-semikina

**Comment by cristianrgreco** [comment]
@katerina-semikina Do you have any feedback for this PR? https://github.com/testcontainers/testcontainers-node/pull/102
It's mostly based off your example and I've added support to use a built-in ZK and removed the need for clients to provide ports.

**Comment by katerina-semikina** [comment]
> @katerina-semikina Do you have any feedback for this PR? #102
> It's mostly based off your example and I've added support to use a built-in ZK and removed the need for clients to provide ports.

For me it looks really good 👍

**Comment by cristianrgreco** [comment]
This is now available in 3.0.0. Documentation on how to use the new Kafka module is here: https://github.com/testcontainers/testcontainers-node/tree/master/src/modules/kafka

Big thanks again to @katerina-semikina 

If there are any problems please raise a new issue :slightly_smiling_face:

**Comment by omerlh** [comment]
Did someone got it working? I am trying to connect to Kafka from another container, having the same shared network, but the advertised broker is the localhost one...

**Comment by katerina-semikina** [comment]
> https://github.com/testcontainers/testcontainers-node/tree/master/src/modules/kafka

Hi Omer, yes, it should work fine. 

It may be a bit tricky when using another container which is trying to get advertised listeners in the same network. For me it works for schema registry container just fine (in testcontainers@7.24.0). 

Could you provide more details please?

**Comment by cristianrgreco** [comment]
@omerlh could you please share a reproducible example using the latest version of testcontainers?

**Comment by omerlh** [comment]
I got it to work by following this [post](https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/). I am not sure what is the difference exactly (some code is borrowed from testcontainers kafka), but the important part is setting both addressess.
```
const network = await new Network().start();

  const zookeeperContainer = await new GenericContainer('confluentinc/cp-zookeeper:7.0.1')
    .withExposedPorts(2181)
    .withNetworkMode(network.getName())
    .withNetworkAliases('zookeeper')
    .withEnv('ZOOKEEPER_CLIENT_PORT', '2181')
    .start();

  const kafkaContainer = await new GenericContainer('confluentinc/cp-kafka:7.0.1')
    .withExposedPorts(19092)
    .withNetworkMode(network.getName())
    .withNetworkAliases('kafka')
    .withEnv('KAFKA_ADVERTISED_LISTENERS', 'PLAINTEXT://kafka:9093,CONNECTIONS_FROM_HOST://localhost:19092')
    .withEnv('KAFKA_LISTENER_SECURITY_PROTOCOL_MAP', 'PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT')
    .withEnv('KAFKA_ZOOKEEPER_CONNECT', 'zookeeper:2181')
    .withEnv('KAFKA_INTER_BROKER_LISTENER_NAME', 'PLAINTEXT')
    .withEnv('KAFKA_BROKER_ID', '1')
    .withEnv('KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR', '1')
    .withEnv('KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS', '1')
    .withEnv('KAFKA_TRANSACTION_STATE_LOG_MIN_ISR', '1')
    .withEnv('KAFKA_LOG_FLUSH_INTERVAL_MESSAGES', '9223372036854775807')
    .withEnv('KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS', '0')
    .withEnv('KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE', 'false')
    .start();

  const { output, exitCode } = await kafkaContainer.exec([
    'kafka-configs',
    '--alter',
    '--bootstrap-server',
    'kafka:9093',
    '--entity-type',
    'brokers',
    '--entity-name',
    '1',
    '--add-config',
    `advertised.listeners=[PLAINTEXT://kafka:9093,CONNECTIONS_FROM_HOST://localhost:${kafkaContainer.getMappedPort(19092)}]`,
  ]);
 ```

**Comment by katerina-semikina** [comment]
> I got it to work by following this [post](https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/). I am not sure what is the difference exactly (some code is borrowed from testcontainers kafka), but the important part is setting both addresseses.
> 
> ```
> const network = await new Network().start();
> 
>   const zookeeperContainer = await new GenericContainer('confluentinc/cp-zookeeper:7.0.1')
>     .withExposedPorts(2181)
>     .withNetworkMode(network.getName())
>     .withNetworkAliases('zookeeper')
>     .withEnv('ZOOKEEPER_CLIENT_PORT', '2181')
>     .start();
> 
>   const kafkaContainer = await new GenericContainer('confluentinc/cp-kafka:7.0.1')
>     .withExposedPorts(19092)
>     .withNetworkMode(network.getName())
>     .withNetworkAliases('kafka')
>     .withEnv('KAFKA_ADVERTISED_LISTENERS', 'PLAINTEXT://kafka:9093,CONNECTIONS_FROM_HOST://localhost:19092')
>     .withEnv('KAFKA_LISTENER_SECURITY_PROTOCOL_MAP', 'PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT')
>     .withEnv('KAFKA_ZOOKEEPER_CONNECT', 'zookeeper:2181')
>     .withEnv('KAFKA_INTER_BROKER_LISTENER_NAME', 'PLAINTEXT')
>     .withEnv('KAFKA_BROKER_ID', '1')
>     .withEnv('KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR', '1')
>     .withEnv('KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS', '1')
>     .withEnv('KAFKA_TRANSACTION_STATE_LOG_MIN_ISR', '1')
>     .withEnv('KAFKA_LOG_FLUSH_INTERVAL_MESSAGES', '9223372036854775807')
>     .withEnv('KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS', '0')
>     .withEnv('KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE', 'false')
>     .start();
> 
>   const { output, exitCode } = await kafkaContainer.exec([
>     'kafka-configs',
>     '--alter',
>     '--bootstrap-server',
>     'kafka:9093',
>     '--entity-type',
>     'brokers',
>     '--entity-name',
>     '1',
>     '--add-config',
>     `advertised.listeners=[PLAINTEXT://kafka:9093,CONNECTIONS_FROM_HOST://localhost:${kafkaContainer.getMappedPort(19092)}]`,
>   ]);
> ```

Actually that's how the version I use work (7.24.0) - I have both addresses.

**Comment by omerlh** [comment]
Weird, I moved to other task for now, but I'll try to investigate it again, i spent a lot of time on it yesterday and gave up at some point...
