### ISSUE TITLE
"Cannot find module" error on usage of of "KafkaContainer" with v10.8.0

### ISSUE THREAD

**Issue by FroYo425** [testcontainers/testcontainers-node#744]
**Expected Behaviour**
All modules are found and imported correctly.

**Actual Behaviour**
On creation of a new KafkaContainer the error "Cannot find module 'testcontainers/src/wait-strategies/wait-for-container' from '../../node_modules/@testcontainers/kafka/build/kafka-container.js'" occurs. This occurred with v10.8.0.

Probably, the problem is that there are these lines in the "kafka-container.js" file:
```
const wait_for_container_1 = require("testcontainers/src/wait-strategies/wait-for-container");
const bound_ports_1 = require("testcontainers/src/utils/bound-ports");
```
This tries to access the "src" folder in the "testcontainers" package but there is only a "build" folder.

**Comment by cristianrgreco** [comment]
Fixed in 10.8.1
