### ISSUE TITLE
Not supported ImagePullPolicy()

### ISSUE THREAD

**Issue by polaroi8d** [testcontainers/testcontainers-node#75]
It would be nice if the node version of test containers will be supporting the `.withImagePullPolicy()` feature.

**Comment by jayarjo** [comment]
I think there should a way to instantiate a container with raw full config in first place. Simplification is good for many cases, but then there are some  cases that fall out of such and there's no go for that in TestContainers @cristianrgreco

**Comment by cristianrgreco** [comment]
Hi @polaroi8d, could you elaborate a bit more on what you mean by image pull policy? I wasn't aware Docker had such a feature

**Comment by polaroi8d** [comment]
Sorry @cristianrgreco for a late answer. I would like to use as in the Java lib has this feature. Is it implemented or why are you closed the "feature request".

**Comment by cristianrgreco** [comment]
Hi @polaroi8d, no problem. I've raised a PR, if you're able to review that it provides what you need then please do, if not I'll merge it in a couple of days.

**Comment by polaroi8d** [comment]
@cristianrgreco  Thank you, it looks good to me. 

Releated PR opened by Cristian #93

**Comment by cristianrgreco** [comment]
Thanks @polaroi8d, it's available now in 2.15.0
