### ISSUE TITLE
Cannot install redpanda module from npm

### ISSUE THREAD

**Issue by kashive** [testcontainers/testcontainers-node#760]
**Expected Behaviour**
Able to install redpanda module with `npm install @testcontainers/redpanda --save-dev` as per [docs](https://node.testcontainers.org/modules/redpanda/)

**Actual Behaviour**
```
@testcontainers/redpanda is not in the npm registry, or you have no permission to fetch it.
```

**Comment by cristianrgreco** [comment]
Released in 10.9.0
