### ISSUE TITLE
Could not find a working container runtime strategy

### ISSUE THREAD

**Issue by ahmed-deftoner** [testcontainers/testcontainers-node#768]
**Expected Behaviour**
Postgres Container should start

**Actual Behaviour**
Postgres Container did not start

**Testcontainer Logs**
Error: Jest: Got error running globalSetup - C:\Users\carbo\Projects\twin-premium-api\Tests\Integration\setup.ts, reason: Could not find a working container runtime strategy
    at getContainerRuntimeClient (C:\Users\carbo\Projects\twin-premium-api\node_modules\testcontainers\build\container-runtime\clients\client.js:64:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgreSqlContainer.start (C:\Users\carbo\Projects\twin-premium-api\node_modules\testcontainers\build\generic-container\generic-container.js:54:24)
    at async PostgreSqlContainer.start (C:\Users\carbo\Projects\twin-premium-api\node_modules\@testcontainers\postgresql\build\postgresql-container.js:34:47)
    at async initPostgres (C:\Users\carbo\Projects\twin-premium-api\Tests\Integration\setup.ts:12:22)
    at async Promise.all (index 0)
    at async init (C:\Users\carbo\Projects\twin-premium-api\Tests\Integration\setup.ts:7:5)
    at async C:\Users\carbo\Projects\twin-premium-api\node_modules\@jest\core\build\runGlobalHook.js:109:13       
    at async waitForPromiseWithCleanup (C:\Users\carbo\Projects\twin-premium-api\node_modules\@jest\transform\build\ScriptTransformer.js:160:5)
    at async ScriptTransformer.requireAndTranspileModule (C:\Users\carbo\Projects\twin-premium-api\node_modules\@jest\transform\build\ScriptTransformer.js:808:16)

**Steps to Reproduce**
1. Windows but ran tests in WSL2
2. Docker version 24.0.7 and NodeJS version v20.12.1
3. npx jest --config ./src/Tests/Integration/it.jest.json src/Tests/Integration/Agency/agency.it.spec.ts
4. Error: Jest: Got error running globalSetup - C:\Users\carbo\Projects\twin-premium-api\Tests\Integration\setup.ts, reason: Could not find a working container runtime strategy

**Environment Information**
- Operating System: Windows Subsystem For Linux
- Docker Version: 24.0.7
- Node version: v20.12.1
- Testcontainers version: ^10.9.0

**Comment by kiview** [comment]
What is MSW?

Did you execute the tests as a WSL process? This path here `C:\Users\carbo\Projects\twin-premium-api\Tests\Integration\setup.ts, reason: Could not find a working container runtime strategy` looks like a Windows process, there will not be an OOTB integration between the Windows host and Docker within WSL if Docker Desktop is not used.

**Comment by ahmed-deftoner** [comment]
> What is MSW?
> 
> Did you execute the tests as a WSL process? This path here `C:\Users\carbo\Projects\twin-premium-api\Tests\Integration\setup.ts, reason: Could not find a working container runtime strategy` looks like a Windows process, there will not be an OOTB integration between the Windows host and Docker within WSL if Docker Desktop is not used.

I run docker on WSL, and I executed all the commands on WSL and not Windows, but you're right, the path seems different, I'll verify it again though

**Comment by cristianrgreco** [comment]
Please reopen the issue if it persists

**Comment by rudemex** [comment]
I'm having this problem in my GitLab pipelines with v10.9 and v10.10, and with debuguer I can't find the problem

**Comment by zotijs** [comment]
Same here in Gitlab, using the following job configuration:

```
test:
  stage: test
  extends: .test_application
  services:
    - name: docker:dind
      alias: docker
      # explicitly disable tls to avoid docker startup interruption
      command: ['--tls=false']
  variables:
    DOCKER_HOST: 'tcp://docker:2375'
    DOCKER_TLS_CERTDIR: ''
    DEBUG: testcontainers*
  only:
    - merge_requests
```

I am getting `Could not find a working container runtime strategy` when I am trying to start the testcontainer in jest's `globalSetup`
```

**Comment by Vindexus** [comment]
> Same here in Gitlab, using the following job configuration:
> 
> ```
> test:
>   stage: test
>   extends: .test_application
>   services:
>     - name: docker:dind
>       alias: docker
>       # explicitly disable tls to avoid docker startup interruption
>       command: ['--tls=false']
>   variables:
>     DOCKER_HOST: 'tcp://docker:2375'
>     DOCKER_TLS_CERTDIR: ''
>     DEBUG: testcontainers*
>   only:
>     - merge_requests
> ```
> 
> I am getting `Could not find a working container runtime strategy` when I am trying to start the testcontainer in jest's `globalSetup`
> 
> Debug print:
> 
> ```
> 2024-06-21T14:39:33.532Z testcontainers [DEBUG] Testing container runtime strategy "TestcontainersHostStrategy"...
> 2024-06-21T14:39:33.534Z testcontainers [DEBUG] Found custom configuration: dockerHost: "tcp://docker:2375"
> 2024-06-21T14:39:33.534Z testcontainers [DEBUG] Testing container runtime strategy "ConfigurationStrategy"...
> 2024-06-21T14:39:33.563Z testcontainers [DEBUG] Container runtime strategy "ConfigurationStrategy" does not work
> 2024-06-21T14:39:33.563Z testcontainers [DEBUG] Testing container runtime strategy "UnixSocketStrategy"...
> 2024-06-21T14:39:33.563Z testcontainers [DEBUG] Testing container runtime strategy "RootlessUnixSocketStrategy"...
> 2024-06-21T14:39:33.564Z testcontainers [DEBUG] Testing container runtime strategy "NpipeSocketStrategy"...
> ```
> 
> More details:
> 
> * the runner is a docker executor
> * the image of the test is node alpine

Did you ever figure out this issue?

**Comment by zotijs** [comment]
> > Same here in Gitlab, using the following job configuration:
> > ```
> > test:
> >   stage: test
> >   extends: .test_application
> >   services:
> >     - name: docker:dind
> >       alias: docker
> >       # explicitly disable tls to avoid docker startup interruption
> >       command: ['--tls=false']
> >   variables:
> >     DOCKER_HOST: 'tcp://docker:2375'
> >     DOCKER_TLS_CERTDIR: ''
> >     DEBUG: testcontainers*
> >   only:
> >     - merge_requests
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am getting `Could not find a working container runtime strategy` when I am trying to start the testcontainer in jest's `globalSetup`
> > Debug print:
> > ```
> > 2024-06-21T14:39:33.532Z testcontainers [DEBUG] Testing container runtime strategy "TestcontainersHostStrategy"...
> > 2024-06-21T14:39:33.534Z testcontainers [DEBUG] Found custom configuration: dockerHost: "tcp://docker:2375"
> > 2024-06-21T14:39:33.534Z testcontainers [DEBUG] Testing container runtime strategy "ConfigurationStrategy"...
> > 2024-06-21T14:39:33.563Z testcontainers [DEBUG] Container runtime strategy "ConfigurationStrategy" does not work
> > 2024-06-21T14:39:33.563Z testcontainers [DEBUG] Testing container runtime strategy "UnixSocketStrategy"...
> > 2024-06-21T14:39:33.563Z testcontainers [DEBUG] Testing container runtime strategy "RootlessUnixSocketStrategy"...
> > 2024-06-21T14:39:33.564Z testcontainers [DEBUG] Testing container runtime strategy "NpipeSocketStrategy"...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > More details:
> > 
> > * the runner is a docker executor
> > * the image of the test is node alpine
> 
> Did you ever figure out this issue?

Hello, sorry for the late response, basically it depends on how a runner is configured, but this is what worked for us:

```
  services:
    - name: docker:dind
      # explicitly disable tls to avoid docker startup interruption
      command: ['--tls=false']
  tags:
    - dind
  variables:
    DOCKER_HOST: 'unix:///var/run/docker.sock'
    DOCKER_TLS_CERTDIR: ''
    DOCKER_DRIVER: overlay2
    DEBUG: $DEBUG_TEST_CONTAINERS

```

**Comment by cristianrgreco** [comment]
The problem seems introduced by `"@mswjs/interceptors": "0.37.6"`, things worked fine with `0.37.5`.

In my case using msw 2.7.3 which requires `"@mswjs/interceptors": "^0.37.0"`, I just updated the `package-lock.json` from 0.37.6 -> 0.37.5, which solved my issue:

```
"node_modules/msw": {
  "version": "2.7.3",
  "resolved": "https://registry.npmjs.org/msw/-/msw-2.7.3.tgz",
  ...
  "dependencies": {
    ...
    "@mswjs/interceptors": "^0.37.0",
    ...
  },
  ...
}
```

```
"node_modules/@mswjs/interceptors": {
  "version": "0.37.5",
  "resolved": "https://registry.npmjs.org/@mswjs/interceptors/-/interceptors-0.37.5.tgz",
  "integrity": "sha512-AAwRb5vXFcY4L+FvZ7LZusDuZ0vEe0Zm8ohn1FM6/X7A3bj4mqmkAcGRWuvC2JwSygNwHAAmMnAI73vPHeqsHA==",
  "dev": true,
  "license": "MIT",
  "dependencies": {
    "@open-draft/deferred-promise": "^2.2.0",
    "@open-draft/logger": "^0.3.0",
    "@open-draft/until": "^2.0.0",
    "is-node-process": "^1.2.0",
    "outvariant": "^1.4.3",
    "strict-event-emitter": "^0.5.1"
  },
  "engines": {
    "node": ">=18"
  }
}
```

**Comment by satanshiro** [comment]
> The problem seems introduced by `"@mswjs/interceptors": "0.37.6"`, things worked fine with `0.37.5`.
> 
> In my case using msw 2.7.3 which requires `"@mswjs/interceptors": "^0.37.0"`, I just updated the `package-lock.json` from `0.37.6` -> `0.37.5`, which solved my issue:
> 
> ```
> "node_modules/msw": {
>   "version": "2.7.3",
>   "resolved": "https://registry.npmjs.org/msw/-/msw-2.7.3.tgz",
>   ...
>   "dependencies": {
>     ...
>     "@mswjs/interceptors": "^0.37.0",
>     ...
>   },
>   ...
> }
> ```
> 
> ```
> "node_modules/@mswjs/interceptors": {
>   "version": "0.37.5",
>   "resolved": "https://registry.npmjs.org/@mswjs/interceptors/-/interceptors-0.37.5.tgz",
>   "integrity": "sha512-AAwRb5vXFcY4L+FvZ7LZusDuZ0vEe0Zm8ohn1FM6/X7A3bj4mqmkAcGRWuvC2JwSygNwHAAmMnAI73vPHeqsHA==",
>   "dev": true,
>   "license": "MIT",
>   "dependencies": {
>     "@open-draft/deferred-promise": "^2.2.0",
>     "@open-draft/logger": "^0.3.0",
>     "@open-draft/until": "^2.0.0",
>     "is-node-process": "^1.2.0",
>     "outvariant": "^1.4.3",
>     "strict-event-emitter": "^0.5.1"
>   },
>   "engines": {
>     "node": ">=18"
>   }
> }
> ```

a cleaner temporary solution is to add the following in package json
```js
  "overrides": {
    "msw": {
      "@mswjs/interceptors": "0.37.5"
    }
  }
```

**Comment by cristianrgreco** [comment]
> a cleaner temporary solution is to add the following in package json
> 
>   "overrides": {
>     "msw": {
>       "@mswjs/interceptors": "0.37.5"
>     }
>   }

That'd be ideal. I tried setting the overrides and it just wouldn't work 🤷
