### ISSUE TITLE
How can I view container logs?

### ISSUE THREAD

**Issue by rhyek** [testcontainers/testcontainers-node#79]
Hi. I'm running two test containers during my integration tests using Jest. One is based on postgres and the other is for a migrations app based on a local Dockerfile. They both seem to be running correctly, but I would like to see their output (STDOUT) and it is not clear to me from the documentation how I can do this.

`DEBUG=testcontainers` only outputs docker image build and container creation.

`withDefaultLogDriver` has no effect.

**Comment by cristianrgreco** [comment]
Hi @rhyek, this is currently not supported, though should be easy to implement as we already check container logs for startup

**Comment by rhyek** [comment]
Great. Yeah, turns out my containers aren't actually running correctly and it's not immediately clear to me how to debug them right now aside from starting them outside my test suite.

**Comment by cristianrgreco** [comment]
You could not run the code that shuts down the container/breakpoint before it and run docker logs via the CLI?

**Comment by rhyek** [comment]
Perfect. I'll try that, thanks. It would still be beneficial to have this functionality within the tool as the logs could help out during CI failure debugging.

**Comment by cristianrgreco** [comment]
@rhyek As of 2.9.0 you can now stream container logs:

```javascript
const { GenericContainer } = require("testcontainers");

const container = await new GenericContainer("alpine")
  .start();

const stream = await container.logs();
stream
    .on("data", line => console.log(line))
    .on("err", line => console.error(line))
    .on("end", () => console.log("Stream closed"));
```

**Comment by aminabs** [comment]
> @rhyek As of 2.9.0 you can now stream container logs:
> 
> ```js
> const { GenericContainer } = require("testcontainers");
> 
> const container = await new GenericContainer("alpine")
>   .start();
> 
> const stream = await container.logs();
> stream
>     .on("data", line => console.log(line))
>     .on("err", line => console.error(line))
>     .on("end", () => console.log("Stream closed"));
> ```

this is not working when the container crashes on startup

**Comment by cristianrgreco** [comment]
Hi @aminabs, you can see container logs by exporting `DEBUG=testcontainers:containers` environment variable

**Comment by aminabs** [comment]
hey @cristianrgreco 
thank you for your quick reply.
I will give it a try and let all know

**Comment by aminabs** [comment]
It is included in `envirnoment` in my code: `container.withEnvironment(environment).start()`
But it did not help. I also exported the variable globally: `process.env['DEBUG'] = 'testcontainers:containers'`

**Comment by cristianrgreco** [comment]
You need to export the environment variable before testcontainers runs, for example 
`DEBUG=testcontainers:containers npm test`

**Comment by aminabs** [comment]
@cristianrgreco 
it worked! thanks
