### ISSUE TITLE
"Could not find a working container runtime strategy" when starting MySqlContainer in node inside a container

### ISSUE THREAD

**Issue by tizueh** [testcontainers/testcontainers-node#793]
**Expected Behaviour**
Testcontainers to be able to start a MySqlContainer without problem.

**Actual Behaviour**
It shows the error "Could not find a working container runtime strategy".

**Testcontainer Logs**
Error: Could not find a working container runtime strategy
|
|       12 |
|       13 |   // Test non-root user
|     > 14 |   const container = await new MySqlContainer()
|          |                     ^
|       15 |     .withUsername(username)
|       16 |     .withUserPassword(password)
|       17 |     .withDatabase(database)
|
|         at getContainerRuntimeClient (/app/node_modules/testcontainers/src/container-runtime/clients/client.ts:61:9)
|         at MySqlContainer.start (/app/node_modules/testcontainers/src/generic-container/generic-container.ts:81:20)
|         at MySqlContainer.start (/app/node_modules/@testcontainers/mysql/src/mysql-container.ts:44:7)
|         at /app/src/index.test.ts:14:21

**Steps to Reproduce**
1. clone https://github.com/timonkrebs/docker-express-react-playwright/tree/testcontainers
2. run it with [act](https://github.com/nektos/act) `act pull_request`
4. Error: Could not find a working container runtime strategy

**Environment Information**
- Operating System: WSL2
- Docker Version: 4.19.0 (106363)
- Node version: v20.15.0
- Testcontainers version: "@testcontainers/mysql": "^10.10.0"

**Comment by tizueh** [comment]
| OCI runtime exec failed: exec failed: unable to start container process: chdir to cwd ("/mnt/c/Projects/E2E/docker-express-react-playwright/e2ev") set in config.json failed: no such file or directory: unknown

**Comment by timonkrebs** [comment]
When run with `env var DEBUG=testcontainers*` i get:

| OCI runtime exec failed: exec failed: unable to start container process: chdir to cwd ("/mnt/c/Projects/E2E/docker-express-react-playwright/e2ev") set in config.json failed: no such file or directory: unknown

**Comment by cristianrgreco** [comment]
Hi, it's actually working for me, could you give more info?

```
[E2E Tests/e2e-tests] ⭐ Run Main Run E2E tests against local environment
[E2E Tests/e2e-tests]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/3] user= workdir=e2e
| yarn run v1.22.22
| $ CI=true yarn e2etest
| $ playwright test ./src
|
| Running 1 test using 1 worker
|
|   ✓  1 [chromium] › index.test.ts:5:5 › should display "Hello, TypeScript Express!" text on page (407ms)
|
|   1 passed (738ms)
| Done in 6.76s.
[E2E Tests/e2e-tests]   ✅  Success - Main Run E2E tests against local environment
```

Also, I didn't know about `act`, it's awesome! Thanks for sharing 😄

**Comment by tizueh** [comment]
Thanks, that helped. Is it expected, that starting the MySqlContainer takes about 10 seconds? Is there a way to improve that?

**Comment by cristianrgreco** [comment]
@tizueh Starting a container with `await container.start()` will make Testcontainers start the container, and wait until the wait strategy for MySQLContainer completes. The wait strategy determines when the container is ready to be used. 

In the case of MySQL, the wait strategy is to wait until until port `3306` is ready to accept connections. If it is taking 10s for the container to start, then that is simply how long the MySQL container takes to start and make that port available. If this doesn't fit your use case, you can specify your own wait strategy, but I would be careful not to introduce a case where you attempt to use the container before it is ready.

What makes you say that 10s is a long time for the container to start?

**Comment by tizueh** [comment]
For starting up a MySql container 10s seems quite good. But if I do that for every test the overhead gets significant. So if there is no way to improve that I think I have to keep the container alive for longer than only one test.

**Comment by cristianrgreco** [comment]
Ah I see, yes there are several ways to reuse the same container across tests. If you are using Jest/Vitest or another test framework that supports startup/shutdown hooks I'd recommend you start the container there, so it will be reused across all tests. If not there is a `withReuse` option, so if you have multiple tests which all attempt to start the MySQL container, if the container configuration is the same and Testcontainers detects that a suitable container is already running, it will reuse it.
