### ISSUE TITLE
Using `.withNetwork()` and `.withNetworkAliases()` on the same container leads to two network interfaces

### ISSUE THREAD

**Issue by david-mohr** [testcontainers/testcontainers-node#808]
**Expected Behaviour**
Running the following code should produce only a single interface in the log (ignoring the loopback)
```
import { Network, GenericContainer } from 'testcontainers'

const network = await new Network().start();
const container = await new GenericContainer("alpine")
  .withNetwork(network)
  .withNetworkAliases('foo')
  .withCommand(['sleep', '10'])
  .start();

const networkIpAddress = container.getIpAddress(network.getName());
console.log((await container.exec(['sh', '-c', 'ip a 2>&1'])).output.trim())
await container.stop()
```

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2766: eth0@if2767: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:c0:a8:20:02 brd ff:ff:ff:ff:ff:ff
    inet 192.168.32.2/20 brd 192.168.47.255 scope global eth0
       valid_lft forever preferred_lft forever
```

**Actual Behaviour**
The code above actually leaves two interfaces
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2761: eth1@if2762: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:11:00:07 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.7/16 brd 172.17.255.255 scope global eth1
       valid_lft forever preferred_lft forever
2763: eth0@if2764: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:1d:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.29.0.2/16 brd 172.29.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

**Testcontainer Logs**
The culprit seems to be this line of code: https://github.com/testcontainers/testcontainers-node/blob/main/packages/testcontainers/src/generic-container/generic-container.ts#L95

This class fixes the issue, but breaks DNS:
```
class SingleInterface extends GenericContainer {
  startContainer (client) {
    this.hostConfig.NetworkMode = this.networkMode
    return super.startContainer(client)
  }
}
```

If this is not a bug, what problems am I likely to run into trying to use this class as a workaround?

**Steps to Reproduce**
Run the aforementioned code

**Environment Information**
- Operating System: Fedora 40
- Docker Version: 27.1.1
- Node version: v18.20.3
- Testcontainers version: 10.11.0

**Comment by david-mohr** [comment]
It is worth noting that removing the alias leaves only a single interface

**Comment by david-mohr** [comment]
Further investigation into the Docker API and there is a way to supply the aliases at creation time which fixes the DNS issue.
https://docs.docker.com/engine/api/v1.37/#tag/Container/operation/ContainerCreate
```
class SingleInterface extends GenericContainer {
  startContainer (client) {
    this.hostConfig.NetworkMode = this.networkMode
    this.createOpts.NetworkingConfig = {
      EndpointsConfig: {
        [this.networkMode]: { Aliases: this.networkAliases }
      }
    }
    return super.startContainer(client)
  }
}
```

**Comment by cristianrgreco** [comment]
Hi @david-mohr, out of curiosity what issue is it causing having 2 network interfaces in the container?

**Comment by david-mohr** [comment]
When running concurrent tests that involve clustering, it will sometimes form a cluster across the bridge interface, meaning that we don't get proper test isolation and/or flaky results due to data leaking between tests. Not sure if there is any impact on name resolution.

**Comment by david-mohr** [comment]
I have been back through our tests and while unexpected, it is not causing any real issues for us except where we are attempting to manipulate routing or iptables. The class I shared above addresses the issue in those cases.
