### ISSUE TITLE
The created volumes by "DockerComposeEnvironment" aren't removed

### ISSUE THREAD

**Issue by danmondra** [testcontainers/testcontainers-node#816]
**Expected Behaviour**
When down is called, the volumes created by testcontainers should be removed.
Am I missing something?

**Actual Behaviour**
I create a PostgreSQL container with "DockerComposeEnvironment".
The docker-compose.yml looks like this:
```
services:
  test-db:
    image: postgres:16.2
    restart: no
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

```

It is created successfully and ready to use the database.
When I call "down" from the compose environment 5 seconds later, the containers are deleted, but the created volume "./postgres" still exists and I need to remove it manually.

**Testcontainer Logs**
```
...
  testcontainers:containers test-db-1: 2024-08-08 06:18:08.686 UTC [1] LOG:  database system is ready to accept connections +15ms
  testcontainers [DEBUG] [67d6af1c8c70] Internal port 5432 ready +1s
  testcontainers [INFO] [67d6af1c8c70] Container is ready +0ms
  testcontainers [INFO] DockerCompose environment started +0ms
Downing Containers
  testcontainers [INFO] Downing Compose environment... +5s
  testcontainers:compose Container testcontainers-893695169d7c-test-db-1  Stopping +7s
  testcontainers:containers test-db-1: 2024-08-08 06:18:14.092 UTC [1] LOG:  received fast shutdown request +5s
  testcontainers:containers test-db-1: 2024-08-08 06:18:14.093 UTC [1] LOG:  aborting any active transactions +1ms
  testcontainers:containers test-db-1: 2024-08-08 06:18:14.102 UTC [1] LOG:  background worker "logical replication launcher" (PID 196) exited with exit code 1 +9ms
  testcontainers:containers test-db-1: 2024-08-08 06:18:14.104 UTC [191] LOG:  shutting down +2ms
  testcontainers:containers test-db-1: 2024-08-08 06:18:14.107 UTC [191] LOG:  checkpoint starting: shutdown immediate +3ms
  testcontainers:containers test-db-1: 2024-08-08 06:18:14.116 UTC [191] LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.002 s, total=0.013 s; sync files=3, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB; lsn=0/19130E8, redo lsn=0/19130E8 +9ms
  testcontainers:containers test-db-1: 2024-08-08 06:18:14.126 UTC [1] LOG:  database system is shut down +9ms
  testcontainers:compose Container testcontainers-893695169d7c-test-db-1  Stopped +479ms
  testcontainers:compose Container testcontainers-893695169d7c-test-db-1  Removing +0ms
  testcontainers:compose Container testcontainers-893695169d7c-test-db-1  Removed +57ms
  testcontainers:compose Network testcontainers-893695169d7c_default  Removing +3ms
  testcontainers:compose Network testcontainers-893695169d7c_default  Removed +313ms
  testcontainers [INFO] Downed Compose environment +2s
```

**Steps to Reproduce**
1. Clone the repository to reproduce the error: [test-containers-does-not-remove-volumes](https://github.com/danmondra/test-containers-does-not-remove-volumes)
2. Execute `npm run start` to execute the index.js file and create a compose environment.
3. Wait 5s until environment is automatically downed and volumes are not removed.

**Environment Information**
- Operating System: Ubuntu 24.04 LTS
- Docker Version: Docker version 27.1.1, build 6312585
- Node version: v20.14.0
- Testcontainers version: 10.11.0

**Comment by kiview** [comment]
@cristianrgreco In tc-java, we mirror the behavior of tc-node with regards to the `-v` flag (we submit it, if the user sets `withRemoveVolumes(true)`.

We don't handle named volumes specifically, and I am equally unsure if this should be expected behavior (since it contradicts the Compose semantics around it).

Btw., maybe I am missing something, but where in this reproducer Compose file are named volumes defined or used? I can only see the bind mount `./postgres:/var/lib/postgresql/data`, which shouldn't be a volume at all.

**Comment by danmondra** [comment]
That's true, I misunderstood the difference between bind mounts and named volumes. The current behavior is expected since named volumes exist to persist data, so they shouldn't be removed automatically. 

Anyway thank you and sorry for the inconvenience.
