### ISSUE TITLE
testcontainers/ryuk:0.5.1 container does not stop after test ends when using @testcontainers/mongodb

### ISSUE THREAD

**Issue by nata7che** [testcontainers/testcontainers-node#819]
**Expected Behaviour**
Using `MongoDBContainer` according to documentation, starts 2 containers: `testcontainers/ryuk:0.5.1` and `mongo`.
After test finishes both containers stop.

**Actual Behaviour**
Using `MongoDBContainer` according to documentation, starts 2 containers: `testcontainers/ryuk:0.5.1` and `mongo`.
After test finishes the `mongo` container stops while the `testcontainers/ryuk:0.5.1` remains running, keeping the tests in pending state..
Only force stopping (Ctrl+x) helps.

**Testcontainer Logs**
```
2024-08-13 17:20:25 2024/08/13 14:20:25 Pinging Docker...
2024-08-13 17:20:25 2024/08/13 14:20:25 Docker daemon is available!
2024-08-13 17:20:25 2024/08/13 14:20:25 Starting on port 8080...
2024-08-13 17:20:25 2024/08/13 14:20:25 Started!
2024-08-13 17:20:26 2024/08/13 14:20:26 New client connected: 192.168.65.1:19399
2024-08-13 17:20:26 2024/08/13 14:20:26 Adding {"label":{"org.testcontainers.session-id=5f72293218e4":true}}
```

**Steps to Reproduce**
```
describe('mongodb client test', () => {
    private startedMongoDbContainer: StartedMongoDBContainer;

    beforeAll(async () => {
        startedMongoDbContainer = await new MongoDBContainer('mongo:6.0.1').start();

    }, 60_000);

    afterAll(async () => {
        await startedMongoDbContainer.stop();
    }, 60_000);

    it('test something', async () => {
        assert.ok(true);
    });
});
```

**Environment Information**
- Operating System: `MacOS Sonoma 14.3.1`
- Docker Version: `Docker version 25.0.2, build 29cf629`
- Node version: `v20.11.1`
- Testcontainers version: `10.11.0`

**Comment by nata7che** [comment]
adding a comment: this was found to be a false issue. Sorry for the inconvenience..

**Comment by romkogan** [comment]
> adding a comment: this was found to be a false issue. Sorry for the inconvenience..

What was the problem? I have the same issue
