### ISSUE TITLE
complex shell commands fail with exec()

### ISSUE THREAD

**Issue by jayarjo** [testcontainers/testcontainers-node#82]
How does one exec complex commands on a container? Something like `seq 5 | xargs -I INDEX echo "hi"` for example? I tried all kind of things, but it fails, obviously command gets mingled on its way to the container. Escaping quotes or pipe characters doesn't seem to have any effect. Is this even possible?

**Comment by cristianrgreco** [comment]
Have you tried `.withCmd(['sh', '-c', 'seq 5 | xargs -I INDEX echo "hi"'])` ?

**Comment by jayarjo** [comment]
Magic! Thanks.
