### ISSUE TITLE
Can't run MySql based tests on gitlab runner.

### ISSUE THREAD

**Issue by msahakyan-korio** [testcontainers/testcontainers-node#820]
Hi! I'm using nest.js + MySql +  testcontainers. Running tests locally work fine but on gitlab CI it fails.

My runner config:

[[runners]]
  name = "Readonic CI Runner"
  url = "https://gitlab.sone-name.ca/"
  id = 15
  token = "XXXXXXXXXXXXX"
  token_obtained_at = 2024-08-14T21:23:56Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  environment = ["DOCKER_TLS_CERTDIR=/certs"]
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "ubuntu:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
    network_mtu = 0
    
    My gitlab-ci file:
    
    stages:
  - test

test:
  stage: test
  image: node:20.8.0
  services:
    - docker:dind
  variables:
    TESTCONTAINERS_RYUK_DISABLED: "true"
    DOCKER_HOST: "unix:///var/run/docker.sock"
    DOCKER_TLS_VERIFY: '0'
  script:
    - npm install
    - npm run test
  tags:
    - readonic-ci-runner
    
    
 Test env setup code:
 
 
 import {
  MySqlContainer
} from '@testcontainers/mysql';
import {StartedTestContainer} from 'testcontainers';
export class TestContainersEnvironment {
  private containers: StartedTestContainer[] = [];

  async setup() {
    const mySqlContainer = await new MySqlContainer()
        .withExposedPorts(3306)
        .start()

    this.containers.push(mySqlContainer);

    return {
      PORT: 3000,
      DATABASE_LOGGING: 'false',
      DATABASE_SYNC: 'true',
      DATABASE_HOST: mySqlContainer.getHost(),
      DATABASE_USER: mySqlContainer.getUsername(),
      DATABASE_PASSWORD: mySqlContainer.getRootPassword(),
      DATABASE_PORT: mySqlContainer.getMappedPort(3306),
      DATABASE_NAME: mySqlContainer.getDatabase(),
    };
  }

  async teardown() {
    while (this.containers.length) {
      await this.containers.pop().stop();
    }
  }
}

The Error I'm getting:

Tearing down test environment.
FAIL test/app.spec.ts
  ● Test suite failed to run
    Port 32781 not bound after 120000ms
       8 |   private containers: StartedTestContainer[] = [];
       9 |
    > 10 |   async setup() {
         |                            ^
      11 |     const mySqlContainer = await new MySqlContainer()
      12 |         .start()
      13 |
      
      
 Note:  Port number is being incremented every time like 32781, 32782, ...

**Comment by cristianrgreco** [comment]
https://testcontainers.org/supported_docker_environment/continuous_integration/gitlab_ci/
