### ISSUE TITLE
Make Colima work out of the box

### ISSUE THREAD

**Issue by alecmev** [testcontainers/testcontainers-node#824]
Is there a reason why `Wait.forListeningPorts` isn't the default behavior? I'm not sure if I'm reading it right, but [it seems like it is in `testcontainers-go`](https://github.com/testcontainers/testcontainers-go/blob/0d9e934ec7f62a1e164f7ce4f7560fa5c6b97d2a/lifecycle.go#L252), which makes it "just work" ([source](https://golang.testcontainers.org/system_requirements/using_colima/)):

> As of Colima v0.4.0 it's recommended to set the active Docker context to use Colima. After the context is set Testcontainers for Go will automatically be configured to use Colima.

**Comment by cristianrgreco** [comment]
It is the default behaviour

**Comment by alecmev** [comment]
> It is the default behaviour

Hmm, I could be misunderstanding something, but doesn't the page you link to contradict this?

> ... wait strategies such as waiting for a health check or a log message are insufficient when using Colima. You can use a composite wait strategy to additionally wait for a port to be bound, on top of an existing wait strategy.

**Comment by cristianrgreco** [comment]
> Is there a reason why Wait.forListeningPorts isn't the default behavior

My answer was to this question. 

Users are free to use whatever wait strategy they wish. What you quoted explains that there is a known issue with colima if you deviate from the listening ports wait strategy (which is the default wait strategy).

**Comment by alecmev** [comment]
Ah, I understand, thanks, I see it:

https://github.com/testcontainers/testcontainers-node/blob/055c02f074e079996a2ba5be409dd0f3c8646252/packages/testcontainers/src/generic-container/generic-container.ts#L48

Okay, then my question is, why is this overridable? Seems like most modules forget to add `Wait.forListeningPorts` when using a custom strategy.

**Comment by alecmev** [comment]
@cristianrgreco Friendly ping, just in case you missed this. I'm interested in getting to the bottom of this because I'd be willing to at least update all modules to include `forListeningPorts` in their wait strategies if this is an oversight.
