### ISSUE TITLE
withLogConsumer does not stream stdout/stderr from executing commands

### ISSUE THREAD

**Issue by huksley** [testcontainers/testcontainers-node#828]
**Expected Behaviour**

When creating a container using `withLogConsumer` to collect logs from executing commands, it is expected that the output of executing command will be streamed during the (potentially log running operation) exec

**Actual Behaviour**

No logs are streamed

**Testcontainer Logs**
See logs in 1st comment of this gist https://gist.github.com/huksley/4f3d2455d65e154d4fb296fca4e49897?permalink_comment_id=5174757#gistcomment-5174757

**Steps to Reproduce**
1. Get complete example from https://gist.github.com/huksley/4f3d2455d65e154d4fb296fca4e49897
2. Run node t.js 
3. Expect lines `LOG 1` to be printed
4. Only see `RESULT { output: '1\n', exitCode: 0 }` is printed 

**Environment Information**
- Operating System: MacOS X Sonoma 14.5 (23F79)
- Docker Version: 26.1.1
- Node version: v18.18.2
- Testcontainers version:  testcontainers@10.12.0

**Comment by cristianrgreco** [comment]
Hi @huksley, this is the same behaviour in the other Testcontainers languages. The log consumer returns output from the main container process. Running `container.exec` creates a new process with its own output. For this reason `container.exec` returns its own object with the output.
