### ISSUE TITLE
Ability to restart a container

### ISSUE THREAD

**Issue by JeremyLoy** [testcontainers/testcontainers-node#83]
Adding a `.restart()` method on the StartedTestContainer interface would be really useful, and possibly more efficient/faster than having to `.stop()` and `.start()` in between tests.

e.g. Writing integration tests for a MySQL database where each test invocation is expected to have an empty database.

**Comment by cristianrgreco** [comment]
Hi @JeremyLoy, thanks for raising the issue. Out of curiosity, would it not be significantly faster to clear the database on an already running container, instead of stopping and starting a new one?

**Comment by JeremyLoy** [comment]
Maybe/maybe not. It depends on the capabilities of whatever process is being containerized. I only used a database as an example, but users could do anything tbh
