### ISSUE TITLE
Ability to run withPrivilegedMode

### ISSUE THREAD

**Issue by imdark** [testcontainers/testcontainers-node#84]
this exists in the java implementation

**Comment by cristianrgreco** [comment]
Hi @imdark, thanks for raising the issue!
What's the use case you have for running in privileged mode?

**Comment by imdark** [comment]
My production system uses privileged for multiple reasons, and i am writing integration code for it

**Comment by cristianrgreco** [comment]
Hi @imdark, do you want to review the PR or are you happy for me to release it?

**Comment by cristianrgreco** [comment]
Available in 2.11.0.
