### ISSUE TITLE
stderr output

### ISSUE THREAD

**Issue by jeronimo-planet** [testcontainers/testcontainers-node#842]
When we do an exec, we get an { ouput, exitCode }.
It would be nice if we could get a { stdout, stderr, exitCode }.
Do you guys think it's possible?

**Comment by kiview** [comment]
This is the result type in tc-java, so that would be a quite alinged implementation:
```java
class ExecResult {
    int exitCode;
    String stdout;
    String stderr;
}
```

**Comment by cristianrgreco** [comment]
PR welcome. I'd suggest keeping the existing `output` field, and adding the `stdout`/`stderr` fields. Otherwise we lose the ability to log the output in time order. Removing the `output` would also be a breaking change.

**Comment by cristianrgreco** [comment]
This will be released shortly
