### ISSUE TITLE
Cannot define container hostname

### ISSUE THREAD

**Issue by polRk** [testcontainers/testcontainers-node#865]
When I run docker image with `-h --hostname` I can define container hostname. In Testcontainers NodeJS I can not define host (but in go I can)

**Comment by joebowbeer** [comment]
Why is this needed? Just curious.

> By default, Docker assigns a random hostname to a container if you don't specify one explicitly. This hostname is usually derived from the container ID.

I wonder if this interacts badly with the resolveHost logic in the Localstack module, though I'm probably confusing internal and external host names.

**Comment by polRk** [comment]
> Why is this needed?

YDB daemon cannot start when localhost is specified in the configs, and the node (in this case, the container) has a different hostname.

**Comment by polRk** [comment]
> You can get the hostname via `container.getHost()`

I don't need it, I need the container's hostname to match the config. And the only way to record always single execution in different environments is to run the container via `docker -h/--hostname localhost`

**Comment by cristianrgreco** [comment]
`I can only pass configs as mount and only before launching my ydb daemon`

This is more a limitation of the setup. It should be possible to do whatever you like before your tests start, and inject whatever is needed into the environment or wherever else YBD reads from. Telling the container its host is something it isn't is just going to cause more problems down the line.

I'll close this issue as it doesn't seem to be something to recommend and it's the first I've heard of it being an issue. Will reopen in future if it's necessary.

> In Testcontainers NodeJS I can not define host (but in go I can)

FYI TC-go forwards you the entire Docker API, so you can do whatever you want. TC-node does not follow this practice.
