### ISSUE TITLE
StartedGenericContainer is not exported

### ISSUE THREAD

**Issue by shellscape** [testcontainers/testcontainers-node#88]
When using TypeScript with this project, we need `StartedGenericContainer` to be exported in order to define a container in a top level scope properly, and use the container without assigning it to `any`.

For example:

```typescript
export let container: StartedGenericContainer;

export const start = async () => {
    container = await new GenericContainer('postgres', '11.2-alpine')
      .withExposedPorts(5432)
      .start();
};
```

This is currently not possible, and `let container: any;` must be used.

**Comment by cristianrgreco** [comment]
Hi @shellscape, any reason you can't use the exported interface? `StartedTestContainer`

**Comment by shellscape** [comment]
Because it's not actually exported

**Comment by cristianrgreco** [comment]
`StartedTestContainer`, the interface. 
Not `StartedGenericContainer`, the implementation. 
It's exported: https://github.com/testcontainers/testcontainers-node/blob/master/src/index.ts#L2

**Comment by shellscape** [comment]
Hmmm I wasn't seeing that locally. Please allow me a few hours and I'll give that a second look.

**Comment by shellscape** [comment]
Had to clear some cache and I was able to resolve the `StartedTestContainer` export. Thanks for the look.
