### ISSUE TITLE
Select which Dockerfile to build from (i.e. support -f flag)

### ISSUE THREAD

**Issue by Johnny850807** [testcontainers/testcontainers-node#95]
In my application, I have to separate different test environments into different Dockerfile,
and name each of them in different Dockerfile names. (e.g. Dockerfile-a, Dockerfile-b, ...)

Can I achieve this? 
Since I didn't find any **fileName** support from the `GenericContainer.fromDockerfile` api.

Thanks a lot!

**Comment by cristianrgreco** [comment]
Hi @Johnny850807, I've created a PR https://github.com/testcontainers/testcontainers-node/pull/96. 
I'll merge it unless you have any concerns?

**Comment by Johnny850807** [comment]
@cristianrgreco It looks great, thank you!

**Comment by cristianrgreco** [comment]
Great! Thanks for raising this, it's available in 2.16.0
